### ISSUE TITLE
[ASK] Large data import

### ISSUE THREAD

**Issue by fulljackz** [LycheeOrg/Lychee-v3#1]
Hello,
I have 2TB on a nas which represent : ~900 000 files into 150 000 folders.
Actually I check the pictures with a cifs share.

I would like to use a beautiful web interface to access my files.

- Is it possible to mount a smb share and index the data ?
- Is it possible to index this amount of data ?
- What are the specs for this kind of server.

Thanks for your answers,

Cheers.

**Comment by fulljackz** [comment]
I just gave a try and tried to import from local server giving my mount point.

As a test, I just tried with a limited set of albums. The problem is the source deletion, is it possible do disable it ?

**Comment by crazikPL** [comment]
@fulljackz If webserver has no permissions to delete, then it won't remove your dirs/files. It's the simplest way to achieve this.

**Comment by fulljackz** [comment]
Ok, seems legits :)
Thanks.
