### ISSUE TITLE
Change location of /upload directory

### ISSUE THREAD

**Issue by phischmi** [LycheeOrg/Lychee-v3#103]
Hi,
is it possible to change the location of the /upload-directory?

I'd like to have the /upload-directory under /mnt/hdd/lychee while the installation of lychee will be under /var/www/lychee.

Is this somehow possible?

**Comment by d7415** [comment]
I set up similar (I only linked the big and import folders) using symlinks. So from /var/www/lychee, `mv uploads /mnt/hdd/lychee`, `ln -s /mnt/hdd/lychee/uploads` or some such. They'll still need to be read+writeable by the user your httpd is using, and there maybe be some hidden gotchas (e.g. selinux might get upset).
