### ISSUE TITLE
Blank page on fresh install

### ISSUE THREAD

**Issue by hermzz** [LycheeOrg/Lychee-v3#105]
### Detailed description of the problem

When trying to install from a fresh git clone nothing comes up and the JS console says: `TypeError: data.config is undefined` (https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/lychee.js#L350).

When there is no config file `/php/index.php` returns `{"status":0}` and so trying to access `data.config.justified_layout` fails.

### Steps to reproduce the issue

Removing the `data/config.php` file should do it.

### Browser and system

Firefox/Linux

**Comment by ildyria** [comment]
Thank you for spotting that one! :+1:
