### ISSUE TITLE
git pull to latest version results in blank screen

### ISSUE THREAD

**Issue by fatherb** [LycheeOrg/Lychee-v3#107]
Just did a git pull to look at the new Flickr style for Lychee but got a blank page upon update. Data and uploads still have information in them.

My install is here: 
http://phpstack-59857-660191.cloudwaysapps.com/Lychee/

I did have it going pretty good on 3.2 version.

### Detailed description of the problem
Blank black screen and 'Error: server error or api not found' is briefly shown on screen before disappearing.

This shows in the console of Chrome. 
VM517:1 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://phpstack-59857-660191.cloudwaysapps.com/Lychee/php/index.php with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

### Steps to reproduce the issue
git pull - await download - then try to visit Lychee

### Output of the diagnostics (Settings => Diagnostics)

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version (json):  3.2.0
DB Version:             update_030202
System:                 Linux
PHP Version:            7
MySQL Version:          50562
Imagick:                1
Imagick Active:         1
Imagick Version:        1673
GD Version:             bundled (2.1.0 compatible)
Plugins: 

### Browser and system
Chrome
OSX 10.12.6

**Comment by ildyria** [comment]
When I open the URL you gave me I get as warnings:
```
GET https://phpstack-59857-660191.cloudwaysapps.com/Lychee/dist/main.css net::ERR_CERT_AUTHORITY_INVALID
GET https://phpstack-59857-660191.cloudwaysapps.com/Lychee/dist/main.js net::ERR_CERT_AUTHORITY_INVALID
GET https://phpstack-59857-660191.cloudwaysapps.com/Lychee/favicon.ico net::ERR_CERT_AUTHORITY_INVALID
```

Changing the URL for : https://phpstack-59857-660191.cloudwaysapps.com/Lychee/
gives me a self-signed certificate warning. If I accept it everything seems to work properly.

Also you can try to refresh your cache with CTRL+F5.

**Comment by fatherb** [comment]
eeekkk. well, that's embarrassing. Thanks for taking the time to look. Sorry!

**Comment by ildyria** [comment]
At least I hope you are happy with the flickr layout. :)

**Comment by fatherb** [comment]
Yes it's excellent. Thanks very much for adding it. Makes a big difference seeing whether an image is a portrait or landscape in the previews rather than having to click it to find out.
