### ISSUE TITLE
No tagged "latest release"

### ISSUE THREAD

**Issue by suntorytimed** [LycheeOrg/Lychee-v3#11]
### Detailed description of the problem
In the old organisation the newest tag/release was marked as latest release which allowed accessing it via API calls (f. e. to download the latest release into a container or link to the latest release with a fixed link).

To create this API Tag for the latest tag/release you have to either create a release via the [web interface](https://help.github.com/articles/creating-releases/) or use [GitHubs API](https://developer.github.com/v3/repos/releases/#create-a-release) to mark the right tag.
### Steps to reproduce the issue
Open:
https://api.github.com/repos/LycheeOrg/Lychee/releases/latest
### Output of the diagnostics (Settings => Diagnostics)
-
### Browser and system
-

**Comment by LudovicRousseau** [comment]
I created a release for v3.1.6.

**Comment by suntorytimed** [comment]
Thanks. Please keep in mind that this is an ongoing process and has to be done with every new release.

**Comment by LudovicRousseau** [comment]
😃
