### ISSUE TITLE
Unable to clone LycheeOrg/Lychee repo using GitHub Desktop on Windows because of question mark in filename

### ISSUE THREAD

**Issue by colinmcglothlin** [LycheeOrg/Lychee-v3#110]
### Detailed description of the problem
I am unable to clone the LycheeOrg/Lychee repository to a local repository using GitHub Desktop client on Windows 7 64-bit.  The file that causes the error has a question mark in it, which is an illegal character on Windows.

GitHub Client outputs this error:
"error: unable to create file How-do-I-migrate-from-electerious-to-LycheeOrg?.md: Invalid argument"

### Steps to reproduce the issue
1. Fork LycheeOrg/Lychee.
2. Click "Clone or Download"
3. Click "Open in Desktop"
4. Click "Clone" in GitHub Desktop window that appears
5. After GitHub Desktop finished attempting to clone, the error message appears on the 2nd to last line of the log that appears.

### Browser and system
Chrome
GitHub Desktop 1.5.0
Windows 7 64-bit

**Comment by ildyria** [comment]
Solved. :)

**Comment by colinmcglothlin** [comment]
Awesome! Thanks!
