### ISSUE TITLE
git pull error

### ISSUE THREAD

**Issue by bigfoot50** [LycheeOrg/Lychee-v3#114]
Hi,

when I update via :
git pull https://github.com/LycheeOrg/Lychee.git

There will be an error:
Von https://github.com/LycheeOrg/Lychee
 * branch            HEAD       -> FETCH_HEAD
Aktualisiere b5fe57c..087364e
error: Your local changes to the following files would be overwritten by merge:
        .gitignore
        .htaccess
        Lychee-front
        README.md
        dist/main.css
        dist/main.js
        dist/view.js
        docs
        index.html
        php/Access/Admin.php
        php/Locale/French.php
        php/Modules/Album.php
        php/Modules/Albums.php
        php/Modules/Database.php
        php/Modules/Photo.php
        php/Modules/Settings.php
        php/database/update_030109.php
        php/define.php
        php/index.php
        plugins/Diagnostics/index.php
        view.php
Please, commit your changes or stash them before you can merge.
Aborting

What can I do.

**Comment by ildyria** [comment]
You can try:
```sh
git checkout -b temp
git add -u
git commit -m "personal"
git checkout master
git pull
```

This should be quite safe to do. 


sent from my phone.​

Le 22 nov. 2018 à 21:24, à 21:24, bigfoot50 <notifications@github.com> a écrit:

**Comment by ildyria** [comment]
You can try:
```sh
git checkout -b temp
git add -u
git commit -m "personal"
git checkout master
git pull
```
This should be quite safe to do.

**Comment by bigfoot50** [comment]
same error. Strange...the last two times it worked perfect.

**Comment by bigfoot50** [comment]
Chaos perfect...

error: 'commit' is not possible because you have unmerged files.
fatal: Exiting because of an unresolved conflict.
error: unable to index file docs

...rebuilt the server from backup....

So an build in updater will be great for future.

**Comment by bigfoot50** [comment]
Now I made an manual update from the master file.

git pull
fatal: Not a git repository (or any parent up to mount point /var/www/html/lychee)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

The mount point is wrong. "/var/www/html/lychee/folder" is the right one. How can I change the settings of the mount point?

**Comment by ildyria** [comment]
Given all your problems my advice will be to follow those steps:
https://github.com/LycheeOrg/Lychee/issues/65#issuecomment-430301401

**Comment by bigfoot50** [comment]
That´s the way I did it now. It worked and I put all the commands in a bash script (I must update 5 instances), but it´s not the sense behind git. 

I really love lychee, but update could be more easier.

**Comment by bigfoot50** [comment]
Also worked:
git init
git pull https://github.com/LycheeOrg/Lychee.git

I hope that´s the right way

**Comment by ildyria** [comment]
> I really love lychee, but update could be more easier.

Well update is meant to be just a `git pull` if it is something else then it means that something went wrong in your server.

Happy to hear that it is solved. :+1:
