### ISSUE TITLE
Lychee-front fails to clone from forked repo

### ISSUE THREAD

**Issue by bennettscience** [LycheeOrg/Lychee-v3#115]
### Detailed description of the problem
Forked the LycheeOrg repo and tried to clone the fork to my machine using `git clone --recurse-submodules https://github.com/bennettscience/lychee.git lychee-fork`

The submodules are registered correctly but the clone fails when trying to actually pull the folder. The docs submodule pulls correctly into the clone.

```
Cloning into '/Users/bbennett/Desktop/dev/lychee-fork/Lychee-front'...
remote: Repository not found.
fatal: repository 'https://github.com/bennettscience/Lychee-front.git/' not found
fatal: clone of 'https://github.com/bennettscience/Lychee-front.git' into submodule path '/Users/bbennett/Desktop/dev/lychee-fork/Lychee-front' failed
```

### Steps to reproduce the issue
1. Fork the `LycheeOrg/Lychee` repo
2. Clone using `git clone --recurse-submodules`

### Browser and system
MacOS 10.13.6
git 2.17.1

**Comment by ildyria** [comment]
**You also need to fork Lychee-front** before doing the git clone. But I agree that we should indicated it in the documentation.
