### ISSUE TITLE
Improved background for slideshow like fgallery

### ISSUE THREAD

**Issue by chrobs** [LycheeOrg/Lychee-v3#118]
### Detailed description of the problem
I really like the adaptive/blured background of fgallery and would love to see it implemented in lychee someday.

Have a look:
https://www.thregr.org/~wavexx/software/fgallery/demo/#7

### Steps to reproduce the issue
The fgallery project is doing the blur image from the thumbnail as follows:
```
  # blur
  sys('convert', '-quiet', "$out/$fthumb",
      '-virtual-pixel', 'Mirror',
      '-gaussian-blur', "0x$backblur",
      '-scale', "$backsize[0]x$backsize[1]",
      '-quality', '90', "$out/$fblur");
```
https://github.com/wavexx/fgallery/blob/master/fgallery#L741

**Comment by ildyria** [comment]
I don't like using system call and that would make us generate yet another image to store on the server...
The following solution is more elegant in my opinion:

```html
<!DOCTYPE html>
<html>
<head>
<style>
img.background {
    width: 110%;
    height: 110%;
    position: absolute;
    left: -5%;
    top: -5%;
    z-index: -1;
    -webkit-filter: blur(35px); /* Safari 6.0 - 9.0 */
    filter: blur(35px);
}

img.circle {
    display: block;
    margin: 0 auto;
    height: auto;
    width: 90%;
}
</style>
</head>
<body>

<img class="background" src="https://www.w3schools.com/cssref/pineapple.jpg" alt="Pineapple">
<img class="circle" src="https://www.w3schools.com/cssref/pineapple.jpg" alt="Pineapple">

<h1>The filter Property</h1>

<p>Blurred background:</p>
<p><strong>Note:</strong> The filter property is not supported in Internet Explorer, Edge 12, or Safari 5.1 and earlier.</p>

</body>
</html>
```

**Comment by chrobs** [comment]
Using system call is pretty nasty, especially from an interactive php application ;)

Your solution looks very good and I really like the eliminated need to store an additional picture

**Comment by ildyria** [comment]
I don't really have time to do that now, but if you want to give a try, I think you should look in: 
~https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/view.js#L488~
here: https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/build.js#L174

**Comment by ildyria** [comment]
Fixed with Lychee-Laravel (future v4)
