### ISSUE TITLE
Update System Requirements

### ISSUE THREAD

**Issue by chrobs** [LycheeOrg/Lychee-v3#119]
### Detailed description of the problem

I had a few struggles with the new Video/Thumbnail feature because there was no hint at all that the server system itself should have ffmpeg installed in additiion to the php-ffmpeg via composer.

Even if I agree that the requirement is quite obvious, Lychee fails silently to upload a new video if php-ffmpeg is installed but the ffmpeg/ffprobe binaries cannot be found on the server system.

Therefore, I suggest to extend the system requirements wiki page accordingly.

https://github.com/LycheeOrg/Lychee/wiki/Installation

**Comment by chrobs** [comment]
Short supplement: 
update the suggested max file size for uploads in `php.ini`. At the moment, the wiki states
`
upload_max_filesize = 20M
`
and I think for videos it should be 250MB or more (60MB for a 30 seconds Video, recorded with my old Nexus 5)

**Comment by ildyria** [comment]
@chrobs You should now be able to edit the wiki pages. :)

**Comment by chrobs** [comment]
@ildyria thanks, done.
