### ISSUE TITLE
Login dialog won't trigger password save option

### ISSUE THREAD

**Issue by ErikKrause** [LycheeOrg/Lychee-v3#12]
If I login to Lychee I get no option to save my login credentials by the browser. 

Firefox 61.0.1 64bit on Windows 10

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.1.6
DB Version:      030102
System:          Linux
PHP Version:     5.6
MySQL Version:   50721
Imagick:         1
Imagick Active:  1
Imagick Version: 1673
GD Version:      bundled (2.1.0 compatible)
Plugins:

**Comment by fly-man-** [comment]
This is by design in Firefox, not much we can do about it.

**Comment by ErikKrause** [comment]
Sorry, this is not by design in Firefox, rather by design in Lychee. The Lychee login page is the first I encounter this. All others I came across (26 this year) allow to save the password and username.

**Comment by fly-man-** [comment]
Perhaps I have to explain this a bit more:

Firefox does a reload of the page, making it seem that the page isn't reloaded. This is the reason why the login page isn't re-triggered thus not giving the popup to do the saving of the username/password.

**Comment by ErikKrause** [comment]
Ok. But how do other pages do it? It must be pretty uncommon how Lychee does it, given I have not encountered this before.

However, I'd like to have Lychee not requiring a login at all, since this is for an internal page only. It's a nuisance that I have to use a password where it is not necessary. This should be configurable, like many other things, too (language for example, or social networks in menu).

**Comment by at0dd** [comment]
Could this be because the form is wrapped with a `div` tag instead of a `form`? I'll do some testing and report back.
