### ISSUE TITLE
License select is not pre-selected

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-v3#120]
### Detailed description of the problem

When you want to update the license chosen. The current license is not pre-selected.

### Steps to reproduce the issue

Update to 3.2.5, select a license, try to select a new one.

@bennettscience can you have a look at it? 
This line should help you: https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/view.js#L668

**Comment by bennettscience** [comment]
Yeah, I'll take a look. I need to work out a way to wait for the `basicModal` to call the update function because the element doesn't exist on load.

**Comment by ildyria** [comment]
Fixed with https://github.com/LycheeOrg/Lychee/commit/42b2be606587ab9840deccada6760fa5ee1b2012
