### ISSUE TITLE
Document how to enable .htaccess for apache2

### ISSUE THREAD

**Issue by LudovicRousseau** [LycheeOrg/Lychee-v3#122]
### Detailed description of the problem

By default (at least on Debian 9) the use of `.htaccess` is **not** enabled for apache2.

I had to enable it by adding this section in the corresponding `/etc/apache2/sites-available/foo` file:
```
  <Directory "/var/www/Lychee">
    AllowOverride All
  </Directory>
```
Maybe `AllowOverride All` is too generous and should be limited.

I propose to document this in https://github.com/LycheeOrg/Lychee/wiki/Installation

### Steps to reproduce the issue

- install apache2
- install Lychee
- check the Content-Security-Policy header returned by the server

### Browser and system

Firefox 63.0.3 on macOS Mojave 10.14.1
server is Debian 9.6 (stable) using apache2 version 2.4.25

**Comment by d7415** [comment]
I wonder if this may be better placed in the FAQ, or on an apache-specific wiki page? There are currently no httpd-specific instructions on that page, and it could easily get cluttered.

**Comment by bennettscience** [comment]
It could make sense on the Wiki page, after all that's where `php.ini` modifications are listed. It's a good note for people who haven't (or who don't regularly) set up their own servers. Most hosted companies already have the `AllowOverride` and configure different sites with `.htaccess`.

I'm not a server admin, but how much of a security gap is using `.htaccess` vs configuring Apache directly on the server? Especially considering many users wouldn't have access to core Apache config settings anyways?

**Comment by LudovicRousseau** [comment]
I agree to put this information in the FAQ.
If we have other Apache specific configuration to mention we could create a wiki page for Apache.

**Comment by d7415** [comment]
We could potentially also include example configuration files for various httpds in a "sample webserver configuration" page or something?

> It could make sense on the Wiki page, after all that's where `php.ini` modifications are listed.

PHP is required, but apache is not. It should definitely be somewhere though, and perhaps pointed to by the Installation page (like the FAQ is now, which is why that was my first thought).

**Comment by bennettscience** [comment]
Added `.htaccess` settings to the FAQ.
