### ISSUE TITLE
Adding to documentation

### ISSUE THREAD

**Issue by bennettscience** [LycheeOrg/Lychee-v3#123]
I'd be happy to help update some of the documentation (#122, #119, `Changelog.md`) but there's no way to submit a PR for wiki pages. There is a [suggested workaround](https://stackoverflow.com/a/11481887/2278429) on how to make the process smoother, but I wanted to see if this had been discussed at all before forging ahead.

**Comment by LudovicRousseau** [comment]
There is no PR for wiki pages. Just use the Edit button and change the page from your browser

Any github user should be able to edit any wiki page.
If you have an access right issue just tell us here.

**Comment by d7415** [comment]
The permissions seem to be more limited here. I don't have an edit button either.

**Comment by LudovicRousseau** [comment]
I disabled the "Restrict editing to users in teams with push access only".
It should work better now.

**Comment by d7415** [comment]
Thanks. That worked.

**Comment by ildyria** [comment]
@d7415 , @bennettscience  on a similar topic, would you be interested in joining the LycheeOrg organisation ? :)

**Comment by d7415** [comment]
Sure :) My time tends to come in fits and bursts, but I'm happy to contribute when I have time.

**Comment by bennettscience** [comment]
@ildyria Sounds good to me 👍
