### ISSUE TITLE
Server Error or API not found + updates 030203 to 030205 not applying

### ISSUE THREAD

**Issue by Espionage724** [LycheeOrg/Lychee-v3#128]
I tried uploading a picture to my Lychee instance, and after the upload, the page was blank. Refreshing the page shows the Server Error or API not found message. Looking at the browser console, index.php is 502.

The album I was trying to upload the picture to is now inaccessible (blank with the index.php 502), but other albums load fine.

```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!


System Information
------------------
/var/www/media/Lychee-front/package.json not found. Please do: git submodule init ; git submodule update
DB Version:             update_030205
System:                 Linux
PHP Version:            7.2
MySQL Version:          50505
Imagick:                1
Imagick Active:         1
Imagick Version:        1687
GD Version:             2.2.5
Plugins:                
```
Log (errors):
```
2018-09-18 22:05:28 - error - Lychee\Modules\Database::createTables (181) 	- Table 'lychee.lychee_settings' doesn't exist
2018-09-18 22:05:28 - error - Lychee\Modules\Database::createTables (226) 	- Table 'lychee.lychee_albums' doesn't exist
2018-09-18 22:05:28 - error - Lychee\Modules\Database::createTables (249) 	- Table 'lychee.lychee_photos' doesn't exist
2018-09-19 05:38:51 - error - Lychee\Modules\Photo::add (100) 	- The uploaded file was only partially uploaded
2018-09-19 05:38:51 - error - Lychee\Modules\Photo::add (100) 	- The uploaded file was only partially uploaded (this is spammed at least 40 times with the same timestamp)
2018-09-19 08:55:13 - error - Lychee\Modules\Album::getPublic (418) 	- Could not find specified album
2018-11-23 12:20:50 - error - update_030203 (12) 	- Unknown column 'small' in 'field list'
2018-11-23 12:20:50 - error - update_030204 (12) 	- Unknown column 'lens' in 'field list'
2018-11-29 00:07:33 - error - update_030205 (12) 	- Unknown column 'license' in 'field list'
```

I'm thinking it's related to https://github.com/LycheeOrg/Lychee/issues/111. I tried the update.php suggestion; it reports done from both a browser and console php, but nothing changes. Trying to manually run the updates 030203, 030204, and 030205 report an error at line 11 (either at the query or result lang settings section).

I'm using Fedora Workstation 29 and Firefox 63.0.3.

My Lychee instance runs on Ubuntu 18.04.1 and auto-updates from git (master) daily. I only do a git pull, and I don't visit the instance daily. I wonder if there's something else I should be doing to get any new updates to trigger?

**Comment by ildyria** [comment]
1. Verify that your database is actually up-to-date:
```sh
mysql lychee -u <user> -p
<password>
SELECT * FROM lychee_photos LIMIT 1;
```
this will show you the column names. Check that `lens`, `small`, `license` exist.

```
2018-09-19 08:55:13 - error - Lychee\Modules\Album::getPublic (418) 	- Could not find specified album
```
I would go manually in the database (using e.g. [phpmyadmin](https://www.phpmyadmin.net/)) and verify the values in the table `albums` for the problematic album.

> and 030205 report an error at line 11 (either at the query or result lang settings section).

can you post that error ?

**Comment by Espionage724** [comment]
>     1. Verify that your database is actually up-to-date:
>     this will show you the column names. Check that lens, small, license exist.

Those 3 databases (lens, small, license) seem to exist

```
espionage724@kraityn:/var/www/media$ sudo mysql lychee
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 651
Server version: 10.1.34-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [lychee]> SELECT * FROM lychee_photos LIMIT 1;
+----------------+---------------------+-------------+--------------------------------------+------+--------+------------+-------+--------+--------+------+----------+------+---------+------+-----------------------+-------+------------+------+---------------------------------------+----------------+------------------------------------------+--------+-------+---------+
| id             | title               | description | url                                  | tags | public | type       | width | height | size   | iso  | aperture | make | model   | lens | shutter               | focal | takestamp  | star | thumbUrl                              | album          | checksum                                 | medium | small | license |
+----------------+---------------------+-------------+--------------------------------------+------+--------+------------+-------+--------+--------+------+----------+------+---------+------+-----------------------+-------+------------+------+---------------------------------------+----------------+------------------------------------------+--------+-------+---------+
| 15373501585670 | IMG_20161202_024119 |             | d88e48da0df9f2a2c00a2eb9ff1770ff.jpg |      |      0 | image/jpeg |  3264 |   2448 | 1.7 MB | 1376 | f/2.4    | LGE  | Nexus 5 |      | 41663692/1000000000 s | 4 mm  | 1480646479 |    0 | d88e48da0df9f2a2c00a2eb9ff1770ff.jpeg | 15373499941865 | 3b761cc18e85608b9e16278600361d01951635fd |      1 |     0 |         |
+----------------+---------------------+-------------+--------------------------------------+------+--------+------------+-------+--------+--------+------+----------+------+---------+------+-----------------------+-------+------------+------+---------------------------------------+----------------+------------------------------------------+--------+-------+---------+
1 row in set (0.00 sec)
```

> can you post that error ?

```
espionage724@kraityn:/var/www/media$ sudo -u www-data php /var/www/media/php/database/update_030205.php
PHP Fatal error:  Uncaught Error: Class 'Lychee\Modules\Database' not found in /var/www/media/php/database/update_030205.php:11
Stack trace:
#0 {main}
  thrown in /var/www/media/php/database/update_030205.php on line 11
```

**Comment by ildyria** [comment]
You are not supposed to execute the updates like that (`php <file.php>`) they are used by inclusion because you need the definitions in `config.php` and others stuff.
So that error is not suprising. This is why I said that in the other issue:

> If you create a file `php/update.php` containing this:
> 
> ```php
> <?php
> 
> namespace Lychee;
> 
> use Lychee\Modules\Config;
> use Lychee\Modules\Database;
> use Lychee\Modules\Validator;
> use Lychee\Modules\Response;
> 
> require(__DIR__ . '/define.php');
> require(__DIR__ . '/autoload.php');
> 
> // this should do the update by itself
> Database::get();
> Response::json('done');
> exit();
> ```
> 
> and you call it from your browser it should apply the update. The fact that you have the unknown column warning sound more like your user does not have the ALTER right on the tables in your database. You might want to update that.

Anyway, it looks like to me that your tables have been updated so this is not where the problem is.

You can actually find which images is generating your problems:
When you click on the album, the URL will change for something like: `<baseurl>/#<numbers>`
these numbers represent the ID of your URL.
using mysql once again you can:
```sql
SELECT `id`, `title`, `url` FROM lychee_photos WHERE `album` =  '<numbers>' ORDER BY `id` DESC LIMIT 10;
```
This should select the last 10 pictures uploaded to that album. The column `title` will allow you to check the name of the picture and `url` will allow you to check the picture: `<baseurl>/uploads/big/<url>` You will be able to see if it is a broken one.
In that case, you can go via ssh in the `upload/big/` folder and delete it, idem in the `upload/thumb`,  `upload/small` and `upload/medium` folders.
Once that is done, you can remove the picture from the database by using the `id` info you got above:
```sql
DELETE FROM lychee_photos WHERE `id` = '<id>';
```

I sure hope this will solve your album problem.

**Comment by Espionage724** [comment]
Doing the above (removing the last uploaded image from those folders and from the database) fixes the album (becomes viewable again from a browser).

Trying to upload any image to that album after doing that though breaks it again. I don't see anything added to Lychee's log when doing so.

I haven't tried any other existing album, but I created a new album, and uploading the same new images to it worked fine.

**Comment by ildyria** [comment]
> Trying to upload any image to that album after doing that though breaks it again. I don't see anything added to Lychee's log when doing so.
> 
> I haven't tried any other existing album, but I created a new album, and uploading the same new images to it worked fine.

That makes no sense. I don't see why this would not work in an existing album but would be fine in a new one. I am sorry but I can't really help you on that one.

If this image work in a new album, can you move it to the previous album?

**Comment by Espionage724** [comment]
> If this image work in a new album, can you move it to the previous album?

No; trying to use the Move option on the website doesn't do anything with the image (image doesn't move to an existing album or Unsorted; if I create a new album from that option, the new album gets created, but the image doesn't get moved and the new album is empty). Lychee's log doesn't show anything with this as well.

**Comment by Espionage724** [comment]
If it helps at all, this is the exact configuration I have for Lychee (along with nginx and other components): https://wiki.realmofespionage.xyz/servers:nginx:lychee

**Comment by d7415** [comment]
I can't debug right now, but it may be worth checking your php log, or recent the browser console. Sometimes they pick things up that aren't in Lychee's own log.

**Comment by Espionage724** [comment]
I believe I solved one issue, but  not entirely sure why this fixed it. Looked at the browser console and saw a "upstream sent too big header" error; looked into it, got two additional nginx lines to add for fastcgi, and now I'm able to upload the picture to the problematic album.:

```
fastcgi_buffers 16 16k; 
fastcgi_buffer_size 32k;
```

There's a few issues i'm still experiencing though:

- Trying to move a picture to another album; the browser console shows a `TypeError: callback is not a function` error either at line 1740 (any album except Unsorted) or 1749 (Unsorted folder) in `main.js`, and nothing actually happens (photo isn't moved)

- Various Undefined index errors:

```
2018/12/03 00:26:19 [error] 5627#5627: *563 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: description in /var/www/media/php/Modules/Photo.php on line 800
PHP message: PHP Notice:  Undefined index: license in /var/www/media/php/Modules/Photo.php on line 801
PHP message: PHP Notice:  Undefined index: shutter in /var/www/media/php/Modules/Photo.php on line 809
PHP message: PHP Notice:  Undefined index: make in /var/www/media/php/Modules/Photo.php on line 810
PHP message: PHP Notice:  Undefined index: model in /var/www/media/php/Modules/Photo.php on line 811
PHP message: PHP Notice:  Undefined index: iso in /var/www/media/php/Modules/Photo.php on line 812
PHP message: PHP Notice:  Undefined index: aperture in /var/www/media/php/Modules/Photo.php on line 813
PHP message: PHP Notice:  Undefined index: focal in /var/www/media/php/Modules/Photo.php on line 814
PHP message: PHP Notice:  Undefined index: description in /var/www/media/php/Modules/Photo.php on line 800
PHP message: PHP Notice:  Undefined index: license in /var/www/media/php/Modules/Photo.php on line 801
PHP message: PHP Notice:  Undefined index: shutter in /var/www/media/php/Modules/Photo.php on line 809
PHP message: PHP Notice:  Undefined index: make in /var/www/media/php/Modules/Photo.php on line 810
PHP message: PHP Notice:  Undefined index: model in /var/www/media/php/Modules/Photo.php on line 811
PHP message: PHP Notice:  Undefined index: iso in /var/www/media/php/Modules/Photo.php on line 812
PHP message: PHP Notice:  Undefined index: aperture in /var/www/media/php/Modules/Photo.php on line 813
PHP message: PHP Notice:  Undefined index: focal in /var/www/media/php/Modules/Photo.php on line 814" while reading response header from upstream, client: 185.100.84.164, server: media.realmofespionage.xyz, request: "POST /php/index.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/media.sock:", host: "media.realmofespionage.xyz", referrer: "https://media.realmofespionage.xyz/"
```

- Trying to upload a webm (2MB [big-buck-bunny_trailer.webm](http://dl3.webmfiles.org/big-buck-bunny_trailer.webm)) didn't work; I installed `ffmpeg` and used `composer update`:

```
2018-12-02 23:55:54 - error - Lychee\Modules\Photo::add (268) 	- Could not create thumbnail for video
2018-12-03 00:00:00 - error - Lychee\Modules\Photo::add (268) 	- Could not create thumbnail for video
```

For the database errors, would forcing `utf8mb4` or using MariaDB instead of Mysql happen to cause problems? [Here's my config related to that](https://wiki.realmofespionage.xyz/servers:mariadb).

**Comment by ildyria** [comment]
> Various Undefined index errors 

Just fixed.

**Comment by ildyria** [comment]
> Trying to move a picture to another album; the browser console shows a `TypeError: callback is not a function` error either at line 1740 (any album except Unsorted) or 1749 (Unsorted folder) in `main.js`, and nothing actually happens (photo isn't moved)

I will have a look into that.

**Comment by ildyria** [comment]
> - Trying to move a picture to another album; the browser console shows a `TypeError: callback is not a function` error either at line 1740 (any album except Unsorted) or 1749 (Unsorted folder) in `main.js`, and nothing actually happens (photo isn't moved)

Could not reproduce on Debian + Firefox / Chrome.

**Comment by ildyria** [comment]
User fixed his issue, it would a nice information to add in the wiki.
```
fastcgi_buffers 16 16k; 
fastcgi_buffer_size 32k;
```

**Comment by ildyria** [comment]
@bennettscience can you take care of it?

**Comment by bennettscience** [comment]
Looks like @Espionage724 made the change several days ago. I moved his note to the server config section.
