### ISSUE TITLE
Center align play icon in video thumbnail

### ISSUE THREAD

**Issue by bennettscience** [LycheeOrg/Lychee-v3#133]
### Detailed description of the problem
When justified layout is enabled, the play button is not centered correctly in the video thumbnail.

![Play button not centered](https://photos.ohheybrian.com/uploads/big/738b5a873d66dee86cfc3c9864727f49.png)

### Steps to reproduce the issue
Enable justified layout in Lychee settings. Upload a video.

### Output of the diagnostics (Settings => Diagnostics)
System Information
------------------
Lychee Version (json):  3.2.6
DB Version:             update_030206
System:                 Linux
PHP Version:            7
MySQL Version:          50505
Imagick:                1
Imagick Active:         1
Imagick Version:        1687
GD Version:             2.2.4
Plugins:                

### Browser and system
MacOS 10.13.6, Vivaldi Browser 2.1, Safari 12, Chrome 70

**Comment by ildyria** [comment]
@clementlamoureux can you take a look at it ? :)

**Comment by clementlamoureux** [comment]
@ildyria Take a look at https://github.com/LycheeOrg/Lychee/pull/140 :wink:

**Comment by ildyria** [comment]
thanks :+1:

**Comment by SusanneNussbaum** [comment]
What kind of videos does Lychee support? I thought it could only handle photos? 🤔

**Comment by ildyria** [comment]
@SusanneNussbaum 
```php
	public static $validVideoTypes = array(
		"video/mp4",
		"video/ogg",
		"video/webm",
		"video/quicktime"
    );
```
And see [here](https://github.com/LycheeOrg/Lychee/wiki/FAQ#which-file-formats-are-supported)
