### ISSUE TITLE
[Wish] Actual version number displayed in e.g. Settings

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-v3#137]
[Wish] Actual version number displayed in e.g. Settings

**Comment by d7415** [comment]
It's shown on the login and diagnostics pages. Would you like it somewhere else? If so, where?

**Comment by SerenaButler** [comment]
Ok two places I did not expect them even I now remember to saw them more then once there :-P 

Honestly, UX wise I would like to see a full "internal" about page (not gettin' redirected to an external webssite though).

**Comment by d7415** [comment]
> Honestly, UX wise I would like to see a full "internal" about page (not gettin' redirected to an external webssite though).

That crossed my mind as I was replying. I might take a look when I get a chance and try to produce something simple for that. The about page could probably include the update check too.

**Comment by SerenaButler** [comment]
btw, version number on diagnostic page is showing wrong version. Still 3.2.4 but should be 3.2.6. It's fine on Login.

**Comment by d7415** [comment]
> btw, version number on diagnostic page is showing wrong version. Still 3.2.4 but should be 3.2.6. It's fine on Login.

Check your cache. Those two pages get their versions from slightly different places, but both were updated in the same commit.

**Comment by SerenaButler** [comment]
Sure I did before. And to be sure now again. Still 3.2.4 :-)

**Comment by d7415** [comment]
> Sure I did before. And to be sure now again. Still 3.2.4 :-)

Sorry, my mistake. The diagnostics will show which version of the Lychee-Front submodule you have checked out. You can update it to match with `git submodule update`. That should probably also be looked at... :clipboard: *adds to list*
