### ISSUE TITLE
[bug] navigator specific display issue

### ISSUE THREAD

**Issue by lbonnefond** [LycheeOrg/Lychee-v3#138]
### Detailed description of the problem

Hello,

On a fresh install of Lychee I get a strange display with Firefox and Chrome consisting of large black icons on a white background, but a correct behavior with Edge. Any idea ?

![20181204-lychee](https://user-images.githubusercontent.com/24911821/49445190-9b44c100-f7d1-11e8-8936-75cc48f1f0c7.png)

### Steps to reproduce the issue

I followed the basic installation procedure with git and composer on a shared host (Dreamhost). I own another instance of Lychee (3.1.6) that works fine on all browsers.

### Output of the diagnostics (Settings => Diagnostics)

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version (json):  3.2.6
DB Version:             update_030206
System:                 Linux
PHP Version:            7
MySQL Version:          50634
Imagick:                1
Imagick Active:         1
Imagick Version:        1655
GD Version:             bundled (2.1.0 compatible)
Plugins: 

### Browser and system

Firefox 63.0.3 (64bits)
Google Chrome Version 70.0.3538.110 (Build officiel) (64 bits)
Microsoft EdgeHTML 15.15063
Windows 10

**Comment by d7415** [comment]
Are there any errors in your browser console?

**Comment by lbonnefond** [comment]
Yes, quite a bit:

> Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:2
1543942271779	addons.webextension.{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}	WARN	Loading extension '{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}': Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
1543942271784	addons.webextension.{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}	WARN	Loading extension '{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}': Reading manifest: Error processing storage: An unexpected property was found in the WebExtension manifest.
1543942271815	addons.webextension.{7a73dc4b-1b38-40e7-ac56-7d356dd4af34}	WARN	Loading extension '{7a73dc4b-1b38-40e7-ac56-7d356dd4af34}': Reading manifest: Error processing sandbox: An unexpected property was found in the WebExtension manifest.
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xul
Successfully compiled asm.js code (total compilation time 1ms; not stored in cache (too small to benefit)) adblockplus.js
Unkown category for SetEventRecordingEnabled.
In add-on {d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}, attempting to use listener "notifications.onButtonClicked", which is unimplemented. ExtensionParent.jsm:1007:5
Unknown localization message freshtab_app_top_box_import_bookmarks_hdr background.js:47
Unknown localization message freshtab_app_top_box_import_bookmarks_cta background.js:47
Unknown localization message freshtab_app_top_box_import_bookmarks_later background.js:47
Unknown localization message freshtab_app_middle_box_new_cliqz_tab_hdr background.js:47
Unknown localization message freshtab_app_middle_box_new_cliqz_tab_desc background.js:47
Unknown localization message freshtab_app_middle_box_new_cliqz_tab_cta background.js:47
Unknown localization message freshtab_app_middle_box_blue_theme_hdr background.js:47
Unknown localization message freshtab_app_middle_box_blue_theme_desc background.js:47
Unknown localization message freshtab_app_middle_box_blue_theme_cta background.js:47
Unknown localization message freshtab_app_middle_box_french_news_hdr background.js:47
Unknown localization message freshtab_app_middle_box_french_news_desc background.js:47
Unknown localization message freshtab_app_middle_box_french_news_cta background.js:47
Unknown localization message freshtab_app_middle_box_promote_mobile_hdr background.js:47
Unknown localization message freshtab_app_middle_box_promote_mobile_desc background.js:47
Unknown localization message freshtab_app_middle_box_ft_amo_hdr background.js:47
Unknown localization message freshtab_app_middle_box_ft_amo_desc background.js:47
Unknown localization message freshtab_app_middle_box_ft_amo_cta background.js:47
listener not re-registered ExtensionCommon.jsm:2092
Error: listener not re-registered ExtensionCommon.jsm:2092:24
listener not re-registered ExtensionCommon.jsm:2092
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/dist/main.css’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/dist/main.js’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/Lychee-front/images/apple-touch-icon-iphone-plus.png’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/favicon.ico’ to use ‘https’
Type error for parameter tabId (Integer -1 is too small (must be at least 0)) for tabs.get. background.js:148
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/dist/main.css’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/dist/main.js’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/dist/main.css’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/dist/main.js’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/Lychee-front/images/apple-touch-icon-iphone-plus.png’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/favicon.ico’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/dist/main.css’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/dist/main.js’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/Lychee-front/images/apple-touch-icon-iphone-plus.png’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/favicon.ico’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/Lychee-front/images/apple-touch-icon-iphone-plus.png’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/favicon.ico’ to use ‘https’
Loading failed for the <script> with source “http://photo.inscog.org/dist/main.js”. photo.inscog.org:817:1
[Exception... "Favicon at "http://photo.inscog.org/favicon.ico" failed to load."  nsresult: "0x805a3ff2 (<unknown>)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 147"  data: no]
[Exception... "Favicon at "http://photo.inscog.org/Lychee-front/images/apple-touch-icon-iphone-plus.png" failed to load."  nsresult: "0x805a3ff2 (<unknown>)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 147"  data: no]
[Exception... "Favicon at "http://photo.inscog.org/favicon.ico" failed to load."  nsresult: "0x805a3ff2 (<unknown>)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 147"  data: no]
Unchecked lastError value: Error: Promised response from onMessage listener went out of scope page_performance.js:18
Log warning: The log 'Services.Common.RESTRequest' is configured to use the preference 'services.common.log.logger.rest.request' - you must adjust the level by setting this preference, not by using the level setter Log.jsm:22

**Comment by d7415** [comment]
Ah. Does it work if you disable your ad blocker?

**Comment by lbonnefond** [comment]
No.

> Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:2
Unkown category for SetEventRecordingEnabled.
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xul
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/dist/main.css’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/dist/main.js’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/Lychee-front/images/apple-touch-icon-iphone-plus.png’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/favicon.ico’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/dist/main.css’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/dist/main.js’ to use ‘https’
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/Lychee-front/images/apple-touch-icon-iphone-plus.png’ to use ‘https’
Loading failed for the <script> with source “http://photo.inscog.org/dist/main.js”. photo.inscog.org:817:1
Content Security Policy: Upgrading insecure request ‘http://photo.inscog.org/favicon.ico’ to use ‘https’
[Exception... "Favicon at "http://photo.inscog.org/favicon.ico" failed to load."  nsresult: "0x805a3ff2 (<unknown>)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 147"  data: no]
[Exception... "Favicon at "http://photo.inscog.org/Lychee-front/images/apple-touch-icon-iphone-plus.png" failed to load."  nsresult: "0x805a3ff2 (<unknown>)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 147"  data: no]
Log warning: The log 'Services.Common.RESTRequest' is configured to use the preference 'services.common.log.logger.rest.request' - you must adjust the level by setting this preference, not by using the level setter Log.jsm:22

**Comment by d7415** [comment]
Ok. Does https://photo.inscog.org/ give you a security error or do you have an exception already? 

We may need to add a note to disable CSP if you don't have HTTPS set up, or just add it as a (soft) requirement... Can't fix it now, but I'll look at it later in the week if no one beats me to it.

**Comment by d7415** [comment]
Nevermind. The HTTPS site isn't the gallery. That's the problem here.

If you disable CSP or set up HTTPS it should work.

**Comment by lbonnefond** [comment]
I'm trying to set up https. 
I'll let you know when it's active. 
Thank you

**Comment by lbonnefond** [comment]
Ok, https is on, but now I get a regular layout. Only now I get an error: `Server error or API not found` ...

I think I will restart from a clean install.

**Comment by d7415** [comment]
That might help. Otherwise browser console, php log and Lychee log are the likely candidates for clues. Probably roughly in that order.

**Comment by lbonnefond** [comment]
Ok, a clean install after setting up https did the trick.
Thank you.

**Comment by d7415** [comment]
Great! I'll leave this open for now until I've mentioned / checked HTTPS in the docs. Hopefully tomorrow.
