### ISSUE TITLE
[Wish] Custom Size Image Creation

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-v3#141]
I for myself do a lot of linking to forums with my images, as the medium size (1920) is too big for that case, I always change the values in photo.php too 1280 x 720. The possiblity to set custom size for photo creation would be nice though. I even would make the correlation sizes changeable in the setting. For everybode "small", "Medium" or "Large" is something different.

**Comment by ildyria** [comment]
Fixed with last commit
