### ISSUE TITLE
Download (git clone) instruction fails

### ISSUE THREAD

**Issue by tomscii** [LycheeOrg/Lychee-v3#143]
Hi,

Step 2 (Download) at the Install guide (https://github.com/LycheeOrg/Lychee/wiki/Installation) currently fails with a submodule ref error:

$ git clone --recurse-submodules https://github.com/LycheeOrg/Lychee.git
Cloning into 'Lychee'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 11199 (delta 30), reused 37 (delta 21), pack-reused 11144
Receiving objects: 100% (11199/11199), 3.42 MiB | 2.12 MiB/s, done.
Resolving deltas: 100% (7869/7869), done.
Submodule 'src' (https://github.com/LycheeOrg/Lychee-front.git) registered for path 'Lychee-front'
Submodule 'docs' (https://github.com/LycheeOrg/Lychee.wiki.git) registered for path 'docs'
Cloning into '/<...>/Lychee/Lychee-front'...
remote: Enumerating objects: 72, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 760 (delta 40), reused 46 (delta 24), pack-reused 688
Receiving objects: 100% (760/760), 283.50 KiB | 0 bytes/s, done.
Resolving deltas: 100% (549/549), done.
Cloning into '/<...>/Lychee/docs'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 101 (delta 0), reused 0 (delta 0), pack-reused 98
Receiving objects: 100% (101/101), 27.88 KiB | 0 bytes/s, done.
Resolving deltas: 100% (55/55), done.
error: no such remote ref 487cd5c34f582c75902334a5abebc0d72d620c67
Fetched in submodule path 'Lychee-front', but it did not contain 487cd5c34f582c75902334a5abebc0d72d620c67. Direct fetching of that commit failed.

This is with git 2.11.0 on Debian 9.

Thanks,
Tom

**Comment by d7415** [comment]
Very odd... Maybe delete the folder (if it has no config/photos in yet) and try again? I get:

```
$ git clone --recurse-submodules https://github.com/LycheeOrg/Lychee.git
Cloning into 'Lychee'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 11199 (delta 30), reused 37 (delta 21), pack-reused 11144
Receiving objects: 100% (11199/11199), 3.42 MiB | 3.72 MiB/s, done.
Resolving deltas: 100% (7869/7869), done.
Submodule 'src' (https://github.com/LycheeOrg/Lychee-front.git) registered for path 'Lychee-front'
Submodule 'docs' (https://github.com/LycheeOrg/Lychee.wiki.git) registered for path 'docs'
Cloning into '/tmp/Lychee/Lychee-front'...
remote: Enumerating objects: 72, done.        
remote: Counting objects: 100% (72/72), done.        
remote: Compressing objects: 100% (48/48), done.        
remote: Total 760 (delta 40), reused 46 (delta 24), pack-reused 688        
Receiving objects: 100% (760/760), 283.50 KiB | 994.00 KiB/s, done.
Resolving deltas: 100% (549/549), done.
Cloning into '/tmp/Lychee/docs'...
remote: Enumerating objects: 3, done.        
remote: Counting objects: 100% (3/3), done.        
remote: Compressing objects: 100% (3/3), done.        
remote: Total 101 (delta 0), reused 0 (delta 0), pack-reused 98        
Receiving objects: 100% (101/101), 27.88 KiB | 648.00 KiB/s, done.
Resolving deltas: 100% (55/55), done.
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/LycheeOrg/Lychee-front
 * branch            487cd5c34f582c75902334a5abebc0d72d620c67 -> FETCH_HEAD
Submodule path 'Lychee-front': checked out '487cd5c34f582c75902334a5abebc0d72d620c67'
Submodule path 'docs': checked out '7416764d0ec1668c6ca8ff58d11e5f91d311b105'
```

And the commit is definitely present: LycheeOrg/Lychee-front@487cd5c34f582c75902334a5abebc0d72d620c67

**Comment by tomscii** [comment]
I tried it again, with fresh download location, and it persistently failed with the same error.
I even reproduced it with another machine running the same version of git (the one in Debian stretch), git 2.11.0, that is about 2 years old.

Finally, I was successful on a third machine that had git 2.16.2 installed.

**Comment by d7415** [comment]
Thanks for this. The problem seems to be that the commit was detached (not in a branch). I guess more recent git must explicitly request the commit from the server if it's not in the initial clone. It should be fixed now.

**Comment by tomscii** [comment]
I can confirm that it works now. Thanks for the quick fix!
