### ISSUE TITLE
Photos uploaded using lycheeupload not opening when downloaded via Lychee interface button

### ISSUE THREAD

**Issue by corrilan** [LycheeOrg/Lychee-v3#145]
### Detailed description of the problem
Images uploaded using Lychee "Upload Photo" are working fine, this issue is related specifically to images uploaded using lycheeupload, the SSH upload tool.

Right clicking an image and using the web browsers built in "Save Image As..." option is saving the files and allowing me to open them.

But, when I try to use the Lychee interface button labelled "Download", the file downloads but does not open, instead showing error message:

"Error interpreting JPEG image file (Not a JPEG file: starts with 0x22 0x45)"

I have tried on multiple computers running both Ubuntu Linux and Microsoft Windows 7.

### Steps to reproduce the issue
Upload an image using lycheeupload tool.
Use the Lychee Download button to save and attempt to open the saved image.

### Output of the diagnostics (Settings => Diagnostics)
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version (json):  3.2.6
DB Version:             update_030206
System:                 Linux
PHP Version:            7.2
MySQL Version:          50724
Imagick:                -
Imagick Active:         0
Imagick Version:        -
GD Version:             2.2.5
Plugins:                

### Browser and system
Mozilla Firefox and Google Chrome on Ubuntu Linux.
Internet Explorer and Google Chrome on Microsoft Windows 7.

**Comment by d7415** [comment]
Does the "Full Photo" link work?

I'm not especially familiar with lycheeupload (Thanks for figuring that part out!), although I do use lycheesync. It seems lycheeupload hasn't been updated in a while, so it's possible that something's changed and is breaking things, but we'd have to figure out what (and whether it's something to fix at Lychee's end or at the lycheeupload end)

**Comment by corrilan** [comment]
Hello

"Full Photo" link is not working, shows error of:

Not Found
The requested URL /uploads/big/7acc54d497bbf9eb110718ca20204c49.jpg was not found on this server.

I checked that path and can confirm that the file does not exist!  Seems files uploaded via lycheeupload are not having their big file stored.

Jason

**Comment by d7415** [comment]
That could do it. If you open the downloaded photos in a text editor, is it a 404 page? (Or text of some sort)

**Comment by corrilan** [comment]
When opening a downloaded 'broken' .jpg in text editor it contains just the text:

'Error: Function not found! Please check the spelling of the called function."

**Comment by ildyria** [comment]
This looks really like this line:
```php
Response::error('Function not found! Please check the spelling of the called function.');
```
from: https://github.com/LycheeOrg/Lychee/blob/master/php/Access/Access.php#L11

**Comment by d7415** [comment]
Yeah, and it's not in the lycheeupload source. If the "Full Photo" link is giving a 404 that implies that Lychee might be returning that in place of the big photo in this edge case.

For @corrilan I'd be most concerned that big is the important place for the files to be (unless you're using the lycheeupload option to shrink "big" and upload to "import". If you are you may want to import using Lychee's "import from server" option.

**Comment by d7415** [comment]
> If the "Full Photo" link is giving a 404 that implies that Lychee might be returning that in place of the big photo in this edge case.

Looking through the code, I don't think I can see how that would happen, but I haven't spun up a test instance to look...

**Comment by corrilan** [comment]
I don't think I can use the built in "import from server" option due to my use case which is a Linux based photo booth which snaps some photos and the lycheeupload script automatically copies them to the remote Lychee server.

The "import from server" option will require me to manually intervene to get the photos uploaded if I am not mistaken.

**Comment by d7415** [comment]
It was just a thought if you were using the `--originals` option in lycheeupload. That option (according to its [README](https://github.com/r0x0r/lycheeupload#usage)) puts the original photos into the import/ folder, which is where Lychee gets photos from for its Import from Server function.

It would require manual intervention to make them appear though.

**Comment by d7415** [comment]
If the problem is specific to lycheeupload, it may be worth looking at lycheesync. You'd have to upload yourself and trigger sync, but it may be of interest (and I have it working). You could either rsync the files then trigger via ssh, or maybe run lycheesync with cron.

**Comment by corrilan** [comment]
Just for completeness here is my lycheeupload line on the photo booth system, not using --originals:

python /home/pi/photo-video-booth-code/lycheeupload/lycheeupload.py -d /home/pi/photo-video-booth-code/photos/ --port 2222 --verbose username@myserver:/var/www/mylycheesite/Lychee/ && mv /home/pi/photo-video-booth-code/photos/* /home/pi/photo-video-booth-code/photo-archive/

I will take a look at lycheesync too.

**Comment by d7415** [comment]
I may be wrong (It's late and I haven't tested) but at a glances it looks like it won't upload big unless you have a big_size set (with --big) (https://github.com/r0x0r/lycheeupload/blob/master/upload.py#L63-L67).

I'd be tempted to try adding `self.ssh.put(photo.srcfullpath, photo.destfullpath)` somewhere aroung those lines (maybe line 68) and see what happens.

That definitely shouldn't work because it should have been picked up by now. But maybe no-one used it (with no options, anyway) to find out?

**Comment by corrilan** [comment]
You are right.  Added self.ssh.put(photo.srcfullpath, photo.destfullpath) as you suggested.
Now the uploaded file is also copied to the big directory resulting in the "Full Photo", "Download" and "Download Album" buttons working as required.

Thank you very much!  My fiance will be pleased to know that my time making a photo booth for our big day has not been wasted.

Maybe no one noticed as I did not initially.  I tested the download and full photo links after using the built in Lychee method to upload photos.  It is only my fiance who tried it out on photos uploaded via lycheeupload who noticed the issue.

**Comment by d7415** [comment]
Glad it worked :) If I remember I might put an issue/PR on lycheeupload, so at least people can see there's an issue there.

I'm going to try to find time to have a quick test and see whether I can replicate the "Error: Function not found! Please check the spelling of the called function." error in images. Failing that I'll close this issue when I'm done.

**Comment by d7415** [comment]
The more I look, the less I understand how it works...

But a missing big image in Lychee definitely causes that error, which it shouldn't.

**Comment by d7415** [comment]
Added some mitigation (Error messages, and block downloading a dud jpg) in 92339a0 and dc8fc88.

It looks like any more would require changing frontend/backend interactions, which I don't think is worth it for an edge case like this.
