### ISSUE TITLE
Missing "small" folder in 3.2.6 release

### ISSUE THREAD

**Issue by expiredemulsion** [LycheeOrg/Lychee-v3#146]
### Detailed description of the problem
The 3.2.6 release download
https://github.com/LycheeOrg/Lychee/releases/download/v3.2.6/Lychee-v3.2.6.zip
is missing a folder in the uploads dir compared to the source code.
https://github.com/LycheeOrg/Lychee/archive/v3.2.6.zip

The release contains:
big
import
medium
thumb

while the source code contains: 
big
import
medium
small
thumb

### Steps to reproduce the issue
1. Download release: https://github.com/LycheeOrg/Lychee/archive/v3.2.6.zip
Download source code: https://github.com/LycheeOrg/Lychee/archive/v3.2.6.zip

2. Compare the "uploads" folders and you will find that the the folder "small" is missing in the release package.

### Output of the diagnostics (Settings => Diagnostics)
Error: 'uploads/small' is missing or has insufficient read/write privileges

### Browser and system

Lychee Version (json):  3.2.6
DB Version:             update_030206
System:                 Darwin
PHP Version:            7.1
MySQL Version:          50720
Imagick:                -
Imagick Active:         0
Imagick Version:        -
GD Version:             bundled (2.1.0 compatible)
Plugins:

**Comment by ildyria** [comment]
This will not be solved in the current version, but it will be solved in the next iteration.
