### ISSUE TITLE
Uploaded photos cannot be opened: Failed to load resource (404 NOT FOUND)

### ISSUE THREAD

**Issue by chrobs** [LycheeOrg/Lychee-v3#147]
### Detailed description of the problem
Thumbs of uploaded photos are shown correctly while lychee shows a broken image icon when clicking the photo.

Error message in browser JS console:`Failed to load resource: the server responded with a status of 404 (Not Found)`

### Steps to reproduce the issue

1. Upload new Photo to an Album
1.1 -> Thumbnail of new photo shows correctly
1. Click on Photo thumbnail
1.1 -> Broken image icon is shown and error `failed to load resource` is printed on JS console
1. Click via Menu on 'see full picture'
1.1 -> Picture is shown correctly in originial size

observations:
* No error on the Lychee log
* No error on the Apache log
* Image hash is found 3 times under uploads/:
```
$ ls -alt uploads/*/*ad0a30ad62afb87449b1490d2522139c*
-rw-r--r-- 1 www-data www-data   69545 Dec  9 16:17 uploads/thumb/ad0a30ad62afb87449b1490d2522139c@2x.jpeg
-rw-r--r-- 1 www-data www-data   21713 Dec  9 16:17 uploads/thumb/ad0a30ad62afb87449b1490d2522139c.jpeg
-rw-r--r-- 1 www-data www-data 9221263 Jun  2  2018 uploads/big/ad0a30ad62afb87449b1490d2522139c.JPG
```
### Output of the diagnostics (Settings => Diagnostics)
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version (json):  package.json not found. Please do: git submodule init ; git submodule update
DB Version:             update_030206
System:                 Linux
PHP Version:            7
MySQL Version:          50505
Imagick:                1
Imagick Active:         1
Imagick Version:        1687
GD Version:             2.2.4
Plugins:                

### Browser and system

**Comment by chrobs** [comment]
Followed the instructions in the diagnostic output:

```
apt install php-imagick
git submodule init
git submodule update
```

And no it seems to be working again for newly uploaded pictures:
```
$ ls -alt uploads/*/*bdb632ee662b2a0d10276583b4f7fcec*
-rw-r--r-- 1 www-data www-data   30203 Dec  9 21:43 uploads/small/bdb632ee662b2a0d10276583b4f7fcec.JPG
**-rw-r--r-- 1 www-data www-data  228044 Dec  9 21:43 uploads/medium/bdb632ee662b2a0d10276583b4f7fcec.JPG**
-rw-r--r-- 1 www-data www-data   43910 Dec  9 21:43 uploads/thumb/bdb632ee662b2a0d10276583b4f7fcec@2x.jpeg
-rw-r--r-- 1 www-data www-data   14065 Dec  9 21:43 uploads/thumb/bdb632ee662b2a0d10276583b4f7fcec.jpeg
-rw-r--r-- 1 www-data www-data 2724639 Jul 16  2016 uploads/big/bdb632ee662b2a0d10276583b4f7fcec.JPG
```

I came from a pure git repo update and I didn't noticed the missing submodule update.

That means that there are now ~800 pictures across my gallery which does not have respective medium size pictures. Is there any chance to instruct Lychee to re-create the respective medium sized images if they are missing?

Thanks for any help :)

cheers,
chrobs

**Comment by d7415** [comment]
You can generate medium images using https://github.com/Bramas/lychee-create-medium. For small images see the instructions in #134 :)

I've used both (heavily) today, so they should both work!

**Comment by d7415** [comment]
I'm a little curious about the failure mode. I don't think Lychee-front being out of date should affect any of this, and missing medium photos should only be an issue if the database is wrong (there's a field that states whether an image has small/medium versions available).

That said, if it's working now then we can probably ignore it until/unless it appears again.

**Comment by chrobs** [comment]
Hey @d7415,
thanks so much for your very quick reply and for your 'create medium' script - works like a charm :)

Nevertheless, I agree with you, that this failure state shouldn't be possible.

Around the first occurrence of the missing medium sized image problem, I found the following lines in my apache error logs:
```
[:error] [pid 326] [client ::1:39030] PHP Notice:  Undefined index: max_takestamp in [...]/php/Modules/Album.php on line 85, referer: [...]
[:error] [pid 326] [client ::1:39030] PHP Notice:  Undefined index: min_takestamp in [...]/php/Modules/Album.php on line 78, referer: [...]
[:error] [pid 326] [client ::1:39030] PHP Notice:  Undefined index: min_takestamp in [...]/php/Modules/Album.php on line 79, referer: [...]
[:error] [pid 326] [client ::1:39030] PHP Notice:  Undefined index: max_takestamp in [...]/php/Modules/Album.php on line 84, referer: [...]
[:error] [pid 326] [client ::1:39030] PHP Notice:  Undefined index: max_takestamp in [...]/php/Modules/Album.php on line 85, referer: [...]
```

This may not be related to this issue (especially because I could not reliably reproduce it)  but I'm not sure...sounds strange

**Comment by chrobs** [comment]
Hey again @d7415,
I used your script and it worked like expected: Medium sized images were created for those images which had 'medium = 0' in the lychee_photos table.

But that didn't solved my initial problem for those images uploaded during the period of the Lychee fail state as described above.

The reason is very simple: Those images are marked with 'medium=1' in the database, but there is no medium sized image on the filesystem:
```
MariaDB [lychee]> select id, width, height, url, medium, type from lychee_photos where url like '779b3620800b0fde0f34649706823259%';
+----------------+-------+--------+--------------------------------------+--------+------------+
| id             | width | height | url                                  | medium | type       |
+----------------+-------+--------+--------------------------------------+--------+------------+
| 15443682220903 |  5056 |   3792 | 779b3620800b0fde0f34649706823259.JPG |      1 | image/jpeg |
+----------------+-------+--------+--------------------------------------+--------+------------+

$ find uploads/ -iname "*779b3620800b0fde0f34649706823259*"
uploads/big/779b3620800b0fde0f34649706823259.JPG
uploads/thumb/779b3620800b0fde0f34649706823259.jpeg
uploads/thumb/779b3620800b0fde0f34649706823259@2x.jpeg
```

I suspect that during the upload process, the creation of the medium sized image failed silently such that the database has the 'medium=1' value but there is no medium sized image on the filesystem.

Maybe such fail cases are currently not sufficiently handled in Lychee? Would be an improvement to further strengthen Lychee and avoid this kind of problems.

At least I hope that my problem report may help someone in the future =)

Thanks for your efforts!

cheers,
chrobs

**Comment by d7415** [comment]
Ah, that's annoying... Unfortunately, as I said above, it looks like handling that sort of error would take a lot of extra work rewriting for what is really an edge case caused by 3rd-party tools. It would be nice to fail gracefully, but I'm not sure it's worth the effort just to have a "medium image missing!" message.

If you want a quick and dirty fix, you could delete all the images in the medium/ folder, `UDPATE lychee_photos SET medium=0;` in the DB and then run that script again. It's nasty, but it should result in everything being as expected.... (unless there's another problem in lycheeupload that we've yet to discover!)

**Comment by chrobs** [comment]
Hey @d7415 , thanks for your reply and your quick fix!

I hacked a more efficient (not less nasty!) way, detecting only the false entries in the database:

First, get a list of all photo hashes which have medium=1 but the medium sized file on the filesystem is missing:
```
for hash in `mysql -D lychee -e "select url from lychee_photos where url not like '%.mp4' and medium=1" | /bin/grep -o -P '[a-f0-9]+'`; do if [ ! -f uploads/medium/$hash* ]; then; echo "$hash"; fi; done 2>/dev/null
```

Better check the list on a random basis.

If you're kind of sure, do the following to update 'medium' to '0' for those pictures:
```
for hash in `cat /tmp/list.txt`; do mysql -D lychee -e "update lychee_photos set medium=0 where url like '$hash%'"; done
```

Last, run @d7415 script to automatically create the missing medium sized files.

Et voilà, everything back to normal :)

**Comment by d7415** [comment]
Good job :) I was just being lazy.

I feel I should mention that the create-medium script is by @Bramas :)
