### ISSUE TITLE
lychee uploading pics into uploads/thumb folder only

### ISSUE THREAD

**Issue by gstlouisgit** [LycheeOrg/Lychee-v3#148]
anything but the uploads/thumb folder has the images.  I can see the images in lychee, looking at the network tab in chrome they are being loaded from uploads/thumb, but once you click on one of them the images are not being displayed.

all these folders have 777 permissions
log files just explain 'Lychee\Modules\Photo::add (63) - An upload-folder is missing or not readable and writable'

I only installed this once, the only error I ever got was because the uploads folder did not have writes access, which I have resolved

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version (json):  3.2.6
DB Version:             update_030206
System:                 Linux
PHP Version:            7
MySQL Version:          50560
Imagick:                -
Imagick Active:         0
Imagick Version:        -
GD Version:             bundled (2.1.0 compatible)

macbook pro
chrome Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by corrilan** [comment]
Hello
Try a different browser and clear your browser cache.
I say because I had an issue last week where the thumbnails showed on the album 'cover' but when I clicked the thumbnail to enter the album it appeared empty.
I found another browser worked fine so I cleared cache on original browser and all was well.
Jason

**Comment by gstlouisgit** [comment]
thanks for your comments.

I had already tried a different browser firefox.  This is still the same issue.  Literally on the server, in the web folder, under uplaods/*, thumb folder got filled in, all the other ones accept big/ are empty of images.  Big folder looks to have only a couple of images.  I'm not even sure if those images correspond with the thmub/'images'.  I just tried diff and says none of them match each other.  so honestly I'm not sure at all what's going on.  I will fiddle with it some more when I can.

**Comment by d7415** [comment]
Ok, I've just read through again and checked the specific wording of the error messages. That particular error isn't to do with the medium/small images (at least on the most recent Lychee), but specifically means Lychee can't read or write uploads/ uploads/big/ or uploads/thumb/. If big/ and thumb/ are world-writeable, maybe check the parent uploads folder?

**Comment by gstlouisgit** [comment]
thanks for your comments
that's the first thing I did.  Everything has been chown to apache:apache and chmod to 777 recursively from uploads.  So it should not be a problem unless there is something I'm not seeing.

btw: how do we clear that log from lychee?

**Comment by gstlouisgit** [comment]
Here are some error log from the server for this env

[Fri Dec 14 16:39:45.893437 2018] [autoindex:error] [pid 3958] [client 192.168.10.14:60751] AH01276: Cannot serve directory /home/lychee/public_html/uploads/: No matching DirectoryIndex (index.html,index.htm,index.php,index.php4,index.php5) found, and server-generated directory index forbidden by Options directive
[Fri Dec 14 17:02:15.090209 2018] [fcgid:warn] [pid 4279] [client 192.168.10.14:62703] mod_fcgid: stderr: PHP Warning:  is_dir(): Unable to find the wrapper &quot;nfs&quot; - did you forget to enable it when you configured PHP? in /home/lychee/public_html/php/Modules/Import.php on line 105, referer: http://lychee/
[Fri Dec 14 17:02:15.090266 2018] [fcgid:warn] [pid 4279] [client 192.168.10.14:62703] mod_fcgid: stderr: PHP Warning:  is_dir(): Unable to find the wrapper &quot;nfs&quot; - did you forget to enable it when you configured PHP? in /home/lychee/public_html/php/Modules/Import.php on line 105, referer: http://lychee/
[Fri Dec 14 17:02:57.627222 2018] [fcgid:warn] [pid 28737] [client 192.168.10.14:62707] mod_fcgid: stderr: PHP Warning:  is_dir(): Unable to find the wrapper &quot;nfs&quot; - did you forget to enable it when you configured PHP? in /home/lychee/public_html/php/Modules/Import.php on line 105, referer: http://lychee/
[Fri Dec 14 17:02:57.627263 2018] [fcgid:warn] [pid 28737] [client 192.168.10.14:62707] mod_fcgid: stderr: PHP Warning:  is_dir(): Unable to find the wrapper &quot;nfs&quot; - did you forget to enable it when you configured PHP? in /home/lychee/public_html/php/Modules/Import.php on line 105, referer: http://lychee/
[Fri Dec 14 17:26:02.945824 2018] [fcgid:warn] [pid 3382] [client 192.168.10.14:63109] mod_fcgid: read data timeout in 40 seconds, referer: http://lychee/
[Fri Dec 14 17:26:02.957907 2018] [core:error] [pid 3382] [client 192.168.10.14:63109] End of script output before headers: index.php, referer: http://lychee/
[Fri Dec 14 17:43:38.097815 2018] [fcgid:warn] [pid 1280] (104)Connection reset by peer: [client 192.168.10.14:63852] mod_fcgid: ap_pass_brigade failed in handle_request_ipc function, referer: http://lychee/
[Fri Dec 14 17:45:17.882633 2018] [fcgid:warn] [pid 1281] [client 192.168.10.14:63883] mod_fcgid: read data timeout in 40 seconds, referer: http://lychee/
[Fri Dec 14 17:45:17.907188 2018] [core:error] [pid 1281] [client 192.168.10.14:63883] End of script output before headers: index.php, referer: http://lychee/

**Comment by johnnypark** [comment]
I had the same issue and dived into it and finally found it: when ImageMagick is not installed, the medium / small images are not created with gd either.
I created a PR addressing this: https://github.com/LycheeOrg/Lychee/pull/158

**Comment by gstlouisgit** [comment]
for the record, this did not fix my issue and ImageMagick is installed.

centos7
Package gd-2.0.35-26.el7.x86_64 already installed and latest version
Package ImageMagick-6.7.8.9-15.el7_2.x86_64 already installed and latest version

**Comment by ildyria** [comment]
But are php-imagick and php-gd installed ? 

⁣--

Kind regards

Benoît Viguier

sent from my phone.​

Le 7 janv. 2019 à 13:57, à 13:57, gstlouis <notifications@github.com> a écrit:

**Comment by gstlouisgit** [comment]
yup, doubled check to make sure

[root@stage ~]# yum install php-imagick
Package php-pecl-imagick-3.4.3-9.el7.remi.7.1.x86_64 already installed and latest version
Nothing to do
[root@stage ~]# yum install php-gd
Package php-gd-7.1.25-2.el7.remi.x86_64 already installed and latest version

**Comment by d7415** [comment]
Unless your Diagnostics output has changed from the initial issue, Lychee isn't seeing imagick.
