### ISSUE TITLE
"play-icon.png" should be in "lychee-front/images" not root

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-v3#150]
"play-icon.png" should be in "lychee-front/images" not root.

**Comment by ildyria** [comment]
While this is correct semantically, the problem with moving it is that users don't necessarily do `git submodule update` after a `git pull` to update their server.

While the submodule update is not usually required, making such change would break it the compatibility with most users. :(

**Comment by d7415** [comment]
I suppose we could add a copy or symlink in a soon version, then delete it in a later version with a "may sure you "git submodule update" warning in the release notes?

In theory the release notes should be sufficient, but it's hard to be sure whether people read them.

**Comment by ildyria** [comment]
There is a reason why there a is a protocol named RTFM. ;)

**Comment by LudovicRousseau** [comment]
I think "normal" users would install or upgrade Lychee using the provided `.zip` file from https://github.com/LycheeOrg/Lychee/releases

"Advanced" users can use `git update` but I expect they know what they do.
I added a "Update the source code" section in https://github.com/LycheeOrg/Lychee/wiki/Build#update-the-source-code just in case.

**Comment by d7415** [comment]
@LudovicRousseau If they are already in Lychee-front and building from there there shouldn't be an issue :) It's the in-between users that are likely to cause problems. But you make a good point. I propose we make the change with a new release though so that there's a little more warning.
