### ISSUE TITLE
"Display EXIF data overlay" can toggled with click on image

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-v3#151]
### Detailed description of the problem

"Display EXIF data overlay" can toggled with click on image. 

Not the best UX imo. At least if this is intended behaviour then the switch in settings is not needed.

### Steps to reproduce the issue
* Settings // Turn on "Display EXIF data overlay"
* get OK-Message
* leave Settings
* Go to Album
* Go to Image within Album
* Klick on Image, "Display EXIF data overlay" turned off
* Klick on Image again "Display EXIF data overlay" turned on

* check in Settings, "Display EXIF data overlay" gets toggled there

### Browser and system
Chrome latest/Win 10 1803

**Comment by ildyria** [comment]
The switch in settings is intended to be the default when you arrive on a picture. It reflects the system settings.

While toggling on a picture will just affect the setting on your current session.

But we are open to any proposition of improvement of it. :+1:

**Comment by SerenaButler** [comment]
I would name the setting "Display EXIF data overlay by default" and would make this setting independent of the click on an image. A "System Settting" should no be visible toogeable by a klick. Just my 2 cent :-) BTW it's damn great that the development of Lychee is goin' on :-)

**Comment by d7415** [comment]
Making it clearer that it's a default probably makes sense, but I disagree that if a user decides that the interface is in the way (or that they want it on) for one session they should have to go to settings. That feels like bad UX to me.

**Comment by ildyria** [comment]
Nah I think what @SerenaButler meant is that this should be two separate values:
- the one is settings is the one that reflect the server.
- the one that you change when you click is set when you arrive (default) but then can be modified.

**Comment by SerenaButler** [comment]
Exactly what @ildyria said :-) Thanks guys!

**Comment by SerenaButler** [comment]
And btw, this only happens with a logged in user. A non logged in user can't (that is good .. :-)) change the "server" setting with an image click.

**Comment by ildyria** [comment]
As matter of fact, to change the server settings you do need to to go into settings. It is just that the current local setting is displayed on the slider (poor UX I know).

**Comment by d7415** [comment]
So...

- [x] Make it clearer it's a "default" setting in options (maybe)

- [x] Update the settings page to load the global config, or store the global config separately to the local setting in Lychee-front so that it's always available.

?

**Comment by ildyria** [comment]
I would say both, but I am not really in favor of yet another call to the server before loading the settings.

**Comment by d7415** [comment]
Then (This may be ridiculous, I haven't read up on it yet) perhaps we can store it twice when we first load - once as the one that changes on click (`lychee.image_overlay`) and once as e.g. `lychee.image_overlay_default`?

**Comment by ildyria** [comment]
That sound the simplest :)

**Comment by d7415** [comment]
Fixed in master.
