### ISSUE TITLE
Setting // Image Size Definition // Small, Medium, large // With Default values

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-v3#152]
I allready had this custom size wish #141 but maybe it is better to have all sizes freely definable (within a certain, logical range // or via fixed values presented by a dropdown). Every user have different needs for his gallery and it would be much easier to let him decide (or not and then the default values) which sizes he needs.

**Comment by ildyria** [comment]
Large is always without resize.

**Comment by SerenaButler** [comment]
Then I would suggest renaming it to "Original". :-)

**Comment by d7415** [comment]
> Then I would suggest renaming it to "Original". :-)

I see no significant advantage of this. Especially as the word "big" is only used to refer to the folder and isn't presented to the user in any other way.

No great objections either in principle, but it would risk breaking 3rd-party plugins/tools (which we admittedly don't guarantee stability for) for no real benefit.

**Comment by SerenaButler** [comment]
Large is a descriptive, evaluative term, "original" on the other hand is neutral, value-independent. Large can be something completely different for you than for me. Original is always what was uploaded initiating and not "manipulated/changed" by Lychee.

And so seen I consider a renaming already not quite unimportant.

**Comment by d7415** [comment]
> Large is a descriptive, evaluative term

If we're being pedantic, "Large" is not used in Lychee.

My main concern remains introducing a breaking change for a minor benefit.

**Comment by thunderbird-93** [comment]
I support @SerenaButler request. People who choose to selfhost, already went extra mile to get what they want. Extra flexibility would help to tailor lychee to specific person needs and therefore appear to borader audience.

On a separat note, I've recently upgraded from 3.1 and found that big versions only accessible via "Full Photo" menu. My UHD monitor get fed medium (i.e. 1080px tall) versions by default and this looks plain ugly... Thumbnail got blurry as well. Sigh...

**Comment by ildyria** [comment]
@thunderbird-93 I intend to implement this when I have time.

As of your UHD monitor. There is a way to enable the big picture if your screen is that big (I am also using a 4K screen but I don't feel that the loss of quality is such troubles on medium pictures).
The problem with this approach is the big picture is sometimes too big (I have Jpeg pictures that are 20 to 50MB...). Serving a big image slows down the website by quite a lot (even with pre-fetching), and if you don't have a high speed internet then the website becomes pretty unusable.

As for the Thumbnail there is the x2 version for retina display if I'm not wrong. However this is not the case for "small" pictures if you are using the justified layout.

**Comment by thunderbird-93** [comment]
@ildyria thank you. my full res jpegs from 40mp+ sony are under 10MB, hence download time is not too bad. would you please let me know where should i look to tweak the code to switch from medum to big? I will just patch my setup then.

btw, I'd like to support the project. i feared it went abandoned and super grateful to you guys picking it up. is there a way to donate?

**Comment by LudovicRousseau** [comment]
There is no way to donate to "Lychee" as a project.
But you can donate to individual developers.

For example you can send me bitcoin https://ludovicrousseau.blogspot.com/2016/11/bitcoins-received-for-this-blog-2-years.html
I am not a really active developer for Lychee. I just do my best to maintain the project alive and help other developers to participate.

**Comment by d7415** [comment]
> would you please let me know where should i look to tweak the code to switch from medum to big? I will just patch my setup then.

We might be able to do something (as per the original issue), but in the meantime: https://github.com/LycheeOrg/Lychee/blob/master/php/Modules/Photo.php#L278-L279 is where medium (and small) are generated. If medium is missing it will mostly use big in its place. For small, if missing it looks like it will try medium, if neither exist it will use the thumbnail.
If you're diving into the code anyway, you can also adjust the size of the medium (and small) photos there or in the function [here](https://github.com/LycheeOrg/Lychee/blob/master/php/Modules/Photo.php#L499).

> btw, I'd like to support the project. i feared it went abandoned and super grateful to you guys picking it up. is there a way to donate?

Not at present. I suppose we could set something up, but I think most of us are keeping it going because we use it :)

**Comment by thunderbird-93** [comment]
@LudovicRousseau just sent you a humble donation.

@d7415 - great! thank you. Lychee is a great project, super easy to host with docker, sleek and has nice uncluttered UI. while more and more people getting off facebook and the likes to re-gain control over their data, i hope number of active users will grow. donation button is the way for those people to say "thank you" and support development.
