### ISSUE TITLE
Syntax Error in Session.php

### ISSUE THREAD

**Issue by d7415** [LycheeOrg/Lychee-v3#153]
[Sun Dec 16 11:11:53.537154 2018] [:error] [pid 4816] [client xxxxxxx] PHP Parse error:  syntax error, unexpected '?' in /var/docs/Lychee/php/Modules/Session.php on line 80, referer: https://xxxxxxx/Lychee/

Appears to be an error in the PHP source.

Line 80 has a double question mark, as does line 91:

Log::notice(Database::get(), __METHOD__, __LINE__, 'User (' . $username . ') has logged in from ' . ($_SERVER['HTTP_X_REAL_IP'] ?? $_SERVER['REMOTE_ADDR']));

_Originally posted by @rabinnh in https://github.com/LycheeOrg/Lychee/issues/49#issuecomment-447655333_

**Comment by d7415** [comment]
Can't fish comments out of an issue, which was my intention here, and can't delete issues. :(

**Comment by ildyria** [comment]
@d7415 actually... From January 1st 2019 and onward, I will consider PHP5 issues not being issues anymore as it (PHP5) will be considered fully depreciated.

It is not our role to provide software for insecure versions of PHP. :)

**Comment by d7415** [comment]
I might set a reminder to update the wiki and revert that commit :grin: :tada:

**Comment by ildyria** [comment]
@d7415 24 hours left ? :'D

**Comment by d7415** [comment]
And done :)
