### ISSUE TITLE
Site broken

### ISSUE THREAD

**Issue by meminens** [LycheeOrg/Lychee-v3#157]
### Detailed description of the problem
Updated from 3.2.7 to 3.2.8 via `git pull` and now the site is broken. None of the button below are clickable.
![image](https://user-images.githubusercontent.com/42714627/50427844-d68d5980-087e-11e9-877e-245e47aabc72.png)
### Steps to reproduce the issue
Login as admin and go to homepage
### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!
```
### Browser and system
Firefox, macOS

**Comment by meminens** [comment]
Apache log

```
[core:crit] [pid 28147] (13)Permission denied: [client xxx] AH00529: /var/www/xxx.com/html/lychee/dist/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/xxx.com/html/lychee/dist/' is executable.
```

I checked the dist folder and I don't see an htaccess file in this directory. See below.

![image](https://user-images.githubusercontent.com/42714627/50428034-7ba93180-0881-11e9-94c9-162b1dac3e62.png)

**Comment by ildyria** [comment]
that is surprising because everything is working here.

this update is creating a `user.css` in the dist folder. dist folder should be writable. I think this might be where the error come from.
Though the script is doing a chmod just before...

I'm creating a new VM just to check what is not working.

**Comment by ildyria** [comment]
this update is creating a `user.css` in the dist folder. dist folder should be writable. I think this might be where the error come from.

**Comment by ildyria** [comment]
I'm creating a new VM just to check what is not working.

**Comment by meminens** [comment]
Thanks for looking! I am out of ideas at this point. `dist` folder should have `chmod` of `775` right?

**Comment by meminens** [comment]
OK I double checked and somehow `dist` folder permissions were incorrect. It was `dr-----rwt`. Not sure what it means or how it ended up getting this permission. But I changed permissions to 775 and now the all is well!

**Comment by ildyria** [comment]
very weird, especially because of this line: https://github.com/LycheeOrg/Lychee/blob/master/php/database/update_030208.php#L51 .

**Comment by meminens** [comment]
Is it possible that I screwed up the update procedure somehow? Like I said in OP, all I did was to `cd` into the Lychee folder on my server and run `git pull` as root. I am not sure when and how this `update.php` file is executed.

**Comment by ildyria** [comment]
Just tested. Upgrade 3.2.8 is indeed breaking. :(

**Comment by ildyria** [comment]
Fixed with https://github.com/LycheeOrg/Lychee/commit/92cd6c0b4a282bc59d162b1d1f36b5baaf201bf5

**Comment by ildyria** [comment]
For those who had the same problem. Just switch back the settings of `dist` to `775` and it will work again.

**Comment by meminens** [comment]
thanks!

**Comment by amglvr** [comment]
I had exactly the same effect with all the symbols on the main page after updating to 3.2.7. My site is not yet set up for https, so after removing the line "Header set Content-Security-Policy ..." from the .htaccess file Lychee was working fine again.
