### ISSUE TITLE
"Hosted with Lychee" should open new "About"-Dialog not reffering to an external Site

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-v3#160]
"Hosted with Lychee" in the top right when not logged in should open new "About"-Dialog not reffering to an external Site.

**Comment by d7415** [comment]
I think there's plenty of precedent for such links pointing to a project website rather than a local about page, but I'm open to other opinions.

**Comment by ildyria** [comment]
For that one, I would be in favor to let it directing to the github.io website as this is kind of the only visibility we have. If a user is not pleased with that link, he can also easily remove it: https://github.com/LycheeOrg/Lychee/blob/master/index.html#L717

**Comment by bennettscience** [comment]
I think directing to the .io site is the best option. Sending a casual user, in particular, right to GitHub is often a barrier.

**Comment by d7415** [comment]
That seems to be a majority. Closing.
