### ISSUE TITLE
Unable to add photo with exif

### ISSUE THREAD

**Issue by capulo** [LycheeOrg/Lychee-v3#163]
### Detailed description of the problem
i'm not able to upload photo with exif (i tried several)
i always got error : 2019-01-02 22:53:09 - error - Lychee\Modules\Photo::add (289) 	- Data truncated for column 'takestamp' at row 1
same photo without exif works
i think problem is related to issue #136 and caused by commit 0ca43265d022aefcef06630a91ce634bfad060c5 as with older photo.php file upload works
i tried on php 7.0, 7.1 & 7.3, still same

### Steps to reproduce the issue
install latest master and try to upload some photos with exif

### Output of the diagnostics (Settings => Diagnostics)
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version (json):  3.2.8
DB Version:             update_030208
System:                 Linux
PHP Version:            7.3
MySQL Version:          50724
Imagick:                1
Imagick Active:         1
Imagick Version:        1673
GD Version:             2.2.5
Plugins:                

### Browser and system
win7, firefox 64.0, tried also other browsers

**Comment by ildyria** [comment]
Can you upload this picture somewhere ?

**Comment by ildyria** [comment]
Oups I see what went wrong. Sorry for that.

**Comment by ildyria** [comment]
Should be fixed now.
