### ISSUE TITLE
Imges don't get resized if imagick not present/working

### ISSUE THREAD

**Issue by ezek1el** [LycheeOrg/Lychee-v3#165]
### Detailed description of the problem
Uploading photos bigger than 1080p do not show while browsing, the full image shown via "show full picture" appears just fine. Uploading photos with a size of 1920x1080 works as intended. Thumbnails are working too.

The folders /data and /uploads have the right permissions (0755)

the folders /uploads/small and /uploads/medium only contains one file; index.html 

### Steps to reproduce the issue
Upload photos bigger than 1080p

### Output of the diagnostics (Settings => Diagnostics)

Lychee Version (json):  3.2.8
DB Version:             update_030208
System:                 Linux
PHP Version:            7.2
MySQL Version:          50637
Imagick:                -
Imagick Active:         0
Imagick Version:        -
GD Version:             bundled (2.1.0 compatible)
Plugins:                

Log output;
... - notice - Lychee\Modules\Photo::add (242) 	- Skipped adjustment of photo (20181117_220142

### Browser and system
Firefox 64 - Windows 10

**Comment by ildyria** [comment]
How are you installing Lychee ? Are you using the Releases or directly git ?

On the first case, you will have to wait for the next release. On the second case, are you up to date
(I mean with the github master version).
Just to be sure please do:
```sh
cd /your/Lychee/folder
git pull origin master
```

The reason why I ask that is because the very same issue ( https://github.com/LycheeOrg/Lychee/issues/148) has already been solved with PR https://github.com/LycheeOrg/Lychee/pull/158

**Comment by ezek1el** [comment]
I use the Releases. Unfortunately i only have ftp access and no way to use git directly.

**Comment by ildyria** [comment]
Then it is easy to fix.
Download this file: https://raw.githubusercontent.com/LycheeOrg/Lychee/master/php/Modules/Photo.php
(click on the link to open and then save as `Photo.php`)
and using ftp, replace the file `.../Lychee/php/Modules/Photo.php` by the one you just downloaded.

This should fix your problem. :+1: 

After that, you might want to have a look at:
https://github.com/LycheeOrg/Lychee/issues/134 to generate the missing small images.

I will write a script that generate missing medium images or @d7415 can point you to the appropriate plugin.
