### ISSUE TITLE
Error on first call

### ISSUE THREAD

**Issue by Gabbalo** [LycheeOrg/Lychee-v3#166]
### Detailed description of the problem
I just pulled the currend repo and called the URL. The following errors orrured:
---
`Refused to apply style from 'https://$URL$/lychee/dist/user.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`
---
`
Uncaught TypeError: Cannot read property 'version' of undefined
    at main.js:2554
    at Object.success (main.js:1190)
    at u (main.js:2)
    at Object.fireWith [as resolveWith] (main.js:2)
    at k (main.js:2)
    at XMLHttpRequest.<anonymous> (main.js:2)
`
---
`Refused to apply style from 'https://$URL$/lychee/dist/user.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

Steps to reproduce the issue
Pull newest repo on blank webserver.

Output of the diagnostics (Settings => Diagnostics)
No diagnostics available due to no site available

Browser and system
CentOS 7, PHP 7.1

Edit: I am sorry, that layout is so f***ed up, but I can not fix it ... seems legit to me.

**Comment by dbw3** [comment]
![clipboard02](https://user-images.githubusercontent.com/9830202/50925839-b928c580-1410-11e9-9ba6-978e3a3f84a2.png)

I am getting the same errors concerning main.js on ubuntu 18.04 with PHP 7.2.10.  For me, user.css was not created when installing using git.  This is a new installation, and I'm just seeing a blank grey page in the browser; the install script does not launch.

Diagnostics:
Error: Configuration not found. Please install Lychee for additional tests

**Comment by ildyria** [comment]
On it.

**Comment by ildyria** [comment]
For the first one. it is because your server is returning a 404 instead of a css file.
The update will generate the `user.css`.

For the second one. It should be fixed now.

**Comment by ildyria** [comment]
Thanks @Gabbalo @dbw3 for pointing those out. I tend to forget the installation process (and mostly focus on updates. My mistake :( ).

**Comment by dbw3** [comment]
It appears to be working now.  Thank You!

**Comment by Gabbalo** [comment]
I can second that: First run is working finde now :) :+1:
