### ISSUE TITLE
Back button and browser back button

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-v3#168]
The behaviour between the `back`/`ESC` and `previous page` of a browser is inconsistent.
It would be nice if the previous of the browser would have the same behaviour of `ESC`.

Example of current behaviour:
1. Open an album
2. Select a picture (A)
3. move to the next picture (B)
4. 
  - Press `ESC` => you are back on the album
  - or press the back button of your browser => you are back on picture (A)
5. if you pressed `ESC`:
  - Press `ESC` => you are back on main page.
  - or press the back button of your browser => you are back on picture (B).

This should be made consistent between the two: Keep the behaviour of the Lychee app.

Potential interesting resources: https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_replaceState()_method

**Comment by SerenaButler** [comment]
I think the approach should be different. Basically the behaviour is correct and consistent at the moment, each image represents a (new) URL and therefore the browser back button behaviour is correct.  The question is whether the basic behavior has to be like this. Shouldn't you rather redesign the image call (AJAX)?

**Comment by ildyria** [comment]
what do you mean by the image call in AJAX ?

**Comment by SerenaButler** [comment]
Damn I'm not that coder even I have studied it haha ... I hoped you would understand .. I will check later and try to explain better :-) The image should be changed within the page without changing the url.

:-)

**Comment by ildyria** [comment]
I am a software engineer, and as well one of the main developers of Lychee, I do know what AJAX is, I just was not sure what you meant with the image call part. :)

**Comment by SerenaButler** [comment]
I'm pretty sure you know, I hope this is not a language based misunderstanding ;-)

**Comment by ildyria** [comment]
I think we are pretty good on that one now.
