### ISSUE TITLE
Change to zipstreamer

### ISSUE THREAD

**Issue by masterxdk** [LycheeOrg/Lychee-v3#17]
### Detailed description of the problem
We are handing out huge amount of pictures. The last time it was 300 images with a total size of 2.3 GB.
It took Lychee 2.5 min to generate the ZIP file to download. Many changes had to be done to increase the timeouts.

### Steps to reproduce the issue
Try and download a huge amount of images who all add up to a large size

### Output of the diagnostics (Settings => Diagnostics)
504 Gateway Timeout

### Browser and system
Windows 10
Chrome

Lychee:
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.1.6
DB Version:      030102
System:          Linux
PHP Version:     7.2
MySQL Version:   50723
Imagick:         1
Imagick Active:  1
Imagick Version: 1687
GD Version:      2.2.5
Plugins:         

Obs. This was already requested in the original 
https://github.com/electerious/Lychee/pull/781

**Comment by ildyria** [comment]
Solved with 
https://github.com/LycheeOrg/Lychee-Laravel/commit/869590cff34465ddc92159a8d1e5c26e77ce7f16
https://github.com/LycheeOrg/Lychee-Laravel/commit/d8eb4e39344b698f345d3440b35c1533d13d4627
https://github.com/LycheeOrg/Lychee-Laravel/commit/b5fe99f5b702a5913d2d4fdc318e8a2759cacc63

**Comment by ildyria** [comment]
I just downloaded a 1GB generated file to check if this works... and it worked. :)
