### ISSUE TITLE
First start after fresh install failed: Server error or API not found

### ISSUE THREAD

**Issue by jprokop1** [LycheeOrg/Lychee-v3#174]
### Detailed description of the problem
index.php loaded with status code 200, but with error:
"SyntaxError: Unexpected end of JSON input
    at parse (<anonymous>)
    at Ut (http://192.168.1.20/dist/main.js:2:73768)
    at k (http://192.168.1.20/dist/main.js:2:77335)
    at XMLHttpRequest.<anonymous> (http://192.168.1.20/dist/main.js:2:79907)"

### Steps to reproduce the issue
install (https://www.tecmint.com/lychee-photo-management-system-for-linux/)
with php7.2-fpm

### Output of the diagnostics (Settings => Diagnostics)
Diagnostic page blank

### Browser and system
Chrome, IE11
Ubuntu 18.04, PHP 7.2, NGINX 1.14.2

**Comment by ildyria** [comment]
I have never used nginx. I will check what is wrong.

**Comment by ildyria** [comment]
Could not reproduce on Ubuntu 18.04 with Nginx following the same instruction as yours.

The only thing I see is a bad Nginx configuration.
```
server {
	listen      80;
	server_name	 lychee.example.com;
	root         	/var/www/html/Lychee/;
	index       	index.html;

	charset utf-8;
	gzip on;
	gzip_types text/css application/javascript text/javascript application/x-javascript 	image/svg+xml text/plain text/xsd text/xsl text/xml image/x-icon;
	location / {
		try_files $uri $uri/ /index.php?$query_string;
	}
	location ~ \.php {
		include fastcgi.conf;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/run/php/php7.2-fpm.sock;
	}
	location ~ /\.ht {
		deny all;
	}
}
```
Verify that you are well redirecting to **php7.2-fpm** here.

Also,  when I was using `http://localhost/Lychee` it was not working and giving me some 405 error. However when I added `127.0.0.1    lychee.example.com` to my `/etc/hosts` and then pointed my navigator to `lychee.example.com` it was working properly.

**Comment by jprokop1** [comment]
Problem was in Nginx PHP Configuration:
missing line in /etc/nginx/fastcgi_params:

```
fastcgi_param   SCRIPT_FILENAME         $document_root$fastcgi_script_name;
```

After correction works!
