### ISSUE TITLE
docker image video thumb creation error

### ISSUE THREAD

**Issue by aptalca** [LycheeOrg/Lychee-v3#175]
Hi guys, I'm one of the linuxserver.io devs and I'm trying to add ffmpeg support into the lychee image for video thumb creation. However I can't get it to work. I'm hoping you can help troubleshoot.

### Detailed description of the problem
I added the ffmpeg package, both ffmpeg and ffprobe inside the container work when launched manually.
Also added php-ffmpeg via composer

However, uploading a video results in the error `error - Lychee\Modules\Photo::add (268) 	- Could not create thumbnail for video`

### Steps to reproduce the issue
Here's our test image Dockerfile: https://github.com/linuxserver/docker-lychee/blob/ffmpeg/Dockerfile
And here's the built test image `lspipepr/lychee` https://hub.docker.com/r/lspipepr/lychee/tags

### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version (json):  3.2.10
DB Version:             update_030210
System:                 Linux
PHP Version:            7.2
MySQL Version:          50505
Imagick:                1
Imagick Active:         1
Imagick Version:        1799
GD Version:             bundled (2.1.0 compatible)
Plugins:                
```
### Browser and system
docker image at `lspipepr/lychee`

**Comment by d7415** [comment]
Have you tried specifying the binary locations as [here](https://github.com/LycheeOrg/Lychee/wiki/FAQ#why-dont-my-videos-have-thumbnails)?

**Comment by aptalca** [comment]
@d7415 thanks so much for that heads up. Defining the binary locations indeed fixed the issue.
But the weird part is, the locations are really the default locations that I assumed lychee would look in, `/usr/bin/ffmpeg` and `/usr/bin/ffprobe`.

For now I'll put in a sed to fix the locations, but is there a system wide fix? Setting paths or environment variables? I don't know enough about the php-fpm plugin to troubleshoot (not a fan sed'ing app files).

Thanks

**Comment by d7415** [comment]
I had the same problem and never got to the bottom of it. In theory it's supposed to be needed when ffmpeg isn't in php's PATH, but I think in my case /usr/bin/ was in there. Once I got it working I pretty much gave up (and later added it to the FAQ).

For a more general fix, I guess you'd need to speak to the [PHP-FFMpeg](https://github.com/PHP-FFMpeg/PHP-FFMpeg) devs as iirc Lychee (without that block) just uses its defaults.
