### ISSUE TITLE
Large local import

### ISSUE THREAD

**Issue by roblandry** [LycheeOrg/Lychee-v3#177]
Ive been trying to import tons of photos for days. I came to the conclusion that it is related to the max execution time of php. As a workaround, for large intitial imports, i would recommend adding a way to give unlimited execution time with a LARGE disclaimer. I edited /php/Modules/Import.php and added this after:

https://github.com/LycheeOrg/Lychee/blob/760ec6008a6f85cf666245a8bdcb3d39ba96c394/php/Modules/Import.php#L3
```php
set_time_limit(0);

```

This allows the script to run until finished or until max memory reached. As i said, it is a bad thing to have this, however, i was only importing about 50 photos or so at a time, and i have thousands.

Might be worth adding a unlimited execution time variable, and testing if true to enable the unlimited time limit.

**Comment by ildyria** [comment]
If you are using Import yes.

However if you are using Upload, you do not have this limitation (I uploaded more than 100 files at once) as for every file you will be launching the script..

> Might be worth adding a unlimited execution time variable, and testing if true to enable the unlimited time limit.

This can easily be done. I like the idea of it to be a setting (obviously disabled by default).

Can you make a PR with this?
**Also you do not even need to care about the user interface part as users now have full access to Lychee settings via the "More" button and "Save my modifications, I accept the Risk!"** :warning: :smiley: 

Disclaimer should be placed in the wiki though.

**Comment by roblandry** [comment]
Yes, i will work on a PR in the near future, and submit when done. 😃 👍

**Comment by ildyria** [comment]
Have a look at : https://github.com/LycheeOrg/Lychee/blob/master/php/database/update_030109.php to see how to add a setting in the Database (you will obviously need to create a new `update_0302XX.php` file ;) )

And if you have questions, feel free to drop by here: https://gitter.im/LycheeOrg/Lobby :)

**Comment by d7415** [comment]
We should probably document this in the wiki (if we haven't already)

**Comment by d7415** [comment]
> We should probably document this in the wiki (if we haven't already)

Added to FAQ.
