### ISSUE TITLE
Watermark plugin does not work

### ISSUE THREAD

**Issue by cernyjan** [LycheeOrg/Lychee-v3#187]
### Detailed description of the problem
Gallery stops working, when watermark (https://github.com/electerious/lychee-watermark) is enabled.
On web -> Error: Server error or API not found.
In Console ->
Fatal error: Uncaught Error: Call to a member function attach() on null in /DISK2/WWW/.../www/plugins/watermark/Watermark.php:219
Stack trace:
#0 /DISK2/WWW/.../www/php/autoload.php(20): require()
#1 [internal function]: {closure}('watermark\\Water...')
#2 /DISK2/WWW/.../www/php/Modules/Plugins.php(38): spl_autoload_call('watermark\\Water...')
#3 /DISK2/WWW/.../www/php/Modules/Plugins.php(23): Lychee\Modules\Plugins->__construct(Array)
#4 /DISK2/WWW/.../www/php/Modules/Session.php(14): Lychee\Modules\Plugins::get()
#5 /DISK2/WWW/.../www/php/Access/Guest.php(117): Lychee\Modules\Session->init(true)
#6 /DISK2/WWW/.../www/php/Access/Guest.php(29): Lychee\Access\Guest::initAction()
#7 /DISK2/WWW/.../www/php/index.php(81): Lychee\Access\Guest::init('Session::init')
#8 {main}
  thrown in /DISK2/WWW/.../www/plugins/watermark/Watermark.php on line 219 

### Browser and system

**Comment by d7415** [comment]
Unfortunately, I'm unfamiliar with that plugin, and it was deprecated 3 years ago, before electerious stopped working on Lychee so I'm not even sure *when* it stopped working.

**Comment by ildyria** [comment]
Same as @d7415 .

**Comment by d7415** [comment]
Someone might have some ideas for how to get this working, but I'm going to close this as out of scope. Especially as v4 will break it again anyway. You may want to repost this as a feature request.

**Comment by ildyria** [comment]
I will also add, that you might want to place your watermark through e.g. Lightroom. It gives you more control of where you want your watermark placed on.
