### ISSUE TITLE
image size missing from about

### ISSUE THREAD

**Issue by mir07** [LycheeOrg/Lychee-v3#188]
### Detailed description of the problem
When pressing 'i' to show about of an image the image size is missing even though the image size can be found in the lychee_photos table.

```sql
select count(*) from lychee_photos;
+----------+
| count(*) |
+----------+
|      350 |
+----------+
1 row in set (0.00 sec)

select count(*) from lychee_photos where `size` > 0;
+----------+
| count(*) |
+----------+
|      350 |
+----------+
1 row in set, 350 warnings (0.00 sec)

select size from lychee_photos where title = 'DSC_0002';
+--------+
| size   |
+--------+
| 8.1 MB |
+--------+
1 row in set (0.00 sec)
```

(See screenshot from about for this image)
![screenshot at 2019-02-10 23-53-54](https://user-images.githubusercontent.com/2576455/52540929-718ab600-2d8f-11e9-8e70-2d4cc6bedff7.png)

### Steps to reproduce the issue
There is no step involved
### Output of the diagnostics (Settings => Diagnostics)
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.

System Information
------------------
Lychee Version (json):  3.2.10
DB Version:             update_030210
System:                 Linux
PHP Version:            7
MySQL Version:          50505
Imagick:                1
Imagick Active:         1
Imagick Version:        1687
GD Version:             2.2.4
Plugins:                

### Browser and system
Firefox 65.0 (64 bit) Debian Sid (64 bit)

**Comment by d7415** [comment]
Thanks for spotting this.
