### ISSUE TITLE
How to join the LycheeOrg Organization ?

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-v3#19]
There is no contact point or entry point.

**Comment by LudovicRousseau** [comment]
Opening an issue is a good idea.

I don't know how @fly-man- wants to handle new members. I guess proposing Pull Requests is a good start.

**Comment by fly-man-** [comment]
I think @LudovicRousseau is the person who can help you there. He's the one who has the LycheeOrg permissions

**Comment by LudovicRousseau** [comment]
@ildyria I just sent you an invitation to join LycheeOrg
