### ISSUE TITLE
non-EXIF Image overlay doesn't appear to be working

### ISSUE THREAD

**Issue by mjoras** [LycheeOrg/Lychee-v3#192]
### Detailed description of the problem
Using master I am not able to get any overlay to show up that isn't an EXIF overlay.
### Steps to reproduce the issue
The following settings result in the following result:
https://screenshots.firefox.com/g18LzotE3F5X7N8e/lychee.mjoras.com
https://screenshots.firefox.com/xv6jnQrXtTxvWBkQ/lychee.mjoras.com
### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version (json):  3.2.11
DB Version:             update_030211
System:                 Linux
PHP Version:            7.2
MySQL Version:          50505
Imagick:                1
Imagick Active:         1
Imagick Version:        1799
GD Version:             bundled (2.1.0 compatible)
Plugins:                
```
### Browser and system
Firefox 65 on Linux, same result on Chromium.

**Comment by ildyria** [comment]
Could not reproduce.

You can also rotate through the overlays with `o` (to check if there is a `takedate` available)

**Comment by mjoras** [comment]
o doesn't seem to do anything. All I see is the EXIF overlay. This is with a photo with a description set. Should o also make the overlay disappear? Because that's also not happening even for the EXIF overlay.

**Comment by mjoras** [comment]
If you want a live example, this is the photo on my server that is not working for me, settings are still as above: https://lychee.mjoras.com/#15499956314777/15498816924903

**Comment by bennettscience** [comment]
I'm able to toggle between EXIF and the description. The `takedate` param in `photo.json` is set to `false`, which is why it isn't showing a date (and is also a little weird...)

Can you load another picture, open your browser console, and log `photo.json` and paste the result? Or, if it's shown an error when you use the `o` key, paste the error in.

**Comment by mjoras** [comment]
Bizarre. To clarify you're able to toggle it on my image? For some reason `o` doesn't do anything for me with that link, I can't toggle to the description.

Anyway, here's photo.json for another photo:
```
photo.json
{…}
​
album: "15498811611732"
​
aperture: "f/1.8"
​
cameraDate: "1"
​
description: ""
​
focal: "4 mm"
​
height: "3024"
​
id: "15499432515481"
​
init: 1
​
iso: "20"
​
lens: "iPhone 8 back camera 3.99mm f/1.8"
​
license: "none"
​
make: "Apple"
​
medium: "uploads/medium/6430b989779310cf55068569adfaa5f8.jpeg"
​
model: "iPhone 8"
​
original_album: "15498811611732"
​
public: "0"
​
shutter: "1/1499 s"
​
small: "uploads/small/6430b989779310cf55068569adfaa5f8.jpeg"
​
star: "0"
​
sysdate: "12 February 2019"
​
tags: ""
​
takedate: false
​
thumbUrl: "uploads/thumb/6430b989779310cf55068569adfaa5f8.jpeg"
​
title: "1E1411FD-A01E-4B8F-B15E-455FB4"
​
type: "image/jpeg"
​
url: "uploads/big/6430b989779310cf55068569adfaa5f8.jpeg"
​
width: "4032"
```

I don't see any messages while hitting `o` in either chrome or firefox.

**Comment by bennettscience** [comment]
Did you run `git pull --recurse-submodules` to update Lychee-front at the same time as the 3.2.11 update on your server? If not, run `git update submodule origin master` to make sure you have the latest frontend code.

**Comment by mjoras** [comment]
I'm using the linuxserver.io docker. Does it look like the frontend on my server is just out of date? I can follow up with the linuxserver.io people to see how they're updating the docker image.

**Comment by bennettscience** [comment]
That's what I'm thinking. Maybe @roblandry could offer some insight? I don't use Docker at all.

**Comment by mjoras** [comment]
@bennettscience I asked on discord, and they've indicated they don't actually use git, they download the release zip.

**Comment by mjoras** [comment]
I wonder if the 3.2.11 tag had the wrong submodule included for the frontend.

**Comment by bennettscience** [comment]
Ok. I just want to make sure we're on the same page.

1. Load the image. Click to toggle the overlay. Nothing shows?
2. If something shows, hit the `o` hotkey. What happens?

If the overlay is toggled by default, that means it will show when the photo loads _without_ a click. It can still be hidden with a mouse click on the image.

If you `console.log(lychee)`, what do you see for the `image_overlay` keys?

**Comment by mjoras** [comment]
I figured out my problem, it was really stupid. It was actually just cloudflare caching the dist js file for 3.2.10, even though I told it to purge everything for the subdomain. Whacking it to purge everything has cleared up the issue.

Thanks for the help and sorry for the noise.

**Comment by ildyria** [comment]
@mjoras As you mentionned discord, I will point you to our gitter which you can access with your github account at: https://gitter.im/LycheeOrg/Lobby
:)
