### ISSUE TITLE
"Server error or API not found." because dist/user.css is missing

### ISSUE THREAD

**Issue by LudovicRousseau** [LycheeOrg/Lychee-v3#194]
### Detailed description of the problem

If I go to the "Settings" page I get a "Erreur: Server error or API not found." message in red

### Steps to reproduce the issue
Install Lychee

### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Error: Upgrade to PHP 7.1 or higher

System Information
------------------
Lychee Version (json):  3.2.12
DB Version:             update_030212
System:                 Linux
PHP Version:            7
MySQL Version:          50505
Imagick:                1
Imagick Active:         1
Imagick Version:        1687
GD Version:             2.2.4
Plugins:                
```

### Browser and system
Firefox 65.0 on macOS Mojave

### Debug
From Firefox logs I see that the file `user.css` is not found and get a 404 code from the server.
After I create this file using `touch dist/user.css` on the server I do not get the error any more.

I see that the file `user.css` should be created on upgrade by https://github.com/LycheeOrg/Lychee/blob/master/php/database/update_030208.php#L52
But in my case the directory `dist/` is not own by www-data and the php script has no rights to create a new file there.

I propose to update the Diagnostics page to report that access rights for `dist/` are not correct.
Or better, that the file `user.css` should be present and writeable by the web server.
Does Lychee really need a write access to the `dist/` directory itself?

I also note that I can click on "Change CSS" in the Preferences. I get no error and even a "OK: CSS updated". But the file `user.css` has NOT been updated. Of course because the web server has no write access on this file.

**Comment by ildyria** [comment]
> I propose to update the Diagnostics page to report that access rights for `dist/` are not correct.
Or better, that the file `user.css` should be present and writeable by the web server.

:+1:

> Does Lychee really need a write access to the `dist/` directory itself?

Aside from the `user.css` not really.

**Comment by LudovicRousseau** [comment]
I made a proposal but I am not a PHP developer.
I was expecting someone would pick this task and implement what is missing it for me :-)
