### ISSUE TITLE
Feature proposal: full HiDPI support

### ISSUE THREAD

**Issue by kamil4** [LycheeOrg/Lychee-v3#198]
### Detailed description of the problem
Lychee currently provides partial support for HiDPI ("retina") displays. The square thumbnails are generated in both regular (200x200px) and @2x (400x400px) variants, but the small (*x360px) and medium (1920x1080px) pictures are not.

I am interested in contributing the missing functionality to Lychee. Since there's already support for @2x thumbnails, I expect that extending it to cover the remaining sizes will be simple (famous last words...).

I would like to gauge your interest in this effort and in particular how it should be exposed to users? The @2x thumbnails are generated unconditionally but they are tiny so that's not a big deal. medium @2x pictures in particular could take significant space at up to 3840x2160px so people who don't care about them might complain. Should there be a "HiDPI" option in the settings? If so, should it apply to all three generated picture sizes, or should thumbnails always be generated with @2x like now, or should there be a separate setting for each size? What should be the default value? Etc.

I'm looking forward to hearing from you. This looks like a great project and I'd be happy to contribute!
### Browser and system

**Comment by ildyria** [comment]
I would consider extending for the small but I would put it as an option to be enabled by the user (same idea as https://github.com/LycheeOrg/Lychee/wiki/FAQ#im-importing-a-lot-of-photos-using-import-from-server-and-lychee-times-out-before-its-done )

I am fine if this is added as such. Also... **You might consider also making these changes to the next version of Lychee available in alpha|beta stages here: https://github.com/LycheeOrg/Lychee-laravel**

**Comment by ildyria** [comment]
Fixed in Lychee v4.
