### ISSUE TITLE
Feature request: unjustified layout

### ISSUE THREAD

**Issue by kamil4** [LycheeOrg/Lychee-v3#199]
### Detailed description of the problem
I'm looking for a way to display the photos in an album so that they are show in the correct aspect ratio (uncropped, like what the justified layout does), but using a fixed height for all images, that is, without row scaling to get the justified right margin. I've seen albums on Google Photos that are displayed like that, unjustified, and I like it.

Is there any quick hack that would make it possible in Lychee? I've been trying to mess around with JS and user CSS but I can't get it to work. I also tried passing targetRowHeightTolerance equal to 0 (or 0.01) to justified-layout but that doesn't seem to do anything...

It's frustrating because it feels like something that would be trivial to do in HTML 1.0 simply as a series of <img> tags but here it's such a struggle...

### Browser and system

**Comment by ildyria** [comment]
You might want to have a look at 
https://medium.com/@andybarefoot/a-masonry-style-layout-using-css-grid-8c663d355ebb

Also if you add this feature we will gladly merge it as an alternative to the squares and justified layout.

**Comment by kamil4** [comment]
OK, I believe this feature should now be complete.
