### ISSUE TITLE
Place to discuss (e.g. gitter.im)

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-v3#20]
### Detailed description of the problem

It would be nice if there was a place to discuss about Lychee...
e.g. using https://gitter.im/ (thus tied with github).

**Comment by LudovicRousseau** [comment]
I am from the old school and I use mailing list in general.
I am not against new tools. So I created https://gitter.im/LycheeOrg/Lobby that should be associated with the github organization.
