### ISSUE TITLE
Minor UI Issue Settings Siebar

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-v3#201]
### Detailed description of the problem

Close Cross should be left so that no mouse moving is needed when you wanna close the settings sidebar right away.

![lychee_ui_sidepane_bug_04](https://user-images.githubusercontent.com/35893306/52850595-27e5f680-3114-11e9-89f3-001fba9d341e.png)

**Comment by ildyria** [comment]
:+1:

**Comment by d7415** [comment]
I agree with the sentiment, but I think I expect it to be on the right. Conflicting UX...

**Comment by SerenaButler** [comment]
Position is given by the first to use UI Element and how to come back to this state. 

The expectation to have it on the right, and I agree with that visually, is a visual one not an UX one as the usability right now needs more "work" to do as "needed" :-)

**Comment by d7415** [comment]
> The expectation to have it on the right, and I agree with that visually, is a visual one not an UX one as the usability right now needs more "work" to do as "needed" :-)

"needed" is probably a stretch... As far as I can tell this only applies to accidental opening of the menu.

**Comment by ildyria** [comment]
The solution is to make the "top part" clickable to close. :)

**Comment by d7415** [comment]
> The solution is to make the "top part" clickable to close. :)

I thought about that. I wasn't sure about it, but I have no objections beyond that :)

**Comment by SerenaButler** [comment]
Like this?

<img width="230" alt="new mockup 1" src="https://user-images.githubusercontent.com/35893306/52852785-e35d5980-3119-11e9-8ddf-91218835925d.png">

**Comment by ildyria** [comment]
:+1:

**Comment by ildyria** [comment]
Already fixed.
