### ISSUE TITLE
Feature request: Add links to different sizes for one picture

### ISSUE THREAD

**Issue by dhaillant** [LycheeOrg/Lychee-v3#204]
### Detailed description of the problem
Hi, I switched from Flickr to Lychee several months ago.
One thing I really miss from Flickr is the choice of several default sizes for each stored picture.

Below is a copy/paste of Flickr's download page for one picture:

Sizes:
            Square 75 (75 x 75)	
            Square 150 (150 x 150)	
            Tiny (100 x 71)	
            Small 240 (240 x 171)	
            Small 320 (320 x 228)	
            Medium 500 (500 x 356)	
            Medium 640 (640 x 456)	
            Medium 800 (800 x 570)	
            Large 1 024 (1024 x 729)	
            Original (1280 x 911)	

Each dimension links to a pre resized image file.

It allows you to choose one for inclusion in forums, websites etc.
Very usefull if you don't want to manually resize, then upload several copies for every picture.

I know there are big, medium, small folders available but no link is displayed in image description. Only "full photo" and "download" links are present.

Thank you!

**Comment by ildyria** [comment]
This will **not** be added in Lychee v3. However, we may consider adding it to the next version (v4 currently in alpha stages here: https://github.com/LycheeOrg/Lychee-laravel ). :)

Not that the download link will disappear in the next version, only the "full picture" will remain (at the moment).

**Comment by d7415** [comment]
Potentially this could be added in a limited form (with the existing thumb/small/medium sizes) through Lychee-front without changing Lychee itself. Additionally, this way *should* still work with Lychee-laravel.

It's not high on my priority list, but that could be an option if someone else wants to try to implement this.

**Comment by rnwgnr** [comment]
I will try to implement the "limited form", but my approach requires a (non-breaking) change in the backend as well.
If you are interested in giving feedback, have a look at the current state of https://github.com/guzzisti/Lychee/

**Comment by ildyria** [comment]
@guzzisti here is my first feedback. Don't fork this repo (Lychee v3) but that one https://github.com/LycheeOrg/Lychee-laravel 
So your change can be directly integrated in the version 4 of Lychee. :smiley:

**Comment by dhaillant** [comment]
I uploaded a lot of pictures using the 3.1.6 version (or maybe an older version). Small pictures weren't created automatically at that time.
Is there a way to batch create missing files? Thank you!

**Comment by d7415** [comment]
> I uploaded a lot of pictures using the 3.1.6 version (or maybe an older version). Small pictures weren't created automatically at that time.
> Is there a way to batch create missing files? Thank you!

See https://github.com/LycheeOrg/Lychee/issues/134#issuecomment-443597023

Please try to keep comments on issues relevant to that specific issue. (I accept that this is *your* issue, and that there's a happy medium between having too many issues and having unclear issues)

**Comment by ildyria** [comment]
I think this is done.
