### ISSUE TITLE
Upload // Error Message

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-v3#205]
### Steps to reproduce the issue

When uploading images I got these errors. Images are uploaded fine though.

![image](https://user-images.githubusercontent.com/35893306/52866555-372e6980-313f-11e9-9caa-de3cf3fcc110.png)

Console

![image](https://user-images.githubusercontent.com/35893306/52866583-3f86a480-313f-11e9-890c-d4319b9eeaad.png)

### Output of the diagnostics (Settings => Diagnostics)

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version (json):  3.2.12
DB Version:             update_030212
System:                 Linux
PHP Version:            7.1
MySQL Version:          50721
Imagick:                1
Imagick Active:         1
Imagick Version:        1673
GD Version:             bundled (2.1.0 compatible)
Plugins:        

### Browser and system

Win 10 // Google Chrome Version 72.0.3626.109 (64-Bit)

**Comment by ildyria** [comment]
I cannot reproduce, do you have an image for me to try with ?

**Comment by SerenaButler** [comment]
[disarmodel_review_atrevida_50.zip](https://github.com/LycheeOrg/Lychee/files/2869871/disarmodel_review_atrevida_50.zip)

**Comment by d7415** [comment]
Is there any output in Lychee's log?

**Comment by ildyria** [comment]
Very weird, still could not reproduce. :(

**Comment by SerenaButler** [comment]
Nothing unusual in Log, e.g.: 
2019-02-15 16:26:35 - notice - Lychee\Modules\Photo::add (242) 	- Skipped adjustment of photo (disarmodel_review_atrevida_01)

My More Settings
![lychee_upload_02](https://user-images.githubusercontent.com/35893306/52869600-51b81100-3146-11e9-9c87-16fd33771dfc.png)

**Comment by d7415** [comment]
If you run without `useExiftool` does it still raise errors?

**Comment by SerenaButler** [comment]
Unfortunately yes ..:-(

**Comment by ildyria** [comment]
can you do this:

```
git reset --hard HEAD^
```
try upload, this if this raise an error.
If it does, redo the command and try to upload etc...
Once it does not raise an error, do 
```
git show HEAD
```
to see what is the last commit that was working for you.

It may sound scary but you should be fine, you can always do a `git pull master` to get back to your initial state.

**Comment by SerenaButler** [comment]
Sorry can't do that. I always update manually. Not my server. Sorry :-(

**Comment by ildyria** [comment]
:(

**Comment by SerenaButler** [comment]
Anything else I can do or check?

**Comment by mir07** [comment]
You say you update manually, so I presume this means simply copy the content of the lychee-some-version.zip to the folder on the server containing your lychee installation, right?
If you have done this I am certain that you miss this file: dist/user.css?
To fix the error simple create an empty file in the dist folder named user.css with owner changed to whatever owner found for files in uploads/big/

**Comment by SerenaButler** [comment]
> If you have done this I am certain that you miss this file: dist/user.css?

No ;-) But thanks.

**Comment by bennettscience** [comment]
@SerenaButler Do you see any errors in the Network tab of the inspector? Check your XHR requests.

**Comment by SerenaButler** [comment]
I get this:

![1](https://user-images.githubusercontent.com/35893306/52975443-dfedfa80-33c5-11e9-8986-724f9db256d2.png)

**Comment by mir07** [comment]
Is your server running php in safe_mode?
See http://php.net/manual/en/ini.sect.safe-mode.php

**Comment by mir07** [comment]
Or are your server running on Windows?

**Comment by SerenaButler** [comment]
No and No. I did not had this "false error" with 3.2.9.

**Comment by mir07** [comment]
But your error clearly states that the php interpreter is not allowed to run either /bin/sh or /usr/bin/which

**Comment by mir07** [comment]
What operating system do you specifically use, maker and version?
Your errors indicate that your php process is running in either a jail or protected mode where access to executing system commands is disallowed.

**Comment by d7415** [comment]
I'm curious what the errors are without `useExiftool`, as that specific error shouldn't be triggered.

**Comment by mir07** [comment]
The error will be there whether using useExiftool or not since checking if useExiftool is true will execute the system call which detects whether exiftool are present or not. See 'public static function useExiftool()' in Settings.php

**Comment by mir07** [comment]
I have tried to see whether catching an exception is possible but without luck ;-(

**Comment by mir07** [comment]
I might have found a solution that does not cause error messages:
```diff
diff --git a/php/Modules/Settings.php b/php/Modules/Settings.php
index 928dee9..12440c5 100755
--- a/php/Modules/Settings.php
+++ b/php/Modules/Settings.php
@@ -352,8 +352,8 @@ final class Settings {
         /**
          * @return bool Returns the useExiftool setting.
          */
-        public static function useExiftool() {
-                system('which exiftool 2>&1 > /dev/null', $status);
+       public static function useExiftool() {
+                exec('which exiftool 2>&1 > /dev/null', $output, $status);
                 if ($status != 0) return false;
                 return (bool) (self::get()['useExiftool'] === '1');
         }
```
Could you try above patch?

**Comment by mir07** [comment]
Forgot to mention. To provoke a similar error simply call a non existing command like 'which1'

**Comment by ildyria** [comment]
Actually this version is better as you skip the test if you don't enable `useExiftool`:

```php
public static function useExiftool() {
         if(self::get()['useExiftool'] === '1')
         {
             exec('which exiftool 2>&1 > /dev/null', $output, $status);
             if ($status != 0) return false;
             return true;
         }
         return false;
}
```

**Comment by SerenaButler** [comment]
I can confirm that this (ildyrias code) is working and the error message is gone :-)

Thanks Michael! :-)

**Comment by SerenaButler** [comment]
Do I understand it correct that the Exiftool is not working on my hosted webspace though?

**Comment by ildyria** [comment]
@SerenaButler Either that or `system`/`exec` are disabled.

**Comment by SerenaButler** [comment]
I checked and I HAVE exiftool running in my hosted enviroment (all-inkl.de) so it would be nice to get it running with Lychee too ;-)

**Comment by ildyria** [comment]
Surprising then :(
Care to open a new issue then? :sweat_smile: 
(I mean, this issue is about the error message :stuck_out_tongue: )

**Comment by SerenaButler** [comment]
Pffff .... hahaha ... ok :-P

**Comment by ildyria** [comment]
Also feel free to drop by our gitter: https://gitter.im/LycheeOrg/Lobby :)
