### ISSUE TITLE
Exiftool not working on (my) hosted webspace (all-inkl.de)

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-v3#209]
### Detailed description of the problem
Exiftool is not working even it is installed and running on my hosted webspace. I checked and I can run it via ssh.

let me know what I can do to help :-)

![exiftool_01](https://user-images.githubusercontent.com/35893306/53007283-37787e80-3437-11e9-8c39-5c698d8645f7.png)

### Output of the diagnostics (Settings => Diagnostics)
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version (json):  3.2.12
DB Version:             update_030212
System:                 Linux
PHP Version:            7.1
MySQL Version:          50721
Imagick:                1
Imagick Active:         1
Imagick Version:        1673
GD Version:             bundled (2.1.0 compatible)
Plugins:

**Comment by d7415** [comment]
If it's hosted, it's possible that they've disabled the `system()` function in php.

**Comment by SerenaButler** [comment]
I will check with hoster. Small nice company and I know they like Lychee :-)

**Comment by mir07** [comment]
I have a feeling your hoster runs php using php-fpm which makes it possible to run php inside of a chroot environment and/or runs without permission to run any system commands:
"Starting the workers with different uid/gid/chroot/environment and different php.ini options. (No need for safe mode.)"
https://php-fpm.org/about/

**Comment by rnwgnr** [comment]
Yep, all-inkl runs php-fpm. System calls are allowed: https://all-inkl.com/wichtig/faq/#exec

**Comment by SerenaButler** [comment]
So it exiftools should (could) run with my hoster?

**Comment by mir07** [comment]
> So it exiftools should (could) run with my hoster?

Yes, provided the user which runs php-fpm is given permission to run the command or the command is installed in the chroot.

**Comment by SerenaButler** [comment]
Ok, so Lychee will be able to run with exiftools on my hoster. Just someone has to do it :-D

**Comment by ildyria** [comment]
@SerenaButler you might want to document this in the Wiki at some point. :)

**Comment by SerenaButler** [comment]
? I'm lost. It is still not running though ...What I meant is my hoster seems not the problem but still no exiftools :-(

**Comment by rnwgnr** [comment]
I`m hosting at all-inkl.com myself and gave it a try. What i did:

1. enable exiftool in advanced settings
2. uploaded a new photo
3. exifs are shown for this picture

So i guess exiftool works for me. Have you tried switching to PHP 7.2? 
```
System Information
------------------
Lychee Version (json):  3.2.13
DB Version:             update_030213
System:                 Linux
PHP Version:            7.2
MySQL Version:          50723
Imagick:                1
Imagick Active:         1
Imagick Version:        1687
GD Version:             bundled (2.1.0 compatible)
Plugins:                
```

**Comment by SerenaButler** [comment]
I'm stupid ... haha .. please close it ... eijeijei ....

**Comment by ildyria** [comment]
Naaah, we will take a screenshot of it and frame it in the hall of shame :smile:

**Comment by SerenaButler** [comment]
I would like to note that I am not THAT stupid ... apparently it makes no difference with my hoster whether exiftools is set on/off or not. ;-)
