### ISSUE TITLE
Server Error or Api not found

### ISSUE THREAD

**Issue by meetthemeat** [LycheeOrg/Lychee-v3#213]
### Detailed description of the problem

I set up lychee and mariadb. After the first start everything was working. I started importing photos from the server and it run for a couple of thousands photos. There the importing screen didn't disappeared I checked with heidisql if new pics are added to the db. After I recognized there is no more pic added to the db I refreshed the lychee application and got the "Error: Server error or API not found"

I also checked previous impediments realted to this error message but it seems there is no related.
### Output of the diagnostics (Settings => Diagnostics)
Output from chrome developer console:

```
main.js:2 POST http://192.168.178.31:81/php/index.php 500 (Internal Server)
{description: "Server error or API not found.", params: {…}, response: "Internal Server Error"}description: "Server error or API not found."params: {function: "Session::init"}response: "Internal Server Error"__proto__: Object
lychee.error @ main.js:2979
error @ main.js:1198
u @ main.js:2
fireWith @ main.js:2
k @ main.js:2
(anonymous) @ main.js:2
load (async)
send @ main.js:2
ajax @ main.js:2
api.post @ main.js:1201
lychee.init @ main.js:2575
(anonymous) @ main.js:2298
l @ main.js:2
c @ main.js:2
setTimeout (async)
(anonymous) @ main.js:2
u @ main.js:2
fireWith @ main.js:2
fire @ main.js:2
u @ main.js:2
fireWith @ main.js:2
ready @ main.js:2
setTimeout (async)
(anonymous) @ main.js:2
(anonymous) @ main.js:2
(anonymous) @ main.js:2
```

### Browser and system
For lychee I'm using this docker image: https://hub.docker.com/r/linuxserver/lychee
and mariadb: https://hub.docker.com/r/linuxserver/mariadb
hosted on OpenMediaVault 4.1.19
Browser latest Chrome x64 72.0.36

**Comment by d7415** [comment]
Hi. Please provide the output of the Diagnostics page.

**Comment by ildyria** [comment]
An error 500 does not really gives us anything to work with...
Could you please provide us with the content of what you get when you go in:
http://192.168.178.31:81/plugins/Diagnostics/index.php

**Comment by ildyria** [comment]
Also please have a look at this: https://github.com/LycheeOrg/Lychee/wiki/I-have-an-Error-500-what-can-I-do%3F

**Comment by meetthemeat** [comment]
> Hi. Please provide the output of the Diagnostics page.

If you mean  xxx.xxx.xxx:81/plugins/Log/
I get
`Page is not working 192.168.178.31 can't process request.
HTTP ERROR 500`

**Comment by ildyria** [comment]
Then please proceed with the WIKI link. :)

**Comment by meetthemeat** [comment]
> An error 500 does not really gives us anything to work with...
> Could you please provide us with the content of what you get when you go in:
> http://192.168.178.31:81/plugins/Diagnostics/index.php
```
Diagnostics
-----------
```
empty


thx for your support

will check the wiki

**Comment by meetthemeat** [comment]
Have to apologize. Probelm was caused by my modification of config.php.
After I commented out my modifications it was working again.
But @ildyria @d7415 do you know why it is failing when I add this lines (related to https://github.com/electerious/Lychee/blob/master/docs/Settings.md)?

> config.php

 
```
imagick = 1;
skipDuplicates = 1;
```

**Comment by ildyria** [comment]
Well this is not php. In Php variables start with `$` so obviously this raise errrors.

To actually changes these, it has to be done online. You need to go to `Settings (cog)` => `Settings (menu)` => `More` (at the bottom of the page), there you can modify every values and validate by clicking on **Save my modification, I accept the Risk!**.

However if you do that, you are on your own if it breaks. :stuck_out_tongue:

**Comment by meetthemeat** [comment]
Thx for your support and proposal
in php I definetly haven't my strengths ;-)

**Comment by tehniemer** [comment]
I'm getting the same behavior on a fresh install of lychee using the linuxiso docker image. I did what was suggested in the wiki page and found that there was no index.php in the php folder. I created one and populated it with what's shown in the wiki and there was no change in behavior.

**Comment by d7415** [comment]
> I'm getting the same behavior on a fresh install of lychee using the linuxiso docker image. I did what was suggested in the wiki page and found that there was no index.php in the php folder. I created one and populated it with what's shown in the wiki and there was no change in behavior.

The contents on the wiki are not a complete file. If `php/index.php` was missing then the image is corrupt and you should file a bug against that docker image, which is not maintained here. You could try downloading the [file](https://github.com/LycheeOrg/Lychee/blob/master/php/index.php) from this repository separately (and, if necessary, adding the error reporting from the wiki), but there's no certainty that there won't be other missing files.

I'm going to lock this issue as the error is too generic to say much more than "look at the wiki".
