### ISSUE TITLE
error when moving photo to album

### ISSUE THREAD

**Issue by rnwgnr** [LycheeOrg/Lychee-v3#220]
### Detailed description of the problem
When viewing a single photo, it is not possible to move the photo to an album using the folder icon in the context menu.
Moving a single or even multiple photos from the album view works well.

### Steps to reproduce the issue
1. Open a photo in the photo view.
2. Click the folder icon top right and select an album.
3. Nothing happens.

Console shows an error:
`TypeError: callback is not a function
main.js:1764:12`

I did a bit of debugging and found, that when using the folder icon in photo view, the "callback" parameter of `contextmenu.move` is `null`, although it is set in the caller. As i'm not that familiar with JS, i have no clue where to look.

### Browser and system
Manjaro Linux and Firefox 65.0.1
Windows 8.1 and IE11

**Comment by ildyria** [comment]
Nicely spotted. :+1:
