### ISSUE TITLE
Default config.php file, containing database password, is readable by any uid

### ISSUE THREAD

**Issue by brad2014** [LycheeOrg/Lychee-v3#222]
### Detailed description of the problem
The data/config.php file is created with mode 0644, world readable, but it contains the db password secret.

It seems prudent to chmod it to 0640, so that random user processes on the server, if compromised, won't trivially compromise the database.

### Steps to reproduce the issue
Start browser on fresh installation, and save the database configuration.

**Comment by LudovicRousseau** [comment]
Good catch.
I also propose to add code in the Diagnostics results to report an error if the file is world-readable.
