### ISSUE TITLE
DigitalOcean Marketplace

### ISSUE THREAD

**Issue by kattti** [LycheeOrg/Lychee-v3#223]
What do you think of adding Lychee to the @digitalocean [marketplace](https://marketplace.digitalocean.com/category/all)?

**Comment by ildyria** [comment]
That could be interesting, however I don't have the time to prepare something like that.

**Comment by kattti** [comment]
Maybe @wadenick and @ryanpq can help?

**Comment by ildyria** [comment]
No news. clothing.
