### ISSUE TITLE
Issue after upload files

### ISSUE THREAD

**Issue by Wh00ps13** [LycheeOrg/Lychee-v3#224]
### Detailed description of the problem
![asdfas](https://user-images.githubusercontent.com/48535573/54320044-f31e6f80-45eb-11e9-8901-136620961931.png)
### Steps to reproduce the issue
Cloned the repo and runned comporsor install
### Output of the diagnostics (Settings => Diagnostics)
Error: Configuration not found. Please install Lychee for additional tests.
### Browser and system
Firefox, Linux Fedora 29

**Comment by ildyria** [comment]
Looks like some https problem.

**Comment by d7415** [comment]
Also check your folder [permissions](https://github.com/LycheeOrg/Lychee/wiki/Installation#4-permissions)

**Comment by Wh00ps13** [comment]
Permission are 775 in those folders.
It's running local under http.

**Comment by d7415** [comment]
Did you change the [.htaccess file](https://github.com/LycheeOrg/Lychee/wiki/Installation#12-https)?

**Comment by ildyria** [comment]
If you press `F12` you should see the console tab and the network tab. Do you see any errors there?

**Comment by Wh00ps13** [comment]
Damn, that .htaccess part I just missed thx @d7415. Problem is solved.
