### ISSUE TITLE
Inconsistent album overlay?

### ISSUE THREAD

**Issue by andyjohnson0** [LycheeOrg/Lychee-v3#225]
Hi. I'm new to Lychee and am running v3.2.13.

### Detailed description of the problem

I've noticed that when I'm logged-in to Lychee and am on the _Albums_ screen, each album box is overlayed with its title and the date range of the photos (e.g. "Hiking Trip May 2018 - June 2018"). This is what I want. But when I'm not logged-in, the album overlays show the title and the album _creation date_ (e.g "Hiking Trip February 2019"). 

I can't find a way to show the photo date range for non-logged-in users. Am I missing something, or is this a bug, or by design?

### Browser and system

Current Firefox and Chrome (Windows).

Thanks!

**Comment by d7415** [comment]
Thanks for pointing this out!
