### ISSUE TITLE
Allow specifying which photo to use as cover for album

### ISSUE THREAD

**Issue by sat3ll** [LycheeOrg/Lychee-v3#227]
It would be nice to be able to select a specific photo from the album to be the cover/thumbnail. (or maybe just upload a custom thumb).
Right now, a workaround is to Star one of the photos but I am not sure if the feature is intended to be used like that.

**Comment by kamil4** [comment]
Starring a photo in order to use it as the album's thumbnail is documented in the FAQ:

https://github.com/LycheeOrg/Lychee/wiki/FAQ

> How can I set thumbnails for my albums?
> 
> Thumbnails are chosen automatically by the photos you have starred and in the order you uploaded them. Star a photo inside an album to set it as a thumbnail.

So yeah, I would say it's intended to be used that way.
