### ISSUE TITLE
Nothing happens when trying to connect to database

### ISSUE THREAD

**Issue by wonx** [LycheeOrg/Lychee-v3#23]
### Detailed description of the problem

On a fresh install, following the instructions found in https://github.com/LycheeOrg/Lychee/blob/master/docs/Installation.md, I connect with my browser to the Lychee installation, and I am prompted to enter the database connection details. Nothing happens when I click on "Connect". No errors or warning messages.

### Steps to reproduce the issue

Install Lychee according to the instructions, enter the website to continue the configuration.

### Output of the diagnostics (Settings => Diagnostics)

I am not sure where to find that option...

### Browser and system

Debian 8.11
Firefox 61.0.2 (64 bits)
mysql 14.14 Distrib 5.5.60, for debian-linux-gnu (x86_64) using readline 6.3
Apache/2.4.10 (Debian)
PHP 5.6.36-0+deb8u1 (cli) (built: Jun 26 2018 17:31:29)

**Comment by ildyria** [comment]
On a side note, **please update your system**.
Debian stable is now version 9 (Stretch) and not 8 (Jessie). :/
You may also want to switch to php7...

Connect to your server with ssh.
```sh
mysql <database name> -u <database login>  -p [ENTER]
<enter your password>[ENTER]
```
You are now connected to your database. If this is not the case, then you have a problem.

Do the following then:
```
show tables;
```
This should display:
```
+------------------+
| Tables_in_lychee |
+------------------+
| lychee_albums    |
| lychee_log       |
| lychee_photos    |
| lychee_settings  |
+------------------+
```
Then if you do:
```
SELECT * FROM lychee_settings WHERE `key` = "version";
```
This should display:
```
+---------+--------+
| key     | value  |
+---------+--------+
| version | 030102 |
+---------+--------+
```
Version number may differ...

Does all this works?

**Comment by wonx** [comment]
Ok, I assumed that the database was created when you ran the Lychee "installer" for the first time (since it says "Lychee will create its own database.".

I can connect to my mysql server, and the lychee database is not there:

> 
> mysql> show databases;
> +--------------------+
> | Database           |
> +--------------------+
> | information_schema |
> | mysql              |
> | performance_schema |
> +--------------------+
> 3 rows in set (0.28 sec)


And yes, I have to update my whole system. I know...

**Comment by ildyria** [comment]
> Ok, I assumed that the database was created when you ran the Lychee "installer" for the first time (since it says "Lychee will create its own database.".

You assumed right. The code should have created the database. At least that is what I read in the code itself. If you have access to your database, you can directly execute the requests as in the `.sql` files here: https://github.com/LycheeOrg/Lychee/tree/master/php/database

You can also check if the `data/config.php` file exists.

**Comment by wonx** [comment]
Ok, I haven't used mysql for a long while.

I tried to manually create the database and the tables, but I think I've got something wrong.
```

mysql -u root -p
mysql> CREATE DATABASE lychee;
Query OK, 1 row affected (0.04 sec)
mysql> quit
Bye
root@box-media:/var/www/html/Lychee/php/database# mysql lychee -u root -p < albums_table.sql 
root@box-media:/var/www/html/Lychee/php/database# mysql lychee -u root -p < log_table.sql 
root@box-media:/var/www/html/Lychee/php/database# mysql lychee -u root -p < photos_table.sql 
root@box-media:/var/www/html/Lychee/php/database# mysql lychee -u root -p < settings_content.sql 
root@box-media:/var/www/html/Lychee/php/database# mysql lychee -u root -p < settings_table.sql 

root@box-media:/var/www/html/Lychee/php/database# mysql -u root -p
mysql> use lychee
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+------------------+
| Tables_in_lychee |
+------------------+
| ?                |
+------------------+
1 row in set (0.00 sec)

```
So something did not go well. I still think the web interface should return an error or something if it couldn't create the database for whatever reason.
I think I'm going to update my system to debian Stretch and try again later.

**Comment by wonx** [comment]
I am sorry, I forgot to answer your other question. The file data/config.php does not exist, and the folder is almost empty. 

```
root@box-media:/var/www/html/Lychee/data# ls -lia
total 12
391566 drwxrwxrwx  2 root root 4096 ago 21 16:15 .
257637 drwxr-xr-x 11 root root 4096 ago 21 16:15 ..
391567 -rwxr-xr-x  1 root root   70 ago 21 16:15 .gitignore

root@box-media:/var/www/html/Lychee/data# cat .gitignore 
#Ignore everything in this directory
*
#Except this file
!.gitignoreroot@box-media:/var/www/html/Lychee/data#
```
If I browse to Lychee/plugins/Diagnostics/index.php in firefox, I get the following message:

```
Diagnostics
-----------
Error: Configuration not found. Please install Lychee for additional tests

**Comment by wonx** [comment]
Btw, I upgraded to Debian Stretch. The problem persists.

Debian GNU/Linux 9 (stretch)
mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
Apache/2.4.25 (Debian)
PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )

**Comment by ildyria** [comment]
From a fresh Debian Stretch install...

Did you do:
```sh
apt install php-mysql php-mbstring php-gd php-zip imagemagick php-imagick
```
the last 2 are not mandatory but provide a nice addition.

Once done, you can connect to your database:
```sh
mysql -u root -p
<your password>
```
and create an additional user `lychee` that you will use with Lychee:
```sql
CREATE USER lychee@localhost IDENTIFIED BY 'password';
GRANT ALL ON *.* TO lychee@localhost WITH GRANT OPTION;
FLUSH PRIVILEGES;
```

Don't forget to change the access right
```bash
chown -R www-data:www-data *
chmod -R 744 data uploads
```

Don't forget to edit the `/var/www/html/Lychee/.htaccess` and uncomment:
```ApacheConf
<IfModule mod_php7.c>
	php_value max_execution_time 200
	php_value post_max_size 200M
	php_value upload_max_size 200M
	php_value upload_max_filesize 20M
	php_value max_file_uploads 100
</IfModule>
```

Lychee should be working properly.

Once the database has been created, you may want later to reduce the privileges of user `lychee`: remove his grant options and only have the right for: `SELECT, UPDATE, INSERT, DELETE`

```sql
revoke all privileges on *.* from 'lychee'@'localhost';
grant SELECT,INSERT,UPDATE,DELETE ON `lychee`.* TO 'lychee'@'localhost';
flush privileges;
```

All those steps got my installation working.

**Comment by wonx** [comment]
Damn it, I can install all packages without any problem, I can create the new user in mysql, change the ownserwhip of the lychee folder and edit the .htaccess file. But nothing changes. (I also restarted the apache server, just in case).

I recorded a screen capture of this issue, in case you want to see exactly what happens: https://imgur.com/a/byetzV4

Is there any logfile I can check for errors? I don't see anything relevant in the apache log.

Also, I will try to install lychee later in a raspberry pi I have lying around, to see if I get different results.

**Comment by ildyria** [comment]
If you are Firefox, you can press `F12` and go into the `Network` tab.
You shall see the connection to the server (AJAX request etc...)
Given that nothing happens in your case, I expect your server to have an error 500.

**Comment by wonx** [comment]
Solved!

It was a mix of issues. I first tried to install it in a raspberry pi, and it worked right away. 

Then I've been trying all components separately: the web server, php and mysql. It turns out there were some remaining configuration files from php5 which were interfering with php7. I uninstalled and purged everything, and now it works :)

Thank you for your patience

**Comment by ildyria** [comment]
Happy to hear. :)
