### ISSUE TITLE
Shutter speed requires "1/"

### ISSUE THREAD

**Issue by mh00h** [LycheeOrg/Lychee-v3#230]
### Detailed description of the problem
The shutter speed field in the database must start with "1/", else it chokes and refuse to display the image in a browser.

### Steps to reproduce the issue
change the db to have a value which does not start with "1/" to reproduce the issue.

### Output of the diagnostics (Settings => Diagnostics)
"unable to display image" (browser console)

### Browser and system
Firefox, Arch Linux

This is a justified need for long exposure photography.

**Comment by ildyria** [comment]
Err that cannot be the case. Lychee code has been tailored to actually not fail in those cases:
```php
if($photo['shutter'] != '' && substr($photo['shutter'], 0,2) != '1/') {
  // this should fix it... hopefully.
  preg_match('/(\d+)\/(\d+) s/', $photo['shutter'], $matches);
  $a = intval($matches[1]);
  $b = intval($matches[2]);
  $gcd = gcd($a,$b);
  $a = $a / $gcd;
  $b = $b / $gcd;
  if ($a == 1) {
    $photo['shutter'] = '1/'. $b . ' s';
  }
  else {
    $photo['shutter'] = ($a / $b) . ' s';
  }
}
if ($photo['shutter'] == '1/1 s') {
  $photo['shutter'] = '1 s';
}
```

**Comment by kid1000002000** [comment]
This logic breaks if it is already 1/x. Perhaps the else clause needs to also be duplicated up a level?

**Comment by mh00h** [comment]
This logic breaks if it is already 1/x. Perhaps the else clause needs to also be duplicated up a level?

**Comment by ildyria** [comment]
if it is already `1/x` then it does not needs to be checked. No ?

Also it should be `1/x s`.

**Comment by mh00h** [comment]
Do you have a link to where this code lives?

**Comment by ildyria** [comment]
you mean here: https://github.com/LycheeOrg/Lychee/blob/master/php/Modules/Photo.php#L833 ?

**Comment by mh00h** [comment]
Thanks.
When `shutter = "1 s"` what would `$b` equal?

**Comment by ildyria** [comment]
1 ? :smiley:

**Comment by mh00h** [comment]
Try this link. Toggle shutter speed between "1/1 s" to "1 s" to see the error: https://ideone.com/x322VY

**Comment by ildyria** [comment]
'1/1 s'  : https://ideone.com/m652kZ
No error.

**Comment by mh00h** [comment]
From @d7415 : "Exposure time and shutter speed are stored as a fraction (in the EXIF standard) - it actually calls for a numerator and a denominator." Closing as shutter lengths >1s can read "30/1 s"
