### ISSUE TITLE
[feature] Add skip dupplicates to the settings page

### ISSUE THREAD

**Issue by VictorLamoine** [LycheeOrg/Lychee-v3#232]
It would be nice to allow enabling/disabling the `skipDupplicate` value of the `lychee_settings` table through the Settings page.

Currently the easiest way I know to enable skipping duplicates is to execute a SQL query on the database: `UPDATE lychee_settings set `value`='1' where `key`='skipDuplicates'`

**Comment by d7415** [comment]
In the settings menu, click the red "More" button.

**Comment by VictorLamoine** [comment]
Didn't see that button! Thanks
