### ISSUE TITLE
Show complete Lens name in About Photo

### ISSUE THREAD

**Issue by sat3ll** [LycheeOrg/Lychee-v3#234]
### Detailed description of the problem
Instead of, for example, `24mm f/1.8`, it should show `AF-S Nikkor 24mm f/1.8G ED` (_ExifTool -LensID tag_) when using system ExifTool. 

### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Error: Upgrade to PHP 7.1 or higher


System Information
------------------
Lychee Version (json):  3.2.13
DB Version:             update_030213
System:                 Linux
PHP Version:            7
MySQL Version:          50505
Imagick:                1
Imagick Active:         1
Imagick Version:        1687
GD Version:             2.2.4
Plugins:                


Config Information
------------------
version:                 update_030213
checkForUpdates:         1
sortingPhotos:           ORDER BY id DESC
sortingAlbums:           ORDER BY id DESC
imagick:                 1
lang:                    en
skipDuplicates:          0
layout:                  0
image_overlay:           1
default_license:         reserved
small_max_width:         0
small_max_height:        360
medium_max_width:        1920
medium_max_height:       1080
deleteImported:          1
image_overlay_type:      desc
php_script_limit:        0
useExiftool:             1
```

### Browser and system
Firefox 66, x86_64 Linux

**Comment by mir07** [comment]
Unfortunately the LensID tag is only available in the RAW file and not in the JPEG file. Some minor improvement seems to be available in the LensSpec tag which is available in the JPEG file.
Example with ("LensID" => "Tamron SP AF 150-600mm f/5-6.3 VC USD (A011)"):
Lens: "Lens" => "150-600mm f/5-6.3"
LensSpec: "LensSpec" => "150-600mm f/5-6.3 G VR"

**Comment by sat3ll** [comment]
> Unfortunately the LensID tag is only available in the RAW file and not in the JPEG file.

Not necessarily. At least when exporting from _RawTherapee_ as JPEG, it preserves the **LensID** tag. If the exported _RawTherapee_ file (in either JPEG or TIF) is then edited with _GIMP_, this tag is lost (Error: `Warning: Can't decrypt Nikon information (no ShutterCount key)`).
In both cases the **LensSpec** tag is available. The logic for this could be to check first if **LensID** is available, falling back to **LensSpec** (or original behavior, **Lens**) if inaccessible.

**Comment by mir07** [comment]
Seems to be a bug in Darktable and Gimp (which share libraries with Darktable) so I have created a bug report: https://github.com/darktable-org/darktable/issues/2290
