### ISSUE TITLE
Have to put in password for every single photo?!

### ISSUE THREAD

**Issue by axellencyDE** [LycheeOrg/Lychee-v3#236]
Hi there,

I just installed Lychee. It all works fine as long as I don't use password protection for albums. When I want to open an album without being logged it, it asks me for the password - as expected. Then I see every photo in the album - as expected. When I click on a photo I need to put in the password again - NOT what I would expect. If I do and than go to the next or previous photo, it asks me again for the password - definitely not what I expected!

Is this a bug or is this a planned behaviour? Is there a way to change that?

Thx,
Axel

**Comment by ildyria** [comment]
No, this is not the behavior we want.
@kamil4 can you have a look? :stuck_out_tongue:

**Comment by d7415** [comment]
@axellencyDE Could you provide the other information requested in the issue template please?

##### Output of the diagnostics (Settings => Diagnostics)

##### Browser and system

**Comment by axellencyDE** [comment]
Sorry, here's the missing info:

## Diagnostics:

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version (json):  3.2.13
DB Version:             update_030213
System:                 Linux
PHP Version:            7.2
MySQL Version:          50638
Imagick:                1
Imagick Active:         1
Imagick Version:        1655
GD Version:             bundled (2.1.0 compatible)
Plugins:                


Config Information
------------------
version:                 update_030213
checkForUpdates:         1
sortingPhotos:           ORDER BY takestamp ASC
sortingAlbums:           ORDER BY max_takestamp DESC
imagick:                 1
lang:                    de
skipDuplicates:          0
layout:                  1
image_overlay:           0
default_license:         none
small_max_width:         0
small_max_height:        360
medium_max_width:        1920
medium_max_height:       1080
deleteImported:          1
image_overlay_type:      exif
php_script_limit:        0
useExiftool:             0

## Browser and system:

Google Chrome 73.0.3683.86 and Firefox 66.0.1 on Windows 10 Home with latest updates

**Comment by d7415** [comment]
Thanks. I'm still unable to reproduce. How did you install? Are you using `master` or `v3.2.13`?

**Comment by axellencyDE** [comment]
I've installed `v3.2.9` through automatic installation by my hosting provider. Then I did a manual update to `v3.2.13` by copying/overwriting all files/folders except `uploads/` and `data/`.

**Comment by d7415** [comment]
Messy, but I can't think how that would break it. I even tried 3.2.9's javascript with 3.2.13's back end (and vice-versa) and no issues.

**Comment by kamil4** [comment]
I checked it on git master of Lychee and Lychee-front and I can't reproduce it either.

@axellencyDE irrespective of this problem, updating to the git master Lychee v4 (https://github.com/LycheeOrg/Lychee-Laravel, currently in alpha) should make password-protected albums work better though. There's extra code in the new version to ensure that album passwords are only asked for once. In v3, if you exit an album and then attempt to re-enter it, you will be asked for the password again... In v4, such credentials are cached server-side for the duration of the session. I can't explain why in your case you get asked even more frequently than that though...

**Comment by axellencyDE** [comment]
Oh man, I am embarassed ... turns out, deleting the passwords saved by the browser did the trick. Apparently, since I had been logged in before with the admin account and saved these credentials, Lychee tried to use that password instead of the one I assigned to the album(s).

Thanks for your effort!

**Comment by d7415** [comment]
Thanks for letting us know. Hopefully it'll help the next person!
