### ISSUE TITLE
Feature request: Move title to config

### ISSUE THREAD

**Issue by Eupeodes** [LycheeOrg/Lychee-v3#239]
The title in the html title element is currently hardcoded as Lychee. Because of this I have to rollback my title edit on every update and change the title back after the update again.

The title could go in a variable (e.g. $winTitle) in config.php, if index.html becomes index.php, with an include of config.php and `<title><?=$winTitle ?? 'Lychee'?></title>` my problem would be solved.

**Comment by d7415** [comment]
As a workaround, you may wish to look at committing your change locally and letting git handle the rest. Git is very good at managing local changes against changes from upstream.

**Comment by ildyria** [comment]
By the way. this has already been done in the v4. :)
