### ISSUE TITLE
Installation notes still say clone from electerious

### ISSUE THREAD

**Issue by RedFlames** [LycheeOrg/Lychee-v3#24]
Hi,

**docs/Installation.md** notes still says
`git clone https://github.com/electerious/Lychee.git`
when it should reference this `LycheeOrg` repo, right?

**Comment by ildyria** [comment]
That is right. But it seems to me that this project is dying **again**. :(

**Comment by haivala** [comment]
@fly-man- is it dying?

**Comment by LudovicRousseau** [comment]
No, the project is not dying.
