### ISSUE TITLE
Photos not appearing when thumbnail clicked

### ISSUE THREAD

**Issue by corrilan** [LycheeOrg/Lychee-v3#240]
### Detailed description of the problem

I am running the latest version of Lychee (3.2.14)
I have 6 albums at https://jason-and-lynsey.com

2 of the albums are having an issue when the thumbnails are clicked.  They used to work:
https://jason-and-lynsey.com/#15456717649826
https://jason-and-lynsey.com/#15443063109364

### Steps to reproduce the issue

Click a thumbnail in either of the two troublesome albums.

I would expect a larger version of the photo to appear, instead I get a message at the top of the screen stating:  "Error:  Server error or API not found".

My Apache server logs show the following:

==> /var/log/apache2/www.jason-and-lynsey.com_error_log <==
[Fri Mar 29 18:36:39.422454 2019] [php7:notice] [pid 19910] [client 86.140.128.0:50468] PHP Notice:  Undefined offset: 1 in /var/www/customersites/www.jason-and-lynsey.com/Lychee/php/Modules/Photo.php on line 837, referer: https://jason-and-lynsey.com/
[Fri Mar 29 18:36:39.422723 2019] [php7:notice] [pid 19910] [client 86.140.128.0:50468] PHP Notice:  Undefined offset: 2 in /var/www/customersites/www.jason-and-lynsey.com/Lychee/php/Modules/Photo.php on line 838, referer: https://jason-and-lynsey.com/
[Fri Mar 29 18:36:39.422983 2019] [php7:error] [pid 19910] [client 86.140.128.0:50468] PHP Fatal error:  Uncaught DivisionByZeroError: Modulo by zero in /var/www/customersites/www.jason-and-lynsey.com/Lychee/php/helpers/gcd.php:4\nStack trace:\n#0 /var/www/customersites/www.jason-and-lynsey.com/Lychee/php/Modules/Photo.php(839): gcd(0, 0)\n#1 /var/www/customersites/www.jason-and-lynsey.com/Lychee/php/Modules/Photo.php(942): Lychee\\Modules\\Photo::prepareData(Array)\n#2 /var/www/customersites/www.jason-and-lynsey.com/Lychee/php/Access/Admin.php(171): Lychee\\Modules\\Photo->get('15456717649826')\n#3 /var/www/customersites/www.jason-and-lynsey.com/Lychee/php/Access/Admin.php(35): Lychee\\Access\\Admin::getPhotoAction()\n#4 /var/www/customersites/www.jason-and-lynsey.com/Lychee/php/index.php(83): Lychee\\Access\\Admin::init('Photo::get')\n#5 {main}\n  thrown in /var/www/customersites/www.jason-and-lynsey.com/Lychee/php/helpers/gcd.php on line 4, referer: https://jason-and-lynsey.com/

==> /var/log/apache2/www.jason-and-lynsey.com_access_log_themount <==
86.140.128.0 - - [29/Mar/2019:18:36:39 +0000] "POST /php/index.php HTTP/1.1" 500 476 "https://jason-and-lynsey.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36"

### Output of the diagnostics (Settings => Diagnostics)

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Error: PHP gd extension not activated
Error: PHP zip extension not activated
Warning: 'dist/user.css' does not exist or has insufficient read/write privileges.
Warning: 'dist/' has insufficient read/write privileges.
Error: 'data/config.php' is world readable.

System Information
------------------
Lychee Version (json):  3.2.6
Lychee Version (git):   b92a8a49c8287c8bad28895b4a510683145e2d8d		branch 'master' of https://github.com/LycheeOrg/Lychee
DB Version:             update_030214
System:                 Linux
PHP Version:            7.2
MySQL Version:          50725
Imagick:                1
Imagick Active:         1
Imagick Version:        1673
GD Version:             -
Plugins:                

Config Information
------------------
checkForUpdates:         1
default_license:         reserved
deleteImported:          1
full_photo:              1
image_overlay:           0
image_overlay_type:      exif
imagick:                 1
lang:                    en
layout:                  0
medium_max_height:       1080
medium_max_width:        1920
php_script_limit:        0
skipDuplicates:          0
small_max_height:        360
small_max_width:         0
sortingAlbums:           ORDER BY id DESC
sortingPhotos:           ORDER BY title DESC
useExiftool:             0
version:                 update_030214

### Browser and system

I am accessing the remote Lychee server using Mozilla Firefox and Google Chrome on Ubuntu Linux.
Lychee server is running on Ubuntu Linux/Apache.

**Comment by d7415** [comment]
The problem appears to be with the shutter speed. Are you able to check the shutter speed for one of those photos? From mysql, that would be something like `select shutter from lychee_photos where album=15456717649826;`

**Comment by d7415** [comment]
Aside, but related: How are you uploading your photos to Lychee?

**Comment by d7415** [comment]
> Aside, but related: How are you uploading your photos to Lychee?

Ah, judging by #241 probably using lycheeupload, which is probably causing the problem. I keep thinking about making that part of the code more forgiving, but it's hard to justify when it works with the format generated when uploading using Lychee itself. If I have time I might look at doing a quick-fix tomorrow.

Longer term, if I ever finish my "cronnable import from server" side project, this may be avoidable that way.

**Comment by corrilan** [comment]
Hello,

Yes I am using lycheeupload.

It turns out those photos were taken on a Raspberry Pi 3 camera and exiftool shows shutter speed as 1/15.

The working photos were taken on a different USB webcam.  The shutter speed as reported by exiftool though is the same as the non working photos, 1/15.

It seems odd that all photos were working fine last time I opened them.  Since last opening the non working photos I have upgraded the system to a newer version, both Lychee and the general Ubuntu system using apt-get upgrade and dist-upgrade.

**Comment by corrilan** [comment]
The non working album:

mysql> select shutter from lychee.lychee_photos where album=15456717649826;
+------------------+
| shutter          |
+------------------+
| (66570, 1000000) |
| (66570, 1000000) |
| (66570, 1000000) |
| (66570, 1000000) |
| (66570, 1000000) |
| (66570, 1000000) |
+------------------+
6 rows in set (0.00 sec)

And a working album (truncated as it just shows the same empty row 216 times):

mysql> select shutter from lychee.lychee_photos where album=15486036679244;
+---------+
| shutter |
+---------+
|         |
|         |
|         |
|         |
+---------+
216 rows in set (0.01 sec)

**Comment by d7415** [comment]
I suspect that shutter speed code was added since your old Lychee version.

The missing shutter speed is why the working album works. For the broken one I was expecting decimals - that's a very weird format; I suspect `(numerator, denominator)`.

Either way I'll try to find time to make it more forgiving (ignoring bad shutter values) later.

**Comment by corrilan** [comment]
In the mean time, I assume I can delete the shutter values in the database to force it to work?

**Comment by d7415** [comment]
Sorry, I nearly said. Yes, if you delete the shutter values it should all work (apart from the shutter speed)

**Comment by corrilan** [comment]
Yep that got it working, thanks again for your assistance.
