### ISSUE TITLE
Here is my magic mirror photo and video booth code for anyone interested

### ISSUE THREAD

**Issue by corrilan** [LycheeOrg/Lychee-v3#241]
Hello

Thought this may be of use to someone wanting to do a similar project.

May be worth placing a link to this around the plugins/extensions area on the main Lychee page.

I have uploaded the Python code (and soon other useful scripts) for a magic mirror photo and video booth I created for my recent wedding to Github:

https://github.com/corrilan/Magic-Mirror-Photo-and-Video-Booth

I have made use of Lychee and lycheeupload to create the booth.

I will update Github with photos and videos of the booth in action.  Once it has been returned from a friend who is going to use it for an upcoming Christening.

Thanks for all your hard work on Lychee!

**Comment by ildyria** [comment]
@corrilan you might be interested in updating to the latest version of Lychee as it provide the sync options etc. :)
