### ISSUE TITLE
Does lychee have api settings？

### ISSUE THREAD

**Issue by boeto** [LycheeOrg/Lychee-v3#246]
Does lychee have api settings, like "sm.ms" can connect to third parties

**Comment by ildyria** [comment]
https://github.com/LycheeOrg/Lychee-front/blob/master/API.md does this help ?

**Comment by ildyria** [comment]
@pourley shall I close this ?

**Comment by Naielc** [comment]
Found the reason, only the config.php file has been changed user group when unzip.

**Comment by ildyria** [comment]
Looks like it.
