### ISSUE TITLE
Warning: 'dist/user.css' does not exist or has insufficient read/write privileges.

### ISSUE THREAD

**Issue by bigfoot50** [LycheeOrg/Lychee-v3#247]
Hi,
after uprade to the new version I have this error message:
Lychee still works, but only with this warning.

Warning: 'dist/user.css' does not exist or has insufficient read/write privileges.

System Information
------------------
Lychee Version (json):  3.2.14
Lychee Version (git):   b5272e8 (master)
DB Version:             update_030214
System:                 Linux
PHP Version:            7.2
MySQL Version:          50560
Imagick:                1
Imagick Active:         1
Imagick Version:        1690
GD Version:             2.2.5
Plugins:

**Comment by d7415** [comment]
Hi. Please check your [permissions](https://github.com/LycheeOrg/Lychee/wiki/Installation#4-permissions).

**Comment by bigfoot50** [comment]
makes more errors

Warning: 'dist/user.css' does not exist or has insufficient read/write privileges.
Error: 'data/config.php' is world readable.
Error: 'data/config.php' is world executable.

but there is no "user.css" file inside the folder

-rwxr-xr-x. 1 apache apache  63820 13. Apr 18:06 main.css
-rw-r--r--. 1 apache apache 348065 13. Apr 18:06 main.js
-rw-r--r--. 1 apache apache   7910 13. Apr 18:06 play-icon.png
-rw-r--r--. 1 apache apache 151232 13. Apr 18:06 view.js

strange....

**Comment by bigfoot50** [comment]
ahhh....

is there a different between 
git clone --recurse-submodules https://github.com/LycheeOrg/Lychee.git

an the .zip file for download?
Inside the .zip file there a file called user.css

**Comment by ildyria** [comment]
@bigfoot50 yep, but you can just create the `user.css` by yourself.
`touch dist/user.css`
:)
By the way, you may want to do `chmod 750 data/config.php`.

Anyway this issue has been solved on the v4 so I'm closing this issue. :)

**Comment by ildyria** [comment]
I updated the wiki to reflect that change.
