### ISSUE TITLE
Directory relocation + domain name change

### ISSUE THREAD

**Issue by Naielc** [LycheeOrg/Lychee-v3#249]
When directory location change + domain name change and access is made {System error or API not found}, except config.php, what i need to change.

**Comment by ildyria** [comment]
It is unclear to me what you are trying to do.

The request are done to `php/index.php` make sure this one is accessible.

**Comment by Naielc** [comment]
After changing the domain name, the index.php file is accessible and showing the service API error.

**Comment by ildyria** [comment]
If you press F12 in your browser to look at the network connections when you load the site, what is the error that you get?

**Comment by Naielc** [comment]
{description: "Server error or API not found.", params: {…}, response: SyntaxError: Unexpected token < in JSON at position 0
    at parse (<anonymous>)

**Comment by ildyria** [comment]
I meant here:
![here](https://user-images.githubusercontent.com/627094/56573357-3099f380-65c1-11e9-8645-629f58956aa1.png)

Also if it says unexpected token "<" it looks like to me that this is the beginning of the php code: "<?php". Which would mean that your php is NOT executed.

**Comment by Naielc** [comment]
![1](https://user-images.githubusercontent.com/32182694/56573941-77a9d800-6605-11e9-8f96-e2a701ad9bf0.jpg)
![2](https://user-images.githubusercontent.com/32182694/56573948-78db0500-6605-11e9-9a3a-5fb465cec1f6.jpg)

**Comment by ildyria** [comment]
Well it look likes to me that on the Lychee code side every thing is working properly. What is not working is your server. Are you sure your server user (most likely `www-data`) has access to `data/config.php` ?

**Comment by Naielc** [comment]
No, can't. 403 access denied. what reason ? database need to change some thing?

**Comment by d7415** [comment]
> No, can't. 403 access denied. what reason ? database need to change some thing?

Not database. Your web server doesn't have access to `data/config.php`. Check the permissions/ownership on that file and the directories above it.

**Comment by ildyria** [comment]
it is not related to the database but your server user. you need to allow it to run the script.
https://stackoverflow.com/questions/33927463/require-once-failed-to-open-stream-permission-deniedlampp

**Comment by Naielc** [comment]
Found the reason, only the config.php file has been changed user group when unzip.
