### ISSUE TITLE
Help/Feature Request - Import/Reference local files

### ISSUE THREAD

**Issue by Optimaximal** [LycheeOrg/Lychee-v3#250]
We have a large amount of assets on our Synology NAS - I was considering installing Lychee on the onboard Web Server (assuming I could add all the pre-reqs) and then either import them from the NAS local storage or simply hard link/reference the files in their existing folders.

Is this something that is do-able?

**Comment by d7415** [comment]
Importing from the server is possible - there's an `Import from Server` option where you can select a path (NB: the www user will need read access, and by default it will delete the originals! See [Settings](https://github.com/LycheeOrg/Lychee/wiki/Settings)).

If you don't delete the originals, they will be duplicated. Lychee's file structure doesn't reflect albums, so where I use this I accept the duplication.

**Comment by ildyria** [comment]
I think this has been answered.
