### ISSUE TITLE
"Error: No API function specified!" thrown when uploading a video

### ISSUE THREAD

**Issue by waynia** [LycheeOrg/Lychee-v3#251]
Hello, I met a problem as the title of this issue said. 

I had followed the instruction to install php-ffmpeg and checked the existence of ffmpeg tool in my unix system. Still this problem occured, how could I fix it? Thanks~

**Comment by ildyria** [comment]
I am not using this functionality of Lychee, maybe @clementlamoureux can help you.

**Comment by jprokop1** [comment]
I had a similar problem with video upload (Linux/nginx), by me helped set the path to ffmpeg/ffprobe binary in nginx conf:
```conf
location ~ \.php$ {
    ...;
    fastcgi_param PATH /usr/local/bin:/usr/bin:/bin:/your/path;
	...;
}
```
you can check your enviroment with testfile.php:
```php
<?php  
var_dump(getenv('PATH'));
  var_dump(exec('which ffmpeg'));
  var_dump(exec('which ffprobe'));
  var_dump(ini_get('open_basedir'));
  var_dump(is_file(exec('which ffmpeg')));
  var_dump(is_executable(exec('which ffmpeg')));
?>
```

**Comment by waynia** [comment]
> I had a similar problem with video upload (Linux/nginx), by me helped set the path to ffmpeg/ffprobe binary in nginx conf:
> location ~ .php$ {
> ...;
> fastcgi_param PATH /usr/local/bin:/usr/bin:/bin:/your/path;
> ...;
> }
> you can check your enviroment with testfile.php:
> `<?php var_dump(getenv('PATH')); var_dump(exec('which ffmpeg')); var_dump(exec('which ffprobe')); var_dump(ini_get('open_basedir')); var_dump(is_file(exec('which ffmpeg'))); var_dump(is_executable(exec('which ffmpeg'))); ?> `

Thanks for your reply~ 
I added the PATH variable into the conf file of nginx, and used the testfile.php to check if the PATH variable was recognized, and, yes, the php page showed the path string specified in conf file, however, the same error still occuredd in the console...

**Comment by ildyria** [comment]
Can you press F12 and look in the network tab what is the response of the server ?
https://github.com/LycheeOrg/Lychee/wiki/I-have-an-Error-500-what-can-I-do

Though it is weird that you get this kind of error. Please also verify that the format is supported:
```php
	public static $validVideoTypes = array(
		"video/mp4",
		"video/ogg",
		"video/webm",
		"video/quicktime"
    );
```

**Comment by purerstamp** [comment]
I have the same problem and there's no error 500 in response. Both PHP FPM and NGINX reply with a 200. And in fact, in my case, it only occurs with a MP4 file in particular, not all. This file is 118MB (the bigger one I've upload without any problem is 100MB). The problem is not _upload_max_filesize_ in _php.ini_.

![Capture d’écran 2019-07-14 à 17 13 00](https://user-images.githubusercontent.com/17382504/61185519-b4142f80-a65a-11e9-8147-3a5809ec6fec.png)

**Comment by d7415** [comment]
> This file is 118MB (the bigger one I've upload without any problem is 100MB). 

Do you have any other videos available to check that it is size dependent?

**Comment by purerstamp** [comment]
That's what I was looking for but I don't have it so I'll make videos that size asap and let you know.

**Comment by klodzack** [comment]
I have the same issue.
Uploaded many videos fine, up to 303MB.
The only one that failed is the largest one, 708MB.
Apache upload_max_filesize is 1024MB.
All files are .mov.

**Comment by kamil4** [comment]
Can you put the video files that cause problems somewhere where we can download them to try and reproduce the problem on our end? Thanks!

**Comment by d7415** [comment]
From the different sizes (but the implication of a size issue) I'm thinking maybe timings. PHP's execution time limits might be a good place to start, but I can't look them up (or test them) myself right now.

**Comment by purerstamp** [comment]
@kamil4 you can find the video causing the problem here [https://the-redunicorn.fr/large-vid.mp4](https://the-redunicorn.fr/large-vid.mp4).
@d7415 Are max_input_time and/or max_execution_time what you are thinking? I gonna try right now.

**Comment by purerstamp** [comment]
@d7415 My max_execution_time is 200s. My max_input_time is now 120s (instead of 60). At the end of the upload (less than 2 min after the begining) the same error occured. The other timer I found is default_socket_timeout but still got this error.

**Comment by kamil4** [comment]
I tried your video and it uploaded without problems for me. I'm using the default values in `php.ini`, although at least with Apache I believe Lychee will use the values from its own `.htaccess` file, which are:

```
        php_value max_execution_time 200
        php_value post_max_size 500M
        php_value upload_max_filesize 500M
        php_value max_file_uploads 100
```

I was uploading over a very fast link (I'm at work right now :smiley:) so transfer time wouldn't have been a problem in my case as it took only a few seconds.

**Comment by purerstamp** [comment]
@kamil4 Oh yes of course, I've totally omitted `post_max_size` and that was my problem. I use NGINX so I just modified `php.ini`. So I think it would be a good idea to better document PHP limits belonging to file uploads for people who don't know much on PHP or just people like me with head in the clouds :°

**Comment by d7415** [comment]
> So I think it would be a good idea to better document PHP limits belonging to file uploads for people who don't know much on PHP or just people like me with head in the clouds :°

Like [this](https://github.com/LycheeOrg/Lychee-Laravel/wiki/Install#72-php)? :wink:

**Comment by purerstamp** [comment]
@d7415 Oh I had a look on the wrong part of the documentation.. definitely head in the clouds, sorry 😅
Thanks for your kind support.
