### ISSUE TITLE
Failed MySql Connection message should be clearer

### ISSUE THREAD

**Issue by lbrunjes** [LycheeOrg/Lychee-v3#254]
### MySql connection errors not clear
If Lychee fails to connect top MySql it will simply parrot the error message from mysqli with no changes. The default error is file not found. It is not clear that this is a database error. No other functionality will exist. It took me a while to figure out what was happening and ultimately I ended up adding random echo()s to things until the error showed up calling a database function.

I would suggest changing line 90 of php/Modules/Database.php to include The phrase 'Database Connection Error: ' 

```
private static function connect_error() {
		return 'Database Connection Error: ' . mysqli_connect_error();
	}
```
https://github.com/LycheeOrg/Lychee/blob/master/php/Modules/Database.php#L90

This didnt seem worthy of a pull request, but I can create one if needed

### Steps to reproduce the issue

1. After install or during normal usage, stop mysqld (sudo service mysql stop)
2. The main page will the simply read: File Not found. 

### Output of the diagnostics (Settings => Diagnostics)

Diagnostics
-----------
"Error: No such file or directory"

### Browser and system
Various ubuntu flavors  and chromium.

![Screenshot_2019-05-03_08-19-19](https://user-images.githubusercontent.com/942037/57136968-705c9a00-6d7c-11e9-9df1-ad85d1538fc5.png)

**Comment by ildyria** [comment]
Fixed.
