### ISSUE TITLE
"Server error or API not found" when trying to search

### ISSUE THREAD

**Issue by morbificagent** [LycheeOrg/Lychee-v3#255]
### Detailed description of the problem

Entering a search term into the box on top leads to ""Server error or API not found" message and the search doesnt work.

### Output of the diagnostics (Settings => Diagnostics)

```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Error: 'data/config.php' is world readable.
Error: 'data/config.php' is world writable.


System Information
------------------
<br />
<b>Warning</b>:  file_get_contents(W:\htdocs\Lychee-front/package.json): failed to open stream: No such file or directory in <b>W:\htdocs\plugins\Diagnostics\index.php</b> on line <b>130</b><br />
W:\htdocs\Lychee-front/package.json not found. Please do: git submodule init ; git submodule update
Lychee Version (git):   No git data found. Probably installed from release.
DB Version:             update_030214
System:                 WINNT
PHP Version:            7.3
MySQL Version:          50505
Imagick:                1
Imagick Active:         1
Imagick Version:        1799
GD Version:             bundled (2.1.0 compatible)
Plugins:                


Config Information
------------------
checkForUpdates:         1
default_license:         none
deleteImported:          1
full_photo:              1
image_overlay:           0
image_overlay_type:      desc
imagick:                 1
lang:                    de
layout:                  0
medium_max_height:       1080
medium_max_width:        1920
php_script_limit:        0
skipDuplicates:          0
small_max_height:        360
small_max_width:         0
sortingAlbums:           ORDER BY title DESC
sortingPhotos:           ORDER BY takestamp DESC
useExiftool:             0
version:                 update_030214
```

### Browser and system

Win10 with xampp
![Unbenannt](https://user-images.githubusercontent.com/50199132/57145691-0d8ef100-6dc4-11e9-9f9a-4f8d43b1a5b9.JPG)

**Comment by ildyria** [comment]
Can you please press F12, and look at what the console says, look at what the network tab says. Redo a search and see what kind of error the search query is giving you. In the case of an error 500, please have a look here:
https://github.com/LycheeOrg/Lychee/wiki/I-have-an-Error-500-what-can-I-do

**Comment by morbificagent** [comment]
Hope this is what you wanted to have:

![grafik](https://user-images.githubusercontent.com/50199132/57146438-96f2f300-6dc5-11e9-9cd4-3ae4eae5b951.png)

**Comment by ildyria** [comment]
If you go to "Networkanalyse" and look at the answer of the search request, what is it you get ?

**Comment by kamil4** [comment]
I had no idea that Lychee server works on Windows NT.  The things you learn... :smiley:

**Comment by morbificagent** [comment]
> 
> 
> If you go to "Networkanalyse" and look at the answer of the search request, what is it you get ?

![grafik](https://user-images.githubusercontent.com/50199132/57148880-d243f080-6dca-11e9-91a6-65b6f827d813.png)

**Comment by morbificagent** [comment]
> 
> 
> I had no idea that Lychee server works on Windows NT. The things you learn... 😃

Works great ;-)

**Comment by lbrunjes** [comment]
I ran into this last night, typically it appears to happen if you get a malformed JSON response from the backend. In my case, I left a debug echo in and it was getting attached to the JSON and making javascript unable to parse it. Looks like in your case it may be the notices in the  the second screenshot that are breaking the JSON output.

**Comment by d7415** [comment]
> I ran into this last night, typically it appears to happen if you get a malformed JSON response from the backend. In my case, I left a debug echo in and it was getting attached to the JSON and making javascript unable to parse it. Looks like in your case it may be the notices in the the second screenshot that are breaking the JSON output.

That certainly sounds plausible. Most sane PHP installations turn notices off by default, so I'm not surprised this hasn't come up before.

@morbificagent I'd suggest you look at `display_errors` and `error_reporting` in your `php.ini`. That said, I'm not convinced this should be triggering in the first place...

**Comment by morbificagent** [comment]
That was it!

Changed display_errors to off and its working.

Many thanks for your help guys and have a nice weekend!
