### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by Sk3yNet** [LycheeOrg/Lychee-v3#263]
I'm not sure if it is possible to run Lychee on a Windows server. Please let me know if I am way off base with this one.

I have a working PHP7.3.5/Apache2.4/MySQL Server on Windows. I get the connection dialog when I open the site in Firefox but after entering connection info & clicking 'connect' I get a "Server Error or API not found".

On running: Diagnostics\index.php
PHP Warning:  fileperms(): stat failed for D:\Apache24\htdocs\Lychee\data/config.php in D:\Apache24\htdocs\Lychee\plugins\Diagnostics\index.php on line 61
Error: Configuration not found. Please install Lychee for additional tests.

Lychee\data\config.php does not exist so I suspect a failed install.

On re-running Composer Install:
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

I have yet to implement ssl on the site but doubt that is the issue at this point.
phpinfo() gives a lot of info

Any help you can provide would be greatly appreciated!

**Comment by kamil4** [comment]
If you check issue #255, the reporter used it on Windows with some success, so it's certainly possible, though I don't think that any of the developers regularly test it on that platform...

**Comment by Sk3yNet** [comment]
Thank you for the reply. This is a dual boot machine so I also tried installing on a Debian OS, oddly I had the same result.

**Comment by kamil4** [comment]
Just to confirm, on Debian you're also getting "Server Error or API not found" when you click "Connect" in the initial dialog? Do you have all the required php extensions installed?

**Comment by Sk3yNet** [comment]
Debian: No, I just did the debian install to see if I get a config.php.

Windows:
I confirmed on the Windows install that I have session, exif, mbstring, gd, mysqli, json & zip running through phpinfo(). At the time of my op I was getting the log in dialog but that has since stopped. The firefox console gives the following error on opening the page & no log in dialog appears.
    
![image](https://user-images.githubusercontent.com/51216623/59148141-e59e3900-89d2-11e9-8b4d-25c99c6c0e78.png)

**Comment by ildyria** [comment]
can you look at the response that you get in the network tab ? 
It is most likely something like `<?php` or a warning.

**Comment by Sk3yNet** [comment]
Thank you for your response. I did the dumb & was opening the index.html as a local document rather than through the host. I now have the log-in dialog back & I am back to my op issue.

Current status:
Trying to log in for the first time I get the log in dialog but a "Server Error or API not found" when I click connect.

Looking at the network tab I have a 404 error for user.css

plugins/Diagnostics/index.php:
Diagnostics
-----------
<br />
<b>Warning</b>:  fileperms(): stat failed for D:\Apache24\htdocs\Lychee\data/config.php in <b>D:\Apache24\htdocs\Lychee\plugins\Diagnostics\index.php</b> on line <b>61</b><br />
Error: Configuration not found. Please install Lychee for additional tests.

php/index.php?fn=phpinfo:
"Error: No API function specified!"

/phpinfo.php?fn=phpinfo
Lots of info

Thanks again for any direction you can provide!

**Comment by ildyria** [comment]
> Looking at the network tab I have a 404 error for user.css

that's fine.

Can you create a file `config.php` in the `data` folder.
The content of `config.php` should be:
```php
<?php

// Database configuration
$dbHost = 'TO FILL'; // Host of the database
$dbUser = 'TO FILL'; // Username of the database
$dbPassword = 'TO FILL'; // Password of the database
$dbName = 'TO FILL'; // Database name
$dbTablePrefix = 'TO FILL'; // Table prefix
```

**Comment by Sk3yNet** [comment]
Done. I no longer get the login dialog but I still get the error.

'Diagnostics
-----------
<br />
<b>Fatal error</b>:  Uncaught Error: Class 'Mysqli' not found in D:\Apache24\htdocs\Lychee\plugins\Diagnostics\index.php:80
Stack trace:
#0 {main}
  thrown in <b>D:\Apache24\htdocs\Lychee\plugins\Diagnostics\index.php</b> on line <b>80</b><br />`

**Comment by ildyria** [comment]
haaaa now we are going somewhere. Well you need to install the mysql dependencies. :)

**Comment by Sk3yNet** [comment]
I'm sorry, I don't know what those are. I have MySQL installed & running, what are the dependencies & where do they go?

If you mean the PHP extensions: session, exif, mbstring, gd, mysqli, json, zip. I believe I have them.

**Comment by ildyria** [comment]
Well it clearly says that mysqli is not enabled in your `php.ini` for apache:

> `Fatal error: Uncaught Error: Class 'Mysqli' not found`

**Comment by Sk3yNet** [comment]
I confirmed that mysqli is not commented out in my php.ini

"extension=mbstring
extension=exif      ; Must be after mbstring as it depends on it
extension=mysqli"

Also I confirmed through a command line
C:\Users\User\Desktop>php -m
[PHP Modules]
bcmath
calendar
Core
ctype
date
dom
exif
fileinfo
filter
gd
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
Phar
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
zip
zlib

And tested using a php script & got a connection confirmation:
```
<?php
$mysqli = new mysqli("localhost", "user", "pass", "schema");

/* check connection */
if ($mysqli->connect_errno) {
    printf("Connect failed: %s\n", $mysqli->connect_error);
    exit();
}

/* check if server is alive */
if ($mysqli->ping()) {
    printf ("Our connection is ok!\n");
} else {
    printf ("Error: %s\n", $mysqli->error);
}

/* close connection */
$mysqli->close();
?>
```

Please let me know what I can check as I am still doing something wrong. :(

**Comment by ildyria** [comment]
The thing is that your apache php.ini and your cli php.ini are not the same. When you execute a php file directly on via the command line it will use the cli php.ini instead of the apache one.

did you try accessing the php script you created via your server ?

**Comment by ildyria** [comment]
maybe related: https://stackoverflow.com/questions/38406871/php-7-cannot-find-mysqli

**Comment by Sk3yNet** [comment]
You are correct! Running through apache the command fails while cli worked. As mentioned in the link you provided I had an incorrect PHPIniDir in my apache httpd.conf!!! You are the best, thank you @ildyria & @kamil4. I am up & running now.
