### ISSUE TITLE
Design: possible to separate admin login page?

### ISSUE THREAD

**Issue by wayneyaoo** [LycheeOrg/Lychee-v3#269]
### Detailed description of the problem

It's a design problem rather than a bug. Some of my friends may ask "how can I register?" because they find the tiny button on the upper left corner, which is the admin login page. Is it possible to separate the login page to some other routings like `https://lychee.bla/login`, or even better,  a customizable routing? It's also a bit like... security improvement because the first thing I can think of when I found the demo is that "wow login page? Can i register? ... no ... then it must be admin's home. Can I inject it? :p".

Yeah It's not big deal. It doesn't really matter if the params are escaped properly. I'd like to help but PHP is not my type.

**Comment by d7415** [comment]
This is possible, but:
 - it would be a lot of effort
 - this version of Lychee is not being actively developed while we plan the transition to [v4](https://github.com/LycheeOrg/Lychee-Laravel)
 - as standard software, a (very) quick search would find the login page anyway, or at least the end point

**Comment by ildyria** [comment]
> Yeah It's not big deal. It doesn't really matter if the params are escaped properly. I'd like to help but PHP is not my type.

@wx-Yao the parameters to log as admin (username and password) are both hashed with bcrypt. no worries. :)
