### ISSUE TITLE
API Call: Description missing

### ISSUE THREAD

**Issue by kenokenobingo** [LycheeOrg/Lychee-v3#270]
I’m programming a custom front-end for the Lychee API. I got the images and their titles by calling `Album::get`, but I also want to include the description. The curious thing is that I included a description (which I can also see in the standard Lychee front-end and in the MySQL database), but it’s not included in the resposne from the API.

The standard interface:

![Lychee front-end](https://i.imgur.com/8iO0GVa.png)

The response I get when calling the API:

```
{
  "id": "15598273921978",
  "title": "Trump hugging American flag",
  "description": "",
  "tags": "trump,alt-right",
  "public": "0",
  "star": "0",
  "album": "15598142810611",
  "size": "1013.7 KB",
  "type": "image/jpeg",
  "width": "3500",
  "height": "2333",
  "shutter": "",
  "make": "",
  "model": "",
  "iso": "",
  "aperture": "",
  "focal": "",
  "lens": "",
  "license": "CC0",
  "medium": "uploads/medium/e913300a3c8ff4491d402a669a60725b.jpg",
  "small": "uploads/small/e913300a3c8ff4491d402a669a60725b.jpg",
  "thumbUrl": "uploads/thumb/e913300a3c8ff4491d402a669a60725b.jpeg",
  "url": "uploads/big/e913300a3c8ff4491d402a669a60725b.jpg",
  "cameraDate": "0",
  "sysdate": "06 June 2019",
  "takedate": "",
  "previousPhoto": "15599063846383",
  "nextPhoto": "15617459937793"
}
```

Do you have any idea what is wrong or what I am doing wrong?

**Comment by ildyria** [comment]
Humm that is most likely a mistake.
However I would advise you to upgrade your back end to [Lychee-Laravel](https://github.com/LycheeOrg/Lychee-laravel) where we know for sure this is working as we have a CI working: https://github.com/LycheeOrg/Lychee-Laravel/blob/master/tests/Feature/AlbumTest.php#L166

**Comment by kamil4** [comment]
I wouldn't necessarily label it a _mistake_. As far as I can tell, Lychee v3 is more selective about which fields it sends in response to which command. I assume it will send the description field in response to `Photo::get`, but since that field is not used in album view, it's not sent for `Album::get`.

In v4 we send pretty much everything in all situations, which is more predictable but also potentially slightly slower.

**Comment by ildyria** [comment]
Fixed in the v4.
