### ISSUE TITLE
Issue while upgrading Lychee from 3.1.6 to 3.2.16

### ISSUE THREAD

**Issue by prbt2016** [LycheeOrg/Lychee-v3#278]
### Detailed description of the problem
Hello I tried to upgrade Lychee from 3.1.6 to 3.2.16 using this guide 
https://github.com/LycheeOrg/Lychee/wiki/Update#update-manually

I keep the old /data and the /uploads directory as is and replace all other files as mentioned, However it asks me to recreate the user. What could be causing this issue?

### Browser and system
Chrome - 75.0
Apache -2.2
Mysql - 5.5
Centos -6.4 Final
PHP version -7.1

**Comment by d7415** [comment]
So long as `data/config.php` is still intact and readable that shouldn't happen. I'd suggest you check that file is still there and still has the correct values and permissions. I'm assuming you haven't changed/cleared your MySQL database?

**Comment by prbt2016** [comment]
Yes the data/config.php file is intact and it does have readable (i.e 644) permission. I kept the old data and uploads directory(of version 3.1.6) as is, and replaced all the other files with latest (3.2.16 version files) as mentioned in the update documentation.

 After doing this when I visit the url i.e http://domain.com/lychee, I get the following screen:
![test](https://user-images.githubusercontent.com/17871448/62533523-8179e300-b864-11e9-939d-806f391e9ad0.png)

Also when I check the database after hitting the url , in the {{PREFIX}}lychee_settings table, the hashes of username and password are erased.

What could be the issue?. Could you please try to replicate this at your end?

**Comment by ildyria** [comment]
What happen once you enter a new username and password ? Does it request it again when you log out ? 

BTW: php 7.1 is depreciated.

**Comment by prbt2016** [comment]
>>What happen once you enter a new username and password ?

After entering new username and password I am logged into the panel and also it doesn't request for password when logged out.

**Comment by ildyria** [comment]
Then I guess you are fine now ? :p

**Comment by prbt2016** [comment]
For upgrade I should be able to login with the previous admin username and password details right?

**Comment by ildyria** [comment]
True but I guess you are upgrading from a very old version which is from electerious (https://github.com/electerious/Lychee). As a result, there may be some script which reset the login/password.

Also I don't expect any new release of the v3 any time soon (as we are focused on the v4), nor do I expect the migration to the v4 to erase those information again.

**Comment by prbt2016** [comment]
Thanks a lot for that information.

**Comment by ildyria** [comment]
If you want to check the v4: https://github.com/LycheeOrg/Lychee-laravel
