### ISSUE TITLE
Download from shared albums?

### ISSUE THREAD

**Issue by uniQ168** [LycheeOrg/Lychee-v3#280]
I just installed Lychee and it's amazing.
Is there a way to enable download from password protected, shared albums?

Thanks in advance!

**Comment by kamil4** [comment]
Yes, having downloadable, password-protected albums should be supported already. Simply select both options when editing sharing for the album in question. Is it not working for you? If so, can you describe the problem in more detail?

**Comment by uniQ168** [comment]
You are right, I just didn't notice. :D
It's working flawlessly, thanks!
