### ISSUE TITLE
issue for making plugin

### ISSUE THREAD

**Issue by moguno** [LycheeOrg/Lychee-v3#283]
Hello.Lychee is good software!

I would like to hook "Photo move to the album".
but Photo::set Album:after provides only album id.
I would like to get photo id.

I think that "$subject" should contain "$this" object in all hooks.

Do you think about it?

**Comment by d7415** [comment]
Lychee v3 is not under active development, awaiting the release of [version 4](https://github.com/LycheeOrg/Lychee-Laravel/).

**Comment by moguno** [comment]
Thank you.

I look forward to the release of V4.
