### ISSUE TITLE
[question] are the picture files stored in the database or in the web folder?

### ISSUE THREAD

**Issue by Sam1370** [LycheeOrg/Lychee-v3#287]
if you know please add it to the faq so it can be easily seen by other users

**Comment by devincowan** [comment]
Default, pictures are stored in the web directory.
An related question, to which I don't have an answer:
Is there a way to change the location of the picture storage (for instance from /var/www/Lychee/ to somewhere else on server)?

**Comment by Sam1370** [comment]
Thank you for the info, hopefully someone else answers this question.

**Comment by d7415** [comment]
> are the picture files stored in the database or in the web folder?

Yes, in the `uploads` folder under Lychee.

> if you know please add it to the faq so it can be easily seen by other users

You're the first to ask, so no.

> Is there a way to change the location of the picture storage (for instance from /var/www/Lychee/ to somewhere else on server)?

symlinks work.


If you are planning to try Lychee, I should point out that Lychee v3 (this repo) is no longer under active development, awaiting the release of [version 4](https://github.com/LycheeOrg/Lychee-Laravel/). Version 4 is very-late beta at this point and is being used in production by several users.
