### ISSUE TITLE
Fresh install，Sever error or api not found

### ISSUE THREAD

**Issue by iajiao** [LycheeOrg/Lychee-v3#290]
### Detailed description of the problem

Sever error or api not found

### Steps to reproduce the issue

install

### Output of the diagnostics (Settings => Diagnostics)

{description: "Server error or API not found.", params: {…}, response: SyntaxError: Unexpected token < in JSON at position 0
    at parse (<anonymous>)
    at tt (http://…}
description: "Server error or API not found."
params: {function: "Session::init"}
response: SyntaxError: Unexpected token < in JSON at position 0 at parse (<anonymous>) at tt (http://vwjerome.free.fr/Lychee/dist/main.js:1:12632) at n (http://vwjerome.free.fr/Lychee/dist/main.js:3:11797) at XMLHttpRequest.<anonymous> (http://vwjerome.free.fr/Lychee/dist/main.js:3:16973)
__proto__: Object

### Browser and system

chrome
PHP Version 5.6.34

**Comment by kamil4** [comment]
I suppose it could be because of your PHP version? Lychee needs at least 7.1...

**Comment by d7415** [comment]
No response and old PHP. Closing.
