### ISSUE TITLE
Cannot disable share option (Facebook, Twitter)

### ISSUE THREAD

**Issue by CountCypher** [LycheeOrg/Lychee-v3#293]
I'd like to disable the share option for Facebook and Twitter for albums and fotos in the respective menu in the top right corner. Is there a way to disable the sharing to Facebook and Twitter or to disable the sharing option completely? Thanks in advance.

**Comment by ildyria** [comment]
@CountCypher You realize that removing the sharing button will not prevent anyone to copy the address and post it in Facebook or Twitter, right ?

**Comment by CountCypher** [comment]
@ildyria Yes, I'm aware of that. It's just about not necessarily promoting it through the GUI. Is there maybe a file I can edit to disable it?

**Comment by ildyria** [comment]
that is probably the case. The problem is that I don't have any instances of Lychee v3 running at hand at this time.
I highly advise you to upgrade to Lychee v4 (not officially released yet but 99% prod ready) : https://github.com/LycheeOrg/Lychee-laravel
As it is more up to date (especially in the front-end part).

**Comment by CountCypher** [comment]
@ildyria Thanks for the hint, I'll give it a try. So I assume then that v4 provides the option I was asking about? ;)

**Comment by ildyria** [comment]
Not yet, but it will be easier for me to advise you on it and you will be on the bleeding edge of our development. :)

**Comment by kamil4** [comment]
Considering that Lychee is an open source project, you can always tweak its source as you see fit and recompile. Instructions to recompile the front end are here: https://github.com/LycheeOrg/Lychee/wiki/Build.

In your case, you need to comment out lines [416-417](https://github.com/LycheeOrg/Lychee-front/blob/4ce005d2994141befe6ba9acd93967766c4536f9/scripts/main/contextMenu.js#L416) and [432-433](https://github.com/LycheeOrg/Lychee-front/blob/4ce005d2994141befe6ba9acd93967766c4536f9/scripts/main/contextMenu.js#L432) (in the current version; line numbers are likely to be a little different in the version you use) and recompile.

**Comment by CountCypher** [comment]
@kamil4 Thanks, that was the information I was looking for! :)
