### ISSUE TITLE
Server-Error or API not found

### ISSUE THREAD

**Issue by tbx84** [LycheeOrg/Lychee-v3#296]
Hello,
I wanted to update Lychee, which unfortunately didn't work. So I reinstalled it and got the error "Server-Error or API not found". Meanwhile I have completely reinstalled the server (Ubuntu 18.04, PHP 7.2, Apache, MySQL etc.). Nevertheless I still get the error.
I have tested the MySQL connection, which works fine.

What could be the reason? What am I doing wrong?

Logs:
2019-09-27 20:12:41 - error - Lychee\Modules\Database::createTables (169) 	- Table 'lychee.lychee_settings' doesn't exist
2019-09-27 20:12:41 - error - Lychee\Modules\Database::createTables (214) 	- Table 'lychee.lychee_albums' doesn't exist
2019-09-27 20:12:41 - error - Lychee\Modules\Database::createTables (237) 	- Table 'lychee.lychee_photos' doesn't exist
2019-09-27 20:12:41 - error - update_030203 (12) 	- Unknown column 'small' in 'field list'
2019-09-27 20:12:41 - error - update_030204 (12) 	- Unknown column 'lens' in 'field list'
2019-09-27 20:12:41 - error - update_030205 (12) 	- Unknown column 'license' in 'field list'
2019-09-27 20:12:41 - error - update_030207 (12) 	- Unknown column 'license' in 'field list'

**Comment by tbx84** [comment]
Now i found out, that i can upload pictures and make albums.
The problem is, that the user an password is never written to the database!?
No matter how often I create the user.

**Comment by ildyria** [comment]
Well if the `lychee_settings` table does not exists obviously you will not be able to set user and password.
As for why it was not created, that's another problem... :thinking: 

What does the Diagnostics page give you ?

**Comment by d7415** [comment]
> Well if the `lychee_settings` table does not exists obviously you will not be able to set user and password.

Except it lychee_albums and lychee_photos don't exist, the uploading and creating shouldn't be possible either...

@tbx84 If you can login to upload, can you set the password in settings?

**Comment by tbx84** [comment]
> @tbx84 If you can login to upload, can you set the password in settings?

Yes, i can change it there, but after this, it is impossible to login.
Then my only chance is to change it in phpmyadmin to empty fields.

`Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Error: Username empty or not set in database
Error: Password empty or not set in database


System Information
------------------
Lychee Version (json):  3.2.16
Lychee Version (git):   6b90c08 (master)
DB Version:             update_030216
System:                 Linux
PHP Version:            7.2
MySQL Version:          50727
Imagick:                1
Imagick Active:         1
Imagick Version:        1687
GD Version:             2.2.5
Plugins:                


Config Information
------------------
checkForUpdates:         1
default_license:         none
deleteImported:          1
full_photo:              1
hide_version_number:     1
image_overlay:           0
image_overlay_type:      exif
imagick:                 1
lang:                    de
layout:                  0
medium_max_height:       1080
medium_max_width:        1920
php_script_limit:        0
public_search:           0
skipDuplicates:          0
small_max_height:        360
small_max_width:         0
sortingAlbums:           ORDER BY id DESC
sortingPhotos:           ORDER BY id DESC
useExiftool:             0
version:                 update_030216`

**Comment by tbx84** [comment]
Oh, sorry ... found out, that it was a problem with my https-config.

**Comment by ildyria** [comment]
Niiice :+1:
