### ISSUE TITLE
Lychee Redirect plugin is deprecated

### ISSUE THREAD

**Issue by sochix** [LycheeOrg/Lychee-v3#298]
Hi there,
Lychee Redirect plugin is deprecated but it is still in the list on the main page.
Should I create a PR and remove it from the list?

**Comment by ildyria** [comment]
Please do. :)

**Comment by sochix** [comment]
Done https://github.com/LycheeOrg/Lychee/pull/299

**Comment by d7415** [comment]
Do we want to remove them, or just mark as deprecated? Someone may want to update them.

FWIW, lychee-watermark is also deprecated (it and lychee-redirect are both from @electerious), lychee-create-medium is (I think) covered by internal scripts and most of the others haven't been updated in years, but may still work.

**Comment by sochix** [comment]
@d7415 yep, maybe it's better to label them as deprecated. Should I create new PR?

**Comment by ildyria** [comment]
@sochix the proper way would be:

```
# if not already done
git clone https://github.com/sochix/Lychee/
cd Lychee

# switch to the PR branch
git checkout patch-1
# >> edit readme
git add -u
git commit -m "marking as deprecated"
git push
```

This will automatically update the pull request. :)

**Comment by ildyria** [comment]
@sochix I am waiting for the update of your PR with the depreciation to merge it. :)

**Comment by sochix** [comment]
@ildyria done!
