### ISSUE TITLE
Allow anonymous upload to "Public" album?

### ISSUE THREAD

**Issue by InfoSec812** [LycheeOrg/Lychee-v3#3]
### Detailed description of the request
- Enhancement - Give the administrator the ability to allow anonymous upload (only image files) to a specific album. The anon user should be able to (just during their session) update/add EXIF/MetaData
- The Anon users should be able to view ALL photos
- Anon users should NOT be able to delete photos

**Comment by p4u** [comment]
Not what you are asking for, but for disable the login you can apply this ugly patch.

```
diff --git a/php/Modules/Session.php b/php/Modules/Session.php
index 8d8714b..807fe20 100755
--- a/php/Modules/Session.php
+++ b/php/Modules/Session.php
@@ -32,6 +32,7 @@ final class Session {
                        $return['config']['login'] = true;
                }
 
+
                if ($public===false) {
 
                        // Logged in
@@ -102,14 +103,14 @@ final class Session {
        private function noLogin() {
 
                // Check if login credentials exist and login if they don't
-               if (Settings::get()['username']===''&&
-                       Settings::get()['password']==='') {
+//             if (Settings::get()['username']===''&&
+//                     Settings::get()['password']==='') {
                                $_SESSION['login']      = true;
                                $_SESSION['identifier'] = Settings::get()['identifier'];
-                               return true;
-               }
+                               return false;
+//             }
 
-               return false;
+//             return false;
 
        }
```

**Comment by ildyria** [comment]
I don't like this idea. This exposes the server to way to much abuses e.g. what if a person just uploads as many files as he could and fill up the disk space... or simple DDOS attacks by filling up the RAM used by the server while processing the pictures.

**Comment by dunklesToast** [comment]
Well, if it generates a custom, unique link for the upload thing (uploadToken) then there won't be any way to DDoS the Server since there won't be a way to upload. Also, you are already limiting the files processed parallel so that also won't affect the server performance. In my opinion its a really useful feature and I miss it in lychee

**Comment by kajaba** [comment]
Ism voting for this. It would be great to send custom generated link to friends to upload photos. Then I am able to organize them as I like.
