### ISSUE TITLE
Add multiple user accounts

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-v3#30]
From: https://github.com/electerious/Lychee/issues/746
and: https://github.com/electerious/Lychee/issues/132

> I would like to suggest the following feature.
> 
> It would be nice to have the ability to have multiple user accounts with the ability to share photos and albums with other accounts. Only the account that uploads the photo can delete them.

-------

Here's some ideas for access control that I would like to see, I haven't really looked at the code so I’m not sure how hard this would be.

You'd probably have to create a table that would define users and their permissions to each album then have a php/js script determine what albums should be displayed and that would also limit access based on those permissions. It might also be a good idea to keep some of the session data stored on the server if it isn't already, that way you could compare the session identifier token to the username that the request was being performed as and validate that they match before executing any functions; this would assist to mitigate a malicious user from executing commands/actions as another user.

### Superuser
Full access to view/modify all albums and photos

### Standard
Per album view control (who can or can't view album x)
Per album upload control (who can or can't upload to album x)
Per album and photo delete option (who can or can't delete photos from album x)

### Read Only
Can only read/view images for explicitly defined albums.

-----

There're a lot of things to do:

- Add user-table to the database
- Add userid for each album and photo
- Every MySQL query needs to be modified
- A dialog to manage and edit users
- etc.

As said here, multi-user is currently not planned. It needs a lot of modifications.

----

More to read on https://github.com/electerious/Lychee/issues/132

**Comment by jeyca** [comment]
is anyone actively working on this?

**Comment by ildyria** [comment]
I will soon start working on it, why? Are you interested in working on it too?

**Comment by jeyca** [comment]
I am more interested in using it than in working on it :) But actually, I took a look if I would like to contribute code for this and other feature but must say that I am not very much convinced of the code structure and don't know if it makes sense to put effort into it apart from restarting it within a more proven framework.

**Comment by ildyria** [comment]
If you want to have a look at another framework, I'm working on parallel with that one:
https://github.com/ildyria/Lychee-Laravel

It provides nearly the same functions as the current version (search is not implemented).
The only "problem" is that it does not work *out-of-the-box*.
you have to do the `composer update`, edit the `.env` file; do `./artisan migrate` and `./artisan npm`. :confused:

**Comment by ildyria** [comment]
As previously said, I am working on it:

https://github.com/ildyria/Lychee-Laravel/commit/526780e0e5b003309bfb39df59a622e4f2b06e15

In the current master Laravel version, it is now possible to add multiple users. It is missing a lot of features (they can upload, delete, create albums etc...) but they don't have access to the admin part (or most of it).
I am still working on it, but it is coming slowly...

**Comment by ildyria** [comment]
This is completed in the latest version of Lychee-Laravel: https://github.com/ildyria/Lychee-Laravel/commit/ccf9a2649cfcd47bc16323b1e1e66a46e4d216fb .

**Comment by Peque** [comment]
@ildyria Will that work be merged here or are you planning on keeping Lychee-Laravel as a different project?

**Comment by ildyria** [comment]
@Peque My current plans are:
1. to add sub albums to Lychee-Laravel
2. to add an option to switch to the visual layout of pictures for the flickr justified layout (see [here](https://github.com/flickr/justified-layout) ) but that is more on the Lychee-front side.
3. to migrate Lychee-Laravel from my personal account to LycheeOrg and release it as Lychee version 4.0
4. to rename the current Lychee repository as Lychee-Legacy as an alternative because Lychee-Laravel will require `composer`.

You can check the status of my todo list [here](https://github.com/ildyria/Lychee-Laravel/blob/master/todo.md).

To be noted that video are now supported on Lychee-Laravel. :)

**Comment by ildyria** [comment]
See https://github.com/LycheeOrg/Lychee-Laravel for alpha version.

**Comment by Arthaey** [comment]
> Lychee-Laravel will require composer

Is there any way to make composer optional for Lychee-Laravel? I use a shared host that doesn't allow composer.

**Comment by d7415** [comment]
> > Lychee-Laravel will require composer
> 
> Is there any way to make composer optional for Lychee-Laravel? I use a shared host that doesn't allow composer.

Please create new issues for new questions, and do so in the correct repository.

**Comment by ildyria** [comment]
@Arthaey Lychee-laravel requires composer if you install it via a `git clone`. However releases will not require it as we also pack the vendors folder.
Which remind me that it would be nice to do a release soon. :)
