### ISSUE TITLE
Option to remove the share Button on public albums

### ISSUE THREAD

**Issue by lyossius** [LycheeOrg/Lychee-v3#304]
Hello and thanks for the awesome work. 
I know its a rather unusual  request in this day and age, but is there a chance to add an option to deactivate the share button on (hidden) public albums if nobody is logged in? Or limit the options? I find it quite unusual to create a (hidden) public album, add a password for safety measures but everybody can share its contents.

**Comment by ildyria** [comment]
They will still be asked for the password when trying to open it.

**Comment by ildyria** [comment]
fixed in v4.
