### ISSUE TITLE
LDAP integration

### ISSUE THREAD

**Issue by Stalfur** [LycheeOrg/Lychee-v3#305]
Integrating logins with already running services would make this much more usable for small (and large) organizations where we try to not let people have a separate login on each tool.

For example if your login against a set LDAP server is authenticated then you are treated as a Registered user - if it is not you are Public.

**Comment by ildyria** [comment]
Not going to happen in the v3.

Already considered in the v4: https://github.com/LycheeOrg/Lychee-Laravel/issues/324
