### ISSUE TITLE
Getting blank screen when loading into website

### ISSUE THREAD

**Issue by EverlyScott** [LycheeOrg/Lychee-v3#306]
When I install and load into Lychee, I just get a blank screen
![image](https://user-images.githubusercontent.com/31575858/66712539-c12ce180-ed63-11e9-8fd0-11729b2b2848.png)

Log:

`Error 001: Configuration not found. Please install Lychee first.`

Diag:

```
Diagnostics
-----------
Error: Configuration not found. Please install Lychee for additional tests.
```

Chrome Version 77.0.3865.120 (Official Build) (64-bit),
Windows 10 Home x64 Version 10.0.18362 Build 18362

**Comment by EverlyScott** [comment]
Still happens in incognito

**Comment by EverlyScott** [comment]
I think I found out the issue, but I cant find out how to fix it...

When going into chrome inspector, the script tag is supposed to load dist/main.js, but in the sources tab, the file is not loaded.... in console it has no errors about it not being able to load the file.

**Comment by EverlyScott** [comment]
and I can load the script in a web browser 
![image](https://user-images.githubusercontent.com/31575858/66719542-f0207300-edb6-11e9-8039-1adb4c0959ad.png)

**Comment by ildyria** [comment]
> `Error 001: Configuration not found. Please install Lychee first.`

This tells me that it cannot find the `data/config.php` file.

What install steps did you do so far ?

**Comment by EverlyScott** [comment]
> What install steps did you do so far ?

I completed all of the install steps multiple times

**Comment by ildyria** [comment]
What were thoses ?

**Comment by EverlyScott** [comment]
every thing on the [installation wiki page](https://github.com/LycheeOrg/Lychee/wiki/Installation)

**Comment by ildyria** [comment]
So you haven't fully installed Lychee yet. Basically you are missing the last step which is done online: the creation of the tables for the database.

**Comment by EverlyScott** [comment]
Yup, but when I try to do that I just get that blank screen

**Comment by ildyria** [comment]
hummm

**Comment by EverlyScott** [comment]
And I'm guessing its because for some reason its not loading the /dist/main.js file.... and throws no errors in the chrome console

**Comment by ildyria** [comment]
Rename the `.htaccess` into something else.

**Comment by ildyria** [comment]
@d7415 can you ahve a look too ? 

Also you can drop by our gitter: https://gitter.im/LycheeOrg/Lobby

**Comment by EverlyScott** [comment]
> Rename the `.htaccess` into something else.

hmm.... works

**Comment by d7415** [comment]
@ScribbleNerd Was there anything in your browser console with the .htaccess present?

**Comment by EverlyScott** [comment]
Everything works now on a VPS.. I think the shared hosting was messing up something

**Comment by ildyria** [comment]
The share hosting was probably having issues with the `.htaccess` yes. :(
