### ISSUE TITLE
Love Lychee, feature requests.

### ISSUE THREAD

**Issue by smvueno** [LycheeOrg/Lychee-v3#309]
### Detailed description of the problem
The gallery runs super smooth for me, but I'm missing important functions such as.
**Mass download of albums**
**Password protected albums**

### Ideas for fix
**Zip stream** implementation would be awesome for a quick zip file download of current album!
https://github.com/maennchen/ZipStream-PHP

As for password protection, any simple password protection would be working just fine.

**Comment by d7415** [comment]
Already implemented in the next verion [here](https://github.com/LycheeOrg/Lychee-Laravel).
