### ISSUE TITLE
Lychee and Matomo

### ISSUE THREAD

**Issue by effatee** [LycheeOrg/Lychee-v3#310]
### Detailed description of the problem

Hi all,
I've been trying to integrate a javascript tag in the < head > part of the index.html
This is to integrate a visitor analytics tracker (to a Matomo instance running on the same server).
But it doesn't seem to be working. Matomo isn't registering any visitors.
Just wondering if there would be a better way to achieve this that works well with Lychee ?
(edit another file than index.html, create a separate javascript file, etc..? )

### Steps to reproduce the issue

edit index.html
add script within < head >...< / head >

### Browser and system

**Comment by ildyria** [comment]
Also make sure the CSP is not blocking it.

**Comment by effatee** [comment]
> Also make sure the CSP is not blocking it.

Hi and thanks.
I have no issues with my CSP, and furthermore, I have other virtual hosts on the same server that are reporting successfully to Matomo.
A Nextcloud instance with the Piwik/matomo app, a Wordpress also using the matomo plugin, and a static html page, with the embeded javascript code. All are reporting successfully. 
Except the Lychee instance...
These virtual hosts and Matomo are all on the same server/machine/network.

**Comment by ildyria** [comment]
Open in v4: https://github.com/LycheeOrg/Lychee-Laravel/issues/348
