### ISSUE TITLE
Importing more than 80 or so photos from server aborts early

### ISSUE THREAD

**Issue by DavidGriffith** [LycheeOrg/Lychee-v3#311]
### Detailed description of the problem
When attempting to import more than a certain number of photos from the server, the process stalls with no explanation at around the 80 mark.  The "importing" screen just keeps going and going.  You'll know Lychee aborted or stalled when watching on `htop` that the load goes back to normal.

### Steps to reproduce the issue
Put a directory containing around 100 photos on your server.  Create a new album, then select "Import from server".  Give the dialog the directory on the server containing your 100+ photos.  Watch as the process stalls out.  Eventually you'll be able to load the gallery in another tab and notice that not all the photos got into the gallery.

### Output of the diagnostics (Settings => Diagnostics)
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
/var/www/661.org/gallery/Lychee-front/package.json not found. Please do: git submodule init ; git submodule update
Lychee Version (git):   8310355 (master)
DB Version:             update_030216
System:                 Linux
PHP Version:            7.3
MySQL Version:          100317
Imagick:                1
Imagick Active:         1
Imagick Version:        1690
GD Version:             2.2.5
Plugins:                

Config Information
------------------
checkForUpdates:         1
default_license:         none
deleteImported:          1
full_photo:              1
hide_version_number:     1
image_overlay:           0
image_overlay_type:      exif
imagick:                 1
lang:                    en
layout:                  0
medium_max_height:       1080
medium_max_width:        1920
php_script_limit:        0
public_search:           0
skipDuplicates:          0
small_max_height:        360
small_max_width:         0
sortingAlbums:           ORDER BY id DESC
sortingPhotos:           ORDER BY id ASC
useExiftool:             0
version:                 update_030216

### Browser and system
Debian 10, Firefox 60.9.0esr

**Comment by kamil4** [comment]
Can you try setting `php_script_limit` to `1` in the advanced options?

Overall, https://github.com/LycheeOrg/Lychee-Laravel (soon-to-be-v4) has an enhanced import feature that should be immune to such problems and that also provides real-time progress information via the GUI. We have a beta release ready for download, though that one does not include these enhancements, but even the bleeding edge from git is generally pretty stable. I encourage you to give it a try!

**Comment by ildyria** [comment]
Given that we have not heard from the author, I assume this issue closed.

**Comment by DavidGriffith** [comment]
Tried it.  Didn't work
