### ISSUE TITLE
[Help, not issue] Installing FFMpeg on windows?

### ISSUE THREAD

**Issue by EverlyScott** [LycheeOrg/Lychee-v3#314]
Anyone know how I would go about intsalling FFMpeg on Windows Server 2019?

**Comment by d7415** [comment]
There's a download link at https://ffmpeg.org/download.html . Beyond that, I haven't tried so can't say.

**Comment by ildyria** [comment]
Unrelated to the project specifically and authors did not answer @d7415 thus I assume the problem has been solved.
