### ISSUE TITLE
upload from server doesn't complete

### ISSUE THREAD

**Issue by mrjoli021** [LycheeOrg/Lychee-v3#319]
I have copies over 12,000 pictures to  the imports directory.  All pictures are owned by apache.   I am running CentOS 7 with php 7.3.11.  When I attempt to upload from server the pictures starts showing up.  After about 700-800 pictures the imports stops.  The browser just says importing and just freezes.  I have waited about 8-10 hours and nothing.  I refresh the browser and start it again.  This time the pictures continue to import, but again after several hundred pictures the picture count stops.  I have tried different browsers and OS's to perform the upload.  
What are my options to upload so many pictures?

**Comment by ildyria** [comment]
This is most likely due to a timeout either by apache or Php.

**Comment by kamil4** [comment]
Can you try setting `php_script_limit` to `1` in the advanced options?

In general, this problem is fully fixed in https://github.com/LycheeOrg/Lychee-Laravel (soon-to-be-v4).

**Comment by mrjoli021** [comment]
Where can I find the advanced options?  I dont see it on the site.

**Comment by kamil4** [comment]
Go to _Settings_, scroll to the bottom, click _More_. You'll see all the settings listed. Change the value of `php_script_limit` from `0` to `1` and save the settings.

**Comment by mrjoli021** [comment]
I got this issue resolved by increasing the timeout in the php.ini.

the issue now is that since there are so many pictures, the pictures never load on the site.  So the site initially loads with a total of 12k + pictures in the unsorted album.  When I click on the album the site freezes and never returns any pictures.  How can I fix this?

**Comment by kamil4** [comment]
I don't have experience with 12k+ albums in Lychee v3 but I have one such album in Lychee-Laravel (soon-to-be v4) and, as the two versions currently share the same front end code, here's my advice:

**Don't do it :smile:**

At least the v4 server can handle such albums relatively OK, but the front end, and actually by the look of it the web browser itself, is really struggling. There've been proposals to introduce pagination or infinite scroll to combat that, but no code so far. The only improvement we did implement to make this less painful is the lazy loading of photos (so the browser doesn't download them until they are visible). Still, for me a 13k+ album does load, but it takes some 25 seconds for the first photos to render (on a dual-core i7 CPU).

My advice is to keep albums to around 1000 photos. That number seems to be handled much better.

**Comment by d7415** [comment]
Importing from server creates albums for folders, so sorting before you import  is an option too.

**Comment by mrjoli021** [comment]
ok I can easily split this into 1000 pictures per directory.  This will create about about 1200 directories.  How can I import them automatically?  Is there a backend script or something to import all these directories?

**Comment by d7415** [comment]
> ok I can easily split this into 1000 pictures per directory. This will create about about 1200 directories.

12, surely?

> How can I import them automatically? Is there a backend script or something to import all these directories?

It's been a while, but I'm pretty sure you just upload the parent. i.e. tell it to import from `uploads/import` and have e.g. `uploads/import/a`, `uploads/import/b` etc as subdirectories.

**Comment by ildyria** [comment]
Fixed?

**Comment by ildyria** [comment]
Time to close.
