### ISSUE TITLE
Impossible to connect lychee to mariaDB container on rpi3

### ISSUE THREAD

**Issue by JordanAtDown** [LycheeOrg/Lychee-v3#321]
### Detailed description of the problem
I can't install lychee. I can't connect lychee to my mariaDB container

### Steps to reproduce the issue

version: "3.3"

services:
  lychee:
    image: linuxserver/lychee:latest
    container_name: lychee
    environment:
      - PUID=${LYCHEE_PUID}
      - PGID=${LYCHEE_PGID}
      - TZ=Europe/Paris
    volumes:
      - ${LYCHEE_CONFIG}:/config
      - ${LYCHEE_PICTURES}:/pictures
    ports:
      - 8080:80
    restart: always
  
  mysql:
    image: biarms/mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=testroot
      - MYSQL_DATABASE=photos
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test2

### Browser and system
On raspberry 3.

it is possible to have a log of the login error to the database ? Which version of mariadb/mysql is supported by lychee ?

**Comment by ildyria** [comment]
> Which version of mariadb/mysql is supported by lychee ?

I don't think we have a hard requirement on that one.

I don't use Docker, and Lychee works perfectly well out of the box (as we don't hear complains).
So my guess it that your best chances to solve this is to ask https://github.com/linuxserver/docker-lychee or @roblandry

**Comment by limako** [comment]
Did you set bind-address in my.cnf to 0.0.0.0? Otherwise, mysqld will only listen to localhost.

**Comment by JordanAtDown** [comment]
Il semblerait que cela vienne de mysql. Mysql doit augmenter l'accés de ses utilisateurs en spécifiant l'ip qui va le contacter pour fonctionner.
Actually, I'm also looking at the bin address of my.cnf
Thanks
