### ISSUE TITLE
upload fails with "No Api method specified

### ISSUE THREAD

**Issue by chrisbra** [LycheeOrg/Lychee-v3#323]
### Detailed description of the problem

For a while now I have the problem, that sporadically when uploading files, it fails with the error message: "No API function specified". 
Not sure what to look out for in the console window:
![grafik](https://user-images.githubusercontent.com/244927/69559102-a1671b00-0fa9-11ea-8f55-c9abb1751a46.png)

### Steps to reproduce the issue

upload a new picture.

### Output of the diagnostics (Settings => Diagnostics)

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version (json):  3.2.16
Lychee Version (git):   7557a82 (master)
DB Version:             update_030216
System:                 Linux
PHP Version:            7.2
MySQL Version:          50728
Imagick:                1
Imagick Active:         1
Imagick Version:        1687
GD Version:             2.2.5
Plugins:                

Config Information
------------------
checkForUpdates:         1
default_license:         none
deleteImported:          1
full_photo:              1
hide_version_number:     1
image_overlay:           0
image_overlay_type:      exif
imagick:                 1
lang:                    de
layout:                  1
medium_max_height:       1080
medium_max_width:        1920
php_script_limit:        0
public_search:           0
skipDuplicates:          0
small_max_height:        360
small_max_width:         0
sortingAlbums:           ORDER BY id DESC
sortingPhotos:           ORDER BY title ASC
useExiftool:             0
version:                 update_030216

### Browser and system

Firefox 70, Windows 10

**Comment by chrisbra** [comment]
It works, if I let the server import it from a local directory. Could that be a `file too large` problem?

**Comment by chrisbra** [comment]
why was this closed?

**Comment by ildyria** [comment]
Sorry, as you did not bugged us or give any news over the last 4 months, I assumed the issue was fixed.

Looking at your issue, this is likely to be a problem of configuration on your side and we cannot reproduce such error.

Additionally, We are moving to the v4 *very soon*™ which is currently in its released state (but non official) here: https://github.com/LycheeOrg/Lychee-laravel (I highly encourage you to try it).

**Comment by chrisbra** [comment]
No, I did not know what more information I could give you. I will try v4 once it is released.

**Comment by ildyria** [comment]
> I will try v4 once it is released.

I have been using it since... September 2018 ! :sweat_smile: 

Joke aside, we are finalizing it. I finished the doc this morning. Just waiting for @d7415  to figure out the [2 PR](https://github.com/LycheeOrg/Lychee-laravel/pulls) and we should be good for release.

The only questions is the renaming of the repositories:
- Lychee &rArr; Lychee-Classic-v3 or Lychee-v3
- Lychee-Laravel &rArr; Lychee or Lychee-v4

**Comment by chrisbra** [comment]
I see, then if I find some spare time, I will check it out. I suppose the data can be automatically migrated to the new version then?

**Comment by ildyria** [comment]
https://github.com/LycheeOrg/Lychee-Laravel/wiki/FAQ#how-do-i-upgrade-from-lychee-v3-to-lychee-v4
:smiley: 

We need to double check it before doing the last jump but in theory it should be fine:
https://github.com/LycheeOrg/Lychee-Laravel/issues/469#issuecomment-611139932

**Comment by chrisbra** [comment]
thanks for the pointer. will try it out and report problems ;)

**Comment by ildyria** [comment]
![2020-04-17_1920x1080_22:16:57](https://user-images.githubusercontent.com/627094/79610679-4caf7280-80f9-11ea-80e2-684dcfa23d8a.png)
Well.. it is broken with the last commit. Going to fix that ASAP. :)

**Comment by chrisbra** [comment]
I tried, but cannot upgrade, as the new lychee requires php 7.3 and my server only has 7.2.24 (Ubuntu 18.04.4 LTS). Bummer

**Comment by ildyria** [comment]
If you use the release channel you will ignore the php requirement check, sure you will have an Error telling you to upgrade your php version in your Diagnostic page but you should still be fine.

Laravel 7 (framework on which Lychee v4 is based) requires only 7.2.5, So you should be able to make it work.

You can also do the composer step by forcing it:
```
composer install --no-dev --ignore-platform-reqs
```
https://stackoverflow.com/questions/26165101/skip-composer-php-requirement

But then you need to make sure you have the extension required (gd, xml, zip, json, tokenizer, session, mbstring,  ...).

**Comment by chrisbra** [comment]
Thanks. I assume with release channel you mean the Master branch from https://github.com/LycheeOrg/Lychee?
Is there a way to check, if all php extensions are installed? 
Thanks for coming back.

**Comment by ildyria** [comment]
> Thanks. I assume with release channel you mean the Master branch from https://github.com/LycheeOrg/Lychee?

I meant here: https://github.com/LycheeOrg/Lychee/releases

You can also locally clone the repo and do a `make dist`. This will generate an archive which would be the same as the one downloaded (but more *up to date* as you don't have to wait for us to do the release).

> Is there a way to check, if all php extensions are installed? Thanks for coming back.

We have some checks implemented in the Diagnostic page (if you can access it): https://github.com/LycheeOrg/Lychee/blob/master/app/Http/Controllers/DiagnosticsController.php#L130

I'm considering adding some sort of mechanism which allows the user to access Diagnostics without having to log in as admin (if e.g. the gallery does not display you cannot log in).

**Comment by chrisbra** [comment]
Thanks! finally it worked. Had an issue with https://github.com/LycheeOrg/Lychee/wiki/I-have-an-Error-404-when-I-open--gallery,-what-can-I-do%3F 
so perhaps mention that at the upgrade procedure.

Also I am a bit confused about the splash page. It looks nice, but it took me a bit until I found how to customize it.
