### ISSUE TITLE
CLI to trigger import?

### ISSUE THREAD

**Issue by fresh2dev** [LycheeOrg/Lychee-v3#325]
Is there a terminal command that can be issued to trigger an import from a local folder?

**Comment by ildyria** [comment]
There might be some additional software that take care of that.

It is work in progress in the version 4.
See here: https://github.com/LycheeOrg/Lychee-Laravel/pull/237

**Comment by tmp-hallenser** [comment]
There is a python script to import and sync from CLI (https://github.com/GustavePate/lycheesync). For Version 4, there is a WIP pull request (see reply above) and I've forked the above repo and created an experimental branch for v4.

**Comment by alex-phillips** [comment]
I'm also working in a node script in addition to this python one in case people have a preference

**Comment by ildyria** [comment]
Fixed in v4.
