### ISSUE TITLE
Video import via "Import from Server" does not work

### ISSUE THREAD

**Issue by tomscii** [LycheeOrg/Lychee-v3#326]
### Detailed description of the problem

Using a fresh test instance of Lychee 3.2.16, I can upload mp4 videos via "Upload photo" and they work fine (well, slightly suboptimal since the thumbnail is distorted into a square, but I can live with that). However, my usual workflow using "Import from Server" does not work, I get an error popup in the Lychee GUI saying "Folder empty or no readable files to process. Please take a look at the log (Settings -> Show Log) for further details."

However, there is nothing relevant in the log mentioned in the message.

Edit: I should mention that this is my first test attempt at using Lychee for videos. I have never tried this on earlier versions (currently I run Lychee 3.2.7 in production, for photos only). So I cannot say whether this is a regression of some sort.

I could probably work around this by throwing stuff directly into the database via some scripted sql inserts, but if this is a relatively trivial fix I might prefer to wait for a "proper" fix.

### Steps to reproduce the issue

Try to import a .mp4 video file via "Import from Server" feature.

### Output of the diagnostics (Settings => Diagnostics)

Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version (json):  3.2.16
Lychee Version (git):   No git data found. Probably installed from release.
DB Version:             update_030216
System:                 Linux
PHP Version:            7.3
MySQL Version:          100411
Imagick:                1
Imagick Active:         1
Imagick Version:        1801
GD Version:             bundled (2.1.0 compatible)
Plugins:                

Config Information
------------------
checkForUpdates:         1
default_license:         none
deleteImported:          1
full_photo:              1
hide_version_number:     1
image_overlay:           0
image_overlay_type:      exif
imagick:                 1
lang:                    en
layout:                  1
medium_max_height:       1080
medium_max_width:        1920
php_script_limit:        0
public_search:           0
skipDuplicates:          0
small_max_height:        360
small_max_width:         0
sortingAlbums:           ORDER BY id DESC
sortingPhotos:           ORDER BY id DESC
useExiftool:             0
version:                 update_030216

### Browser and system

Firefox 71 on MacOS Mojave (10.14.6)

**Comment by tmp-hallenser** [comment]
Did you give Lychee Laravel (aka Version 4) a try? The branch sync-from-cli (https://github.com/LycheeOrg/Lychee-Laravel/tree/sync-from-cli) gives you a cli command to import (in case you don't want to use the browser).

**Comment by d7415** [comment]
You're right. The Import function doesn't currently support video files. I'll have a quick look later and if it's straightforward I'll look at adding it.

**Comment by d7415** [comment]
I should add that [Lychee-Laravel](https://github.com/LycheeOrg/Lychee-Laravel/) (v4) is where active development is happening, so it may still be worth [migrating](https://github.com/LycheeOrg/Lychee-Laravel/wiki/Install).

**Comment by tomscii** [comment]
Thanks for confirming. Since I need video import to work in a batch manner for several videos per occasion (preferably without touching GUI) I have settled on a home-grown script that pushes inserts into the database directly. This works perfectly for my purposes, at least for now, so no pressure from my part in amending the "Import from Server" feature.

I will give Lychee-Laravel a spin for sure, when I have some time to play. Thanks for the heads up!
