### ISSUE TITLE
Add russian localization - file attached

### ISSUE THREAD

**Issue by l-e-s** [LycheeOrg/Lychee-v3#329]
Hello! I've been waiting for the long time and you did the localization, thank you!!! Please add the russian language, i've made the file and tested it on my server - https://lebedevcloud.ru/gallery
[Russian.php.zip](https://github.com/LycheeOrg/Lychee/files/4061370/Russian.php.zip)
I should note that translation of some lines is not applied, even if the string is present at the language file.

**Comment by hsousa** [comment]
Why not create a pull request instead? That would make it a lot easier for the maintainers.

**Comment by l-e-s** [comment]
I currently don't know how to make it, tried but got an error (made a branch and tried to push here. Wrong?). I am not a developer.

**Comment by l-e-s** [comment]
Created pull request #334
