### ISSUE TITLE
Lychee doesn't work with images "in situ" ?

### ISSUE THREAD

**Issue by shaun-ba** [LycheeOrg/Lychee-v3#330]
So i have 1000s of images on my NAS, will Lychee run and load them? I ask because I was watching a youtube video where it said "Original images will be deleted!"

Why would I want to delete my whole life's worth of images?

**Comment by expiredemulsion** [comment]
The idea is to let Lychee ingest the photos from an import drop folder and not from the original storage.

Perhaps when you have processed your raw photos and export them into different resolutions and paths.
One set of hi-res jpegs in Adobe RGB for printing to a sub folder on your NAS for storage and another set of lower resolution sRGB jpegs to an import folder locally or on your web server for your Lychee to ingest the photos from and then delete to keep the import folder clean.

**Comment by shaun-ba** [comment]
I thought the software was supposed to be for image management, having to keep duplicates of everything and figure out what is and isn't i certain places is not management, thats another layer of work?

**Comment by ildyria** [comment]
We do not support the "in situ" function.

However, since version 3.2.10 you now have an option with prevent the deletion in your configuration.
https://github.com/LycheeOrg/Lychee/commit/97e984c4940104b7012b064663d9f490327bf9c2

I would also suggest you to have a look at https://github.com/LycheeOrg/Lychee-laravel
which is a more up-to-date version of this where functionalities like these are being added: https://github.com/LycheeOrg/Lychee-Laravel/pull/427

**Comment by ildyria** [comment]
Also, I think your use case is different from what Lychee is for.
Lychee is designed to expose a gallery of your photo on the web. To manage your photo locally there are way better tools... e.g. Lightroom, Darktable...
The goal of Lychee is to be hosted on a VPS somewhere and have your website etc there. Even if it can be used as a front end on a NAS, It is not its aimed goal.

I personally see more NAS a cold storage back up.

**Comment by shaun-ba** [comment]
Yes I would like to view the gallery from elsewhere, other devices and such without setting up mount points to the NAS etc. But I don't see why it cannot run as a frontend to the NAS folders instead of creating all of its own duplicate copies of images. Seems like you're missing a trick there.

**Comment by ildyria** [comment]
1. Security reasons. e.g. assume someone gains access to Lychee admin interface and delete all the pictures... Sure your Lychee installation may be well protected behind firewalls but that may not be the case of everyone else.
2. It is simpler to directly manage the database that way: we don't need to remember the path of each picture.
3. Access right management is simpler: you just need to make sure that the www-data user has the correct access to the upload folder and don't need to worry to give access to other folders inside your `/home`, `/media` ....

**Comment by shaun-ba** [comment]
1. Isn't that your concern anyway, if the admin interface is vulnerable thats your issue! - Anyway I have multiple backups of the NAS drives on a regular basis so that issue is negated.
2. Lazy?
3. meh

Sorry i'll leave you to it, I'm just not sure what issue you are solving with the project

**Comment by ildyria** [comment]
> Sorry i'll leave you to it, I'm just not sure what issue you are solving with the project

Basically an open source flikr, and I wish in a long term future to Squarespace...

**Comment by d7415** [comment]
Dupe of #250.
