### ISSUE TITLE
An upload-folder is missing or not readable and writable

### ISSUE THREAD

**Issue by samcro1967** [LycheeOrg/Lychee-v3#332]
I do not see an "uploads" folder when I connect to the container via "docker exec -it lychee bash".  What is the path where this folder is supposed to be?

### Detailed description of the problem
Getting An upload-folder is missing or not readable and writable while trying to import photos.

### Steps to reproduce the issue
Click import from server, enter a valid path, click import

### Output of the diagnostics (Settings => Diagnostics)
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Error: 'uploads/big' is missing or has insufficient read/write privileges.
Error: 'uploads/small' is missing or has insufficient read/write privileges.
Error: 'uploads/medium' is missing or has insufficient read/write privileges.
Error: 'uploads/thumb' is missing or has insufficient read/write privileges.
Error: 'uploads/import' is missing or has insufficient read/write privileges.
Error: 'uploads/' is missing or has insufficient read/write privileges.
Error: 'data/config.php' is world readable.
Error: 'data/config.php' is world executable.

System Information
------------------
Lychee Version (json):  3.2.16
Lychee Version (git):   No git data found. Probably installed from release.
DB Version:             update_030216
System:                 Linux
PHP Version:            7.3
MySQL Version:          100412
Imagick:                1
Imagick Active:         1
Imagick Version:        1801
GD Version:             bundled (2.1.0 compatible)
Plugins:                

Config Information
------------------
version:                 update_030216
checkForUpdates:         1
sortingPhotos:           ORDER BY id DESC
sortingAlbums:           ORDER BY id DESC
imagick:                 1
lang:                    en
skipDuplicates:          0
layout:                  0
image_overlay:           0
default_license:         none
small_max_width:         0
small_max_height:        360
medium_max_width:        1920
medium_max_height:       1080
deleteImported:          0
image_overlay_type:      exif
php_script_limit:        0
useExiftool:             0
full_photo:              1
public_search:           0
hide_version_number:     1

### Browser and system
Chrome Version 79.0.3945.130 (Official Build) (64-bit)
Docker 19.03.5
Windows 10.0.18363.592

**Comment by d7415** [comment]
It should be directly under the Lychee folder. I suggest you look at any documentation from your docker image as it's probably meant to be mounted from outside. As this is a container issue, I'm closing this here.

**Comment by samcro1967** [comment]
So the proper path for the uploads folder is /config/lychee/uploads correct?  When I create an uploads folder there and restart lychee is still says no uploads folder even though that folder exists.

**Comment by d7415** [comment]
It all depends on how your docker image is set up. It's not an official image, and we can't cover every use case.

As we are (admittedly slowly) moving everything over to v4, I'd suggest looking at [LycheeOrg/Lychee-Laravel-Docker](https://github.com/LycheeOrg/Lychee-Laravel-Docker), on Docker Hub [Here](https://hub.docker.com/r/bigrob8181/lychee-laravel).

**Comment by samcro1967** [comment]
Appreciate the suggestion.  That docker image is not able to connect to the latest version of mariadb.  I also tried kolex/lychee.  This one has an uploads folder and can connect, but the app crashes after import.  I will check back in a few months and see if any of the images have been fixed.
