### ISSUE TITLE
Unable to download large-ish albums

### ISSUE THREAD

**Issue by Genide** [LycheeOrg/Lychee-v3#335]
### Detailed description of the problem
I have an album with about 20 images. When attempting to download the album, the UI will freeze.

### Steps to reproduce the issue
I would have at least 20 images in the album. More specifically, try to download an album that is larger than 150MB worth of images.

### Output of the diagnostics (Settings => Diagnostics)

> Diagnostics
> -----------
> Warning: Dropbox import not working. No property for dropboxKey.
> No critical problems found. Lychee should work without problems!
> 
> 
> System Information
> ------------------
> Lychee Version (json):  3.2.16
> Lychee Version (git):   No git data found. Probably installed from release.
> DB Version:             update_030216
> System:                 Linux
> PHP Version:            7.3
> MySQL Version:          100412
> Imagick:                1
> Imagick Active:         1
> Imagick Version:        1801
> GD Version:             bundled (2.1.0 compatible)
> Plugins:                
> 
> 
> Config Information
> ------------------
> checkForUpdates:         1
> default_license:         none
> deleteImported:          1
> full_photo:              1
> hide_version_number:     1
> image_overlay:           0
> image_overlay_type:      exif
> imagick:                 1
> lang:                    en
> layout:                  0
> medium_max_height:       1080
> medium_max_width:        1920
> php_script_limit:        0
> public_search:           0
> skipDuplicates:          0
> small_max_height:        360
> small_max_width:         0
> sortingAlbums:           ORDER BY id DESC
> sortingPhotos:           ORDER BY title ASC
> useExiftool:             0
> version:                 update_030216

### Browser and system
Google Chrome on Windows 10

**Comment by ildyria** [comment]
Most likely already fixed in the v4: https://github.com/LycheeOrg/Lychee-laravel
