### ISSUE TITLE
Feature request : albums inside an album

### ISSUE THREAD

**Issue by mrflos** [LycheeOrg/Lychee-v3#336]
### Detailed description of the problem
In the case of big photo libraries, it would make sense to be able to put albums inside another album (recursive album management)

### Steps to reproduce the issue
the issue is a feature request, but when you attempt to drag n' drop an album into another, it doesn't work

### Output of the diagnostics (Settings => Diagnostics)
not important for this usecase

### Browser and system
Firefox 73.0.1 / Linux debian 10

**Comment by d7415** [comment]
This is available in the [v4](https://www.github.com/LycheeOrg/Lychee-Laravel).

**Comment by mrflos** [comment]
nice will check v4! Thank for answering!
