### ISSUE TITLE
Duplicate+Move

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-v3#35]
From: https://github.com/electerious/Lychee/issues/650

> There is a button to duplicate a photo. If you do it on several photos then you have to move each to another album. It would be nice to have a **Copy to...** button to duplicate and move at once.

**Comment by jeyca** [comment]
How is it even possible to duplicate a photo? Cannot see a button for that function, is it removed in the current master version?

**Comment by ildyria** [comment]
@jeyca Isn't it right click on the picture -> Duplicate ?

**Comment by jeyca** [comment]
ah now I see, its in the overview, but there is no button when in picture view and context menu does not work there.

I just wanted to work a bit in the code, but how can I generate the main.js from the single *.js files? (I admit, this question is a bit offtopic here :))

**Comment by ildyria** [comment]
For generating the main.js, have a look here: https://github.com/LycheeOrg/Lychee/wiki/Build

Also for offtopic questions, you can join us on [gitter](https://gitter.im/LycheeOrg/Lobby). :)
