### ISSUE TITLE
multi-select without click and drag

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-v3#36]
From: https://github.com/electerious/Lychee/issues/649

This is a feature request for some method of selecting multiple photos or albums without needing to click and drag to select them (which you typically can't do from a touch interface). perhaps some sort of checkmark overlay button, similar to what google photos does? i'm not sure how complex this would be to implement, but it seems like it would all happen on the javascript side.

this change may also mean that the right-click option to take action on the selected pictures would need to move to a floating "Actions" button that appears when things are selected (although this may not be necessary depending on implementation).

**Comment by ildyria** [comment]
Currently implemented in a branch on Lychee-front.
Soon...

**Comment by ildyria** [comment]
done.

**Comment by Julianoe** [comment]
Probably not the place but just wanted to say that the click & drag, even though not instinctive (i had to search the github for a multi select option), is really genius. But clearly it's cool that you added another option :)
