### ISSUE TITLE
Is there any plan to include also videos ?

### ISSUE THREAD

**Issue by digitalwm** [LycheeOrg/Lychee-v3#4]
### Detailed description of the problem
I would like to have a way to import and display videos at least mpeg4 encoding and preferably into an HTML5 player.

If there is no plugin and If some support is provided to understand the logic of the app, I could develop this extension

### Browser and system

**Comment by hitam4450** [comment]
+1

**Comment by kelvinau** [comment]
+1

**Comment by meminens** [comment]
Yes please!

**Comment by knutole** [comment]
@electerious Who is maintaining this repo now? Since @digitalwm is offering to write video support, if only given some simple roadmap guidance, somebody should provide this for him. If no feedback is given, this project will die fast!

**Comment by LudovicRousseau** [comment]
This project is now maintained by @ildyria and me. I do not do development.
If you or @digitalwm wants to propose a patch to add video then be welcome.

**Comment by ildyria** [comment]
@knutole 

> if only given some simple roadmap guidance, somebody should provide this for him.

The code is actually pretty simple to read, and anyone can join the gitter (https://gitter.im/LycheeOrg/Lobby) and we will happily answer questions.

> If no feedback is given, this project will die fast! 

@LudovicRousseau and I are pretty active in responding to most issues. I'm doing development but adding support for video (https://github.com/LycheeOrg/Lychee/issues/4) , NEF files (https://github.com/LycheeOrg/Lychee/issues/69), PSD files (https://github.com/LycheeOrg/Lychee/issues/13) etc... is pretty low in my priority list.

**Comment by ildyria** [comment]
https://github.com/LycheeOrg/Lychee/commit/74a6cb9a7ddf10ce61ff27e74ddf707a596ff0eb Done. Big thanks to @clementlamoureux . :+1: 

Still thumbnails to solve but at least video are covered now.

**Comment by knutole** [comment]
@clementlamoureux Amazing job, thanks! Would it be possible to add `.mov` as well? I believe HTML5 supports this!

**Comment by clementlamoureux** [comment]
> @clementlamoureux Amazing job, thanks! Would it be possible to add `.mov` as well? I believe HTML5 supports this!

Thanks 😊 Apparently MOV H.264 file are supported as well, I will add It tomorrow 👍
