### ISSUE TITLE
Website link to outdated repo

### ISSUE THREAD

**Issue by chevalier-m** [LycheeOrg/Lychee-v3#40]
Hello.

Just to notify that the website link to the repository is related to the outdated repository.

That webpage: https://lychee.electerious.com/ .

I don't know who's able to fix that but once done feel absolutely free to close the issue.

**Comment by LudovicRousseau** [comment]
Exact.
We should try to host the website in a LycheeOrg project.

**Comment by ildyria** [comment]
I quickly created a copy of electerious website here: https://lycheeorg.github.io
The only thing I could not do was the [live demo](https://ld.electerious.com).

**Comment by LudovicRousseau** [comment]
We can keep using the original live demo.
Thanks @ildyria for the website copy.

I fixed the website URL in https://github.com/LycheeOrg/Lychee homepage.
