### ISSUE TITLE
Set properties uppon album creation

### ISSUE THREAD

**Issue by lenisko** [LycheeOrg/Lychee-v3#42]
It's only idea, how about allowing user to set properties from new album popup?

I mean `Hidden, Downloadable, Password protected` on this window

![2018-09-23_15-05-25-firefox](https://user-images.githubusercontent.com/10072920/45928331-1cfeaf80-bf42-11e8-80a2-db70ed1750b7.png)

Right now it's possible after creation of album, so technically someone could see `Hidden` album before we change it.

**Comment by ildyria** [comment]
> Right now it's possible after creation of album, so technically someone could see Hidden album before we change it.

**Technically no**, because **by default the album is not shared**. So it is not possible for someone to see a `Hidden` album. Album is shared only once the small eye goes orange.
