### ISSUE TITLE
Feature request: Amazon S3 implementation

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee-v3#44]
It would be good to store to Amazon S3.

**Comment by danbaron-fishwise** [comment]
Are there any other storage options besides the local EBS storage on AWS? No solution for S3? I have 1TB of images.

**Comment by d7415** [comment]
> Are there any other storage options besides the local EBS storage on AWS?

Lychee is designed for self hosting more than cloud hosting. If you make a PR we'll take a look, but it's not a high priority. I suspect it would be more easily added to Lychee-Laravel, but I'm not sure about that.

> No solution for S3?

Not yet, no.

**Comment by ildyria** [comment]
This repo is about the current version (v3) and as there is already an issue about it on the Laravel version (future v4). So I'm closing this.

Why this should be easier with Laravel: https://laravel.com/docs/5.8/filesystem

**Comment by danbaron-fishwise** [comment]
Where do I find the post/issue for v4 about using S3 storage? 
I have an installation on Laravel now, hosted on AWS. It's just not a viable solution without s3 storage. EBS is too expensive.

**Comment by ildyria** [comment]
@danbaron-fishwise the one you opened: https://github.com/LycheeOrg/Lychee-Laravel/issues/149
