### ISSUE TITLE
Database in addition to MySQL (PDO/SQLite)

### ISSUE THREAD

**Issue by oupala** [LycheeOrg/Lychee-v3#46]
Lychee currently requires MySQL to work. We'd like to see other db backends to be supported, like sqlite or PostGreSQL.

**Comment by ildyria** [comment]
This is not possible for the current implementation but the next big version will allow this quite easily as its implementation is database agnostic: https://laravel.com/docs/5.7/database
But it will be the user who will have to change the config as there are some files to edit.

**Comment by oupala** [comment]
Thanks for the update.

Can you tell us a bit more about the *next big version*?

**Comment by ildyria** [comment]
@oupala The *next big version* is available here: https://github.com/LycheeOrg/Lychee-Laravel
It is not official yet, there can be bugs in it. The version mysql is pretty stable.
Also I have not yet documented the installation process.

In summary it should be something in the following style:
```
git clone --recurse-submodules https://github.com/LycheeOrg/Lychee-Laravel.git
cd Lychee-Laravel
./composer install
./cp .env.example .env
# edit .env to reflect the database configuration
# also see here: https://github.com/LycheeOrg/Lychee-Laravel/blob/master/config/database.php
# you will need an existing user and database and the correct access right
# the following command will generate the table in the database.
./artisan migrate
```

**Comment by oupala** [comment]
Great news, I had not heard of this project.

Is it a full rewrite from scratch of Lychee?

**Comment by ildyria** [comment]
Not totally from scratch, but a big part of it yes. But it only is about the back end, the front end stays the same.

**Comment by zero77** [comment]
has SQLite been added to this version yet.

**Comment by ildyria** [comment]
It will NEVER be.

**Comment by ildyria** [comment]
@zero77 sorry for the abrupt answer. I was in vacation.
So to clarify. SQLite will never be integrated to Lychee v3 (which is why this issue is closed). However it has already been integrated into Lychee-Laravel (aka v4 candidate).

**Comment by zero77** [comment]
@ildyria 
ok no problem, are the install instructions up to date and is the instructions on using SQLite over mysql.

**Comment by ildyria** [comment]
Pretty much yes.
You will want to read: https://github.com/LycheeOrg/Lychee-Laravel/wiki/Install
and for the `.env` from https://laravel.com/docs/5.8/database
> ## SQLite Configuration
> After creating a new SQLite database using a command such as  `touch database/database.sqlite`, you can easily configure your environment variables to point to this newly created database by using the database's absolute path:
> 
>```
>DB_CONNECTION=sqlite
>DB_DATABASE=/absolute/path/to/database.sqlite
>```

You should not need to modify the [`database.php`](https://github.com/LycheeOrg/Lychee-Laravel/blob/master/config/database.php) file. :)

**Comment by zero77** [comment]
Ok thanks i will have a look

**Comment by ildyria** [comment]
if you have questions, don't hesitate to come back at us or drop by our gitter :)
