### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by uwealtmann** [LycheeOrg/Lychee-v3#47]
I want to do a localization of the user interface, which should be quite easy to do. But I can't find the strings in the code (maybe while I'm not a php-coder?).

May you give a hint?

**Comment by ildyria** [comment]
All the responsive part of the UI is available here: https://github.com/LycheeOrg/Lychee-front
I advise you to have a look at https://github.com/LycheeOrg/Lychee/wiki/Build

Strings are currently hard coded in the repo above and in [index.html](https://github.com/LycheeOrg/Lychee/blob/master/index.html) , it would be nice if the localization was received from the backend in php at the initialization cf [here](https://github.com/LycheeOrg/Lychee/blob/master/php/Modules/Session.php#L60).

Ideally it should be a config option in the admin panel where you select the localization you want and the array containing the localization strings is part of the payload when first loading the website.

**Comment by LudovicRousseau** [comment]
A good idea would be to use the HTTP ``Accept-Language`` header sent by the client as the _default_ locale.
See https://www.w3.org/International/questions/qa-accept-lang-locales

The backend can use the value to know what l10n to use. Unless the user specified another value for her account preferences.

**Comment by ildyria** [comment]
Work is mostly finished, we just need a window to allow the admin to select the languages he wants to use Lychee in. I will let someone else work on that.
Just sending a post request with function `Settings::setLang` with one of the code from `config['lang_available']` will change the default language. see https://github.com/LycheeOrg/Lychee/blob/master/php/Access/Admin.php#L304

**Comment by ildyria** [comment]
Done.
