### ISSUE TITLE
French localization is not complete.

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-v3#48]
I started working on it here: https://github.com/LycheeOrg/Lychee/blob/master/php/Locale/French.php
There are still quite a lot to translate.

If someone want to continue it and make a PR, (s)he will be welcome. :)

**Comment by arxcdr** [comment]
Hey there, I'm going to fork it and translate a few strings to help you out. I'm currently doing Hacktoberfest so this is a perfect task for me :) I don't know if I'll complete the whole thing but I should be able to do a good chunk of it at least!

**Comment by ildyria** [comment]
Thanks a lot !

**Comment by deatheguard** [comment]
Hi! I am currently participating in Hactoberfest as well, so I want to make myself useful :) I can complete it all with due time (several days) and I've already made some remarks.
