### ISSUE TITLE
Support an easy way to add custom links in the interface

### ISSUE THREAD

**Issue by suntorytimed** [LycheeOrg/Lychee-v3#5]
### Detailed description of the problem
In Germany you are required to add an "Impressum" i.e. legal notice to your page. Especially with the new GDPR rules (or DSGVO in Germany) it is necessary to point to those informations. Currently there is no way apart of manually hacking the index.html to add a custom link to the page. There was already an issue in the old repo: https://github.com/electerious/Lychee/issues/541 but my solution I posted there is a bit inconvenient (especially in a containerized setup).

It would be nice to have an easy way in the admin interface to add such a link to the page.
### Steps to reproduce the issue
not necessary as this is not a bug but a feature request
### Output of the diagnostics (Settings => Diagnostics)
not necessary as this is not a bug but a feature request
### Browser and system
not necessary as this is not a bug but a feature request

**Comment by AkselMeola** [comment]
Would an editable footer be ok ? 

E.g. From settings you could add some contact information. Might be usable for photo sharers to display author information and contact details. 

I propose something like this:

(cog) -> change contact info -> form:
 -> Contact line, e-mail (optional)  
 -> additional links (some text area)

Links could maybe be just a list with each of them on new line and an optional | to separate link title.
Or the text area could hold just custom embedded html.

**Comment by suntorytimed** [comment]
Sounds like a proper solution to me. I currently add it to my headline (https://photography.hibiki.eu)

**Comment by AkselMeola** [comment]
Ok. I have named the thing to a "Signature" and it will just support html content. Then user can do what ever he/she likes. 

In couple of days I have the pull request up and a small staging demo to verify the looks.

**Comment by timsn** [comment]
Is there any progress regarding this topic? I would really like to have such a feature. Otherwise it's really getting hard to run such a site in europe without any imprint information.

**Comment by ildyria** [comment]
No progress, I just thought of a simple way to do it, will do when I have some time available, and to be honest it will only be available on [Lychee-Laravel](https://github.com/LycheeOrg/Lychee-laravel) (because I won't back port things to the v3).
