### ISSUE TITLE
Hover-Over Blue Border/Square Highlights

### ISSUE THREAD

**Issue by Himself132** [LycheeOrg/Lychee-v3#51]
### Detailed description of the problem
Any way you could allow for more options than the effect where when you hover over an album or photo that it shows a blue highlighted square, or a series of angled squares?

Such options could be just as simple white border and no angled boxes, a drop-shadow, or some other simple options?  The minimalist feel of the display is lost in the blue angled squares in my opinion.

### Steps to reproduce the issue
NA

### Output of the diagnostics (Settings => Diagnostics)
NA

### Browser and system
NA

**Comment by ildyria** [comment]
@Himself132 if we add as a setting a text-box where we allow the admin to input their own CSS. Would that be satisfactory to you?

**Comment by Himself132** [comment]
Yes it would thank you
