### ISSUE TITLE
Keep account signed-in

### ISSUE THREAD

**Issue by meminens** [LycheeOrg/Lychee-v3#52]
### Detailed description of the problem
After each browser restart, my Lychee account signs out. All other accounts stay signed in (e.g. Reddit, Gmail, Twitter etc.).

### Steps to reproduce the issue
1. Sign in to Lychee account
2. Close Firefox
3. Open Lychee Albums URL
4. Unable to see private photos because Lychee account is signed out
5. Sign back in again by entering account credentials

### Output of the diagnostics (Settings => Diagnostics)
```Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  
DB Version:      update_030109
System:          Linux
PHP Version:     7.2
MySQL Version:   50723
Imagick:         1
Imagick Active:  1
Imagick Version: 1687
GD Version:      2.2.5
Plugins:         
```

### Browser and system
Firefox on Mac

**Comment by ildyria** [comment]
I just pushed a new function only accessible for user connected. Once connected visit:
`<domain>/php/index.php?function=phpinfo`
 It will display the `phpinfo()`.
Here you will be able to see a line with `cookie_lifetime`, it is currently set to 0, in other word the session ends when you close your browser.

If you want to extend the session lifetime, edit [index.php#L40](https://github.com/LycheeOrg/Lychee/blob/master/php/index.php#L40):

Just before the
```php
session_start();
```
add:

```php
ini_set('session.cookie_lifetime', 60 * 60 * 24 * 7);  // 7 day cookie lifetime
```

**Comment by meminens** [comment]
`phpinfo` URL doesn't work for me. Am I missing something? What do you mean you "pushed a function"? Do I need to update my Lychee installation first by running `git pull`? Sorry for all the questions. :)

![image](https://user-images.githubusercontent.com/42714627/46293952-ad507c00-c562-11e8-84e9-1305147aa757.png)

**Comment by ildyria** [comment]
> Do I need to update my Lychee installation first by running `git pull`?

Yes. :)

> Sorry for all the questions. :)

No worries.

**Comment by meminens** [comment]
Thanks for your patience!

`git pull` tells me I made changes to `Admin.php` but I don't recall modifying any files manually. What do I do?

![image](https://user-images.githubusercontent.com/42714627/46294217-41224800-c563-11e8-8f0c-a03a800f7945.png)

**Comment by ildyria** [comment]
I would suggest to move this discussion in https://gitter.im/LycheeOrg/Lobby :)

If you do
```
git status
```
You will see the files that have been modified.

```
git diff
```
Will show the differences between your local version and the `master` when you last pull it from the repo.

You can now either do:
```
git checkout -- php/Access/Admin.php
git pull 
```
This will erase any changed you made in `Admin.php`

Or you can do:
```
git stash
git pull
git stash pop
```
Which hopefully will temporarily _save_ the changes made in `Admin.php`, pull from the repo and redo the changes.

**Comment by meminens** [comment]
OK will do. It's just odd that `git status` shows changes in almost all the files. I didn't make any changes to any of the Lychee files. Something must have gone wrong. Thanks. Stashing and pulling worked.

**Comment by meminens** [comment]
Issue persists even with `ini_set('session.cookie_lifetime', 60 * 60 * 24 * 7);  // 7 day cookie lifetime`

Thougths?

Cookie local value shows as `604800`

![image](https://user-images.githubusercontent.com/42714627/46320992-e7e00600-c5ae-11e8-841c-bef1c469c1e3.png)

**Comment by ildyria** [comment]
> Thougths?

None, it seems it needs more implementation server side...

**Comment by meminens** [comment]
OK I will look into it. Gotta learn how to configure cookies first on my server but that's out of scope. Thanks.

**Comment by ildyria** [comment]
@bisherbas by server side I meant in the `php` code. :)

**Comment by meminens** [comment]
Oh I see. Because I spent hours configuring my server's side. All other apps are running justs fine (e.g. Shaarli, NextCloud, BookStack etc.). Having problem with Lychee only. If you point me into the right direction (e.g. what files to modify), I might take a shot at it. But I am not an expert PHP coder. Be aware! :)

**Comment by ildyria** [comment]
Creation of the sessions is done here:
https://github.com/LycheeOrg/Lychee/blob/master/php/index.php#L40

The management of the Session (user connected etc) is done here:
https://github.com/LycheeOrg/Lychee/blob/master/php/Modules/Session.php

**Comment by meminens** [comment]
Thanks! I will have a look.

**Comment by meminens** [comment]
@ildyria 

Let me know what you think of  #70

**Comment by ildyria** [comment]
Close thanks to @bisherbas with https://github.com/LycheeOrg/Lychee/pull/70 :+1:
