### ISSUE TITLE
api function session::init leaks server information

### ISSUE THREAD

**Issue by jeyca** [LycheeOrg/Lychee-v3#56]
The api function `session::init` leaks the information of the lychee installation in the server filesystem (for example `/var/www/lychee`). I don't know why that is necessary and this can possibly lead to security problems but is definitely no information that should be given to visitors.

PS, just because I gues someone will say

> "But its only visible for logged in users!"

yes indeed, but because there is currently only this one-account option everyone I want to give the option to upload and share photos can get this server information

**Comment by ildyria** [comment]
There reason is as follows:
```php
// Path to Lychee for the server-import dialog
$return['config']['location'] = LYCHEE;
```

**Comment by ildyria** [comment]
solved in Lychee-Laravel.

**Comment by ildyria** [comment]
See https://github.com/LycheeOrg/Lychee-Laravel for alpha version.
