### ISSUE TITLE
New API For Lychee Android App?

### ISSUE THREAD

**Issue by RalphPfeiffer** [LycheeOrg/Lychee-v3#58]
Do you think that the new API will be great for creating a Lychee Android app?

**Comment by ildyria** [comment]
The new API is design to allow the current front end to move to:
https://github.com/ildyria/Lychee-Laravel
(when it will be ready for production).

The current API or v2 does not matter. What matters are the POST request you are sending to the server and the json you get as a result.

A Lychee Android App would just be "another" front end. :) As long as the App and the server are on the same page (API) then it will work.
