### ISSUE TITLE
Bugs when you have large amounts of photos

### ISSUE THREAD

**Issue by kaskajp** [LycheeOrg/Lychee-v3#6]
### Detailed description of the problem
If you have a lot of files with similar filenames, for example a date prefix like 2018-06-20, the search breaks when you search for "2018", just completely freezes the browser tab.

Same thing happens with the recent uploads smart album, I uploaded 1600 items today and when I click on the recent album the browser tab freezes.

### Steps to reproduce the issue
Upload a lot of photos (1500+) and access the recent album, or upload files with the same prefix/suffix and search for them.

### Output of the diagnostics (Settings => Diagnostics)
**Diagnostics**
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
No critical problems found. Lychee should work without problems!

**System Information**
Lychee Version:  3.1.6
DB Version:      030102
System:          Darwin
PHP Version:     5.6
MySQL Version:   50638
Imagick:         -
Imagick Active:  1
Imagick Version: -
GD Version:      bundled (2.1.0 compatible)
Plugins:         

### Browser and system
macOS running Safari 11.11.1 or Chrome 67

**Comment by kaskajp** [comment]
As a temporary fix I've added hard limits to the queries in search.php, Album.php and Albums.php. This mostly works as a solution for my situation but obviously breaks some key functionality, like the context menu as the album you want to move a photo to might not be shown in the list. A searchable context menu might be something to look at.

**Comment by AkselMeola** [comment]
I might take a look into it.

**Comment by ildyria** [comment]
Could not reproduce (with 1700 pictures).

![nobug](https://user-images.githubusercontent.com/627094/49093106-b6f51800-f263-11e8-8ceb-e5702bfcac07.png)

I guess the limitation mostly comes from the browser rather than Lychee.

**Comment by d7415** [comment]
A little slow but working on Chromium 70 on Linux with >5000 photos. I agree that it's probably client-side.

**Comment by hsousa** [comment]
I have 750 photos on an album and the (Safari) tab is completely frozen.

This definitely sounds browser related as it works great with Firefox.

Still, 700 photos in an album isn't an extreme scenario by any stretch...

**Comment by hsousa** [comment]
Hi @ildyria, I'm looking at your commit (https://github.com/LycheeOrg/Lychee/commit/82f3ab15b3440adc58b55620daf4028460c5ad92). How do I go about testing this on my setup?

I'm currently running Lychee on linuxserver's docker container, and I can't figure out the `requires 'artisan migrate', setting in 'advanced section'` bit.

Help? 😄

**Comment by ildyria** [comment]
Oups. The `artisan migrate` was actually for the [Alpha/Beta version of Lychee v4](https://github.com/LycheeOrg/Lychee-laravel) as we don't have automatic updates of the database on it (as opposed to in Lychee v3). 

As for the setting, you can access it via the **More** button in the settings (also where you need to validate **I take the risk** thing).

**Comment by hsousa** [comment]
Ah, I see.

Wait, so this change is not present on 3.2.12?

I just tried out a clean install of that version, uploaded all the photos, let them process, and still have the same issue on Safari. 😭

**Comment by ildyria** [comment]
Actually... it is related to this: https://github.com/LycheeOrg/Lychee-laravel/issues/6 ... Sorry. :s

**Comment by ildyria** [comment]
We need to add a pagination system yes.

**Comment by hsousa** [comment]
Ah, so different #6, my bad! 😅 

It's frustrating because it works flawlessly on Firefox, but just freezes on Safari 😭

**Comment by hsousa** [comment]
FWIW, it works great on Safari for iOS 🤔

**Comment by ildyria** [comment]
somewhat duplicate : https://github.com/LycheeOrg/Lychee-Laravel/issues/251
