### ISSUE TITLE
All the albums are password protected

### ISSUE THREAD

**Issue by Guimik** [LycheeOrg/Lychee-v3#61]
Hi !
Since the today 'git pull' all the albums are password protected even if they are in public mode.
![capture](https://user-images.githubusercontent.com/31242178/46915146-d1bb4800-cfa7-11e8-9568-acec78da8acf.JPG)
When I click on Cancel: Error Function not Found ! Please check the spelling of new function 

From the diagnostics page:
System Information
------------------
<br />
<b>Warning</b>:  file_get_contents(/Lychee/src/package.json): failed to open stream: No such file or directory in <b>/Lychee/plugins/Diagnostics/index.php</b> on line <b>119</b><br />
Lychee Version:  
DB Version:      update_030109
System:          Linux
PHP Version:     7.2
MySQL Version:   50505
Imagick:         1
Imagick Active:  1
Imagick Version: 1687
GD Version:      2.2.4

thx for reading me

**Comment by ildyria** [comment]
I will check this tonight.

**Comment by ildyria** [comment]
this should be solved now.

**Comment by Guimik** [comment]
Works fine, thanks !
