### ISSUE TITLE
Broken ZIP support or error in supported files

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee-v3#64]
Recently, I noticed that I can attempt to upload ZIPs to Lychee without changing "supported files" to "All Files" in the file selector; does this mean ZIPs are supposed to be supported for uploading in Lychee? If so, it seems to be broken, Lychee will claim the file type is not supported after uploading. For clarification, the ZIPs tested are ZIPs Lychee itself created from downloading an album. If they are not supported after all, the "supported file types" may need to be updated.

**Comment by ildyria** [comment]
> does this mean ZIPs are supposed to be supported for uploading in Lychee? If so, it seems to be broken.

Upload only supports pictures. cf here:
https://github.com/LycheeOrg/Lychee/blob/master/php/Access/Admin.php#L231
https://github.com/LycheeOrg/Lychee/blob/master/php/Modules/Photo.php#L44

```php
	public static $validTypes = array(
		IMAGETYPE_JPEG,
		IMAGETYPE_GIF,
		IMAGETYPE_PNG
	);
	public static $validExtensions = array(
		'.jpg',
		'.jpeg',
		'.png',
		'.gif'
	);
```

> If they are not supported after all, the "supported file types" may need to be updated.

Well it is actually already set:
```html
	<input id="upload_files" type="file" name="fileElem[]" multiple accept="image/*">
```

From: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-accept
> #### accept
> If the value of the **type** attribute is `file`, this attribute indicates the types of files that the server accepts — otherwise it's ignored. The value must be comma-separated unique “content type specifiers”:
> - A case-insensitive file extension starting with the STOP character (U+002E). (e.g. .jpg, .png, .doc).
> - A valid MIME type with no extensions.
> - `audio/*` representing sound files. HTML5
> - `video/*` representing video files. HTML5
> - `image/*` representing image files. HTML5

**Comment by ghost** [comment]
Ah, okay. It must be a fault of Dolphin (KDE Plasma's file system manager) not respecting supported file type declarations correctly. 

Thanks!
