### ISSUE TITLE
How do I migrate from electerious to LycheeOrg?

### ISSUE THREAD

**Issue by lord-carlos** [LycheeOrg/Lychee-v3#65]
Hello

I currently have a Lychee from electrious (2a8b1f9ec2ec488b32571a0eb316a75bc90b5683) running.

Can I just change the git address and do a pull? Or is there more to it?

Thank you.

**Comment by ildyria** [comment]
You might want to back up your installation (especially the database) before but this should not break _that much_... 

I will try to write a quick guide of how to migrate from Electrious to LycheeOrg.
In theory it would just need to change the git remote origin url but we have not integrated the position field yet so we have a small conflict there...

The quick and dirty version would be:
```sh
cd ..

# back things up
mv Lychee Lychee.bck 

# reinstall Lychee (notice the recurse!!)
git clone --recurse-submodules https://github.com/LycheeOrg/Lychee.git

# copy the two main folders
cp -r Lychee.bck/uploads/* Lychee/uploads/
cp -r Lychee.bck/data/* Lychee/data/

# pray the Lord it worked and access the website.
```

**Comment by lord-carlos** [comment]
Seems to have worked. Thanks

**Comment by ildyria** [comment]
You should check creating albums, adding pictures, duplicating pictures.

**Comment by lord-carlos** [comment]
Mhh, yeah I can't upload pictures.
`An upload-folder is missing or not readable and writable!`

But
`drwxrwxr-x 6 XXX XXX 4096 Oct 16 19:44 uploads`
should be writeable. 
Creating album works.

**Comment by ildyria** [comment]
Did you check the ownership of the folders ? uploads access may be correct but not the folders inside.

This should make sure of it:
```sh
chmod -R 775 uploads
```

**Comment by lord-carlos** [comment]
`sudo chown -R www-data:XXX uploads/ data/`
This did the trick 👍 

Thanks everybody for you help and this great software :)
