### ISSUE TITLE
Make available as an app for Nextcloud

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee-v3#66]
Hello,
I think it would be great if Lychee could be made as an app for Nextcloud. Lychee is very good and has features like support for exif and tags. It's also rather fast. The built in gallery app in Nextcloud has many limitations and is very slow.

**Comment by ildyria** [comment]
Duplicate: https://github.com/LycheeOrg/Lychee/issues/39

**Comment by ghost** [comment]
Don't see how #39 is a duplicate. That issue is about reading or importing from nextcloud (webdav), whereas this issue is about making Lychee into an integrated app. The advantage is that it could be available on their app store and thus very easy for users to install. I do understand if this is way out of scope.

**Comment by ildyria** [comment]
Then this is completely unrelated to Lychee. Lychee is a PHP server to manage your gallery coupled with a front-end in Javascript. A PHP server cannot be run as an app as this has to be run on the server (thus on the nextcloud part).

If what you would like would be an app mimicking  Lychee frontend/visual. Then this is also not related to this repository by definition. But should you be interested in creating an app for Nextcloud with Lychee look and feel, then you can join us and create a new project within the organisation. :)

**Comment by ghost** [comment]
Nextcloud is a self hosted cloud platform based on PHP and apps are basically some php code snippets that use the Nextcloud api and Web interface to extend its functionality. There are plenty of different type apps from note taking, file manager, calendar, mail, mind maps, and so on. 

I thought that this would increase the user base quite a bit since there are millions of NC installations all over. 

I wish I could help, but I lack the necessary skills to program in PHP and JS :( Do appreciate the efforts with Lychee as it is though!

**Comment by ildyria** [comment]
My mistake, I though it was proprietary. :/

Anyway, even though it would be interesting for next cloud user, given this would be an app, I think it would be better on its own repository. :s 

I am currently the sole developer and I am working on a few features at the same time (admin dashboard, sub albums, multi users, search by tag and time?) while also migrating to the Laravel framework (cf: https://github.com/ildyria/Lychee-Laravel) for more flexibility... So you can guess that nextcloud would not be my priority. :/

**Comment by LudovicRousseau** [comment]
Maybe a better idea is to improve the Nextcloud gallery application.
For better Nextcloud gallery performance Redis is recommanded https://github.com/nextcloud/gallery#improving-performance (but I have not tested that myself).

I don't think Nextcloud and Lychee have the same target. For example it is not possible to provide a public gallery (visible without an account) using Nextcloud (or I could not find how to do that).

**Comment by karlitschek** [comment]
Hi, Frank from Nextcloud here. Some kind of integration would be great. Not sure what makes sense. But ideas are super welcome! Cheers Frank

**Comment by hitam4450** [comment]
I would suggest to upgrade the gallery app to be used as frontend to the lychee server
or to develop an new standalone app ... like LycheeNext!

Have a great day!

best regards, hitam4450
