### ISSUE TITLE
How secure is Lychee?

### ISSUE THREAD

**Issue by bigfoot50** [LycheeOrg/Lychee-v3#68]
Hi,

First, great work guys! Lychee a really great tool to organize all my pictures!

I know, strange question :-)
But how secure is Lychee? Is there any security gaps? I will open my Lychee installation to the internet.
All Server security configuration are done (permissions, SELinux, safe Passwords, firewalling,...).

Regards

**Comment by ildyria** [comment]
Hi,

If we knew about the security gaps, we would fix them... If someone find a security problem, I would be happy that they report them. Also from a paranoiac point of view, any PHP app is *insecure*.

My Lychee (Laravel version) is open to the internet and I never had any problems with it.

Should you really want to be sure, you can still run a virtual machine in which you have Lychee with a proxy via Apache forwarding to the VM. You will lose some information on logs (ip addresses of connection tentative) but should Lychee be compromised, your attacker will also need to escape the Virtual machine.

**Comment by ildyria** [comment]
I will close this issue as this is more a discussion topic from a semantic point of view.
If someone fine a security flaw, I sure hope he will open an issue.
