### ISSUE TITLE
Nikon NEF support

### ISSUE THREAD

**Issue by jahurtado** [LycheeOrg/Lychee-v3#69]
Hi guys,

I am hobbyist to photography and I was searching for a self-hosted solution to keep all my photos stored and organized.

Lychee is perfect, because I can upload my photos to a server and organize them at any moment with the smartphone or the iPad (it is difficult for me to have time to sit down in front of the computer and organize the files manually).

However, with my Nikon I normally shoot in RAW format (NEF) in order to post-process them later at maximum quality.

I did some changes to support them in Lychee. The code may not look good (I have never written code in PHP) but I think is an approach that just works and perhaps somebody could take the idea in order to implement in a good way.

If somebody wants to test it I created a Dockerfile ready to build and use it:
https://github.com/jahurtado/docker-lychee-nikon-nef

The code is here:
https://github.com/jahurtado/Lychee

Regards,
Jose.

**Comment by Shrinks99** [comment]
Could this be relatively easily duplicated to other RAW formats as well?

**Comment by jahurtado** [comment]
> Could this be relatively easily duplicated to other RAW formats as well?

Yes I think so. The approach is to use imagemagick to convert the RAW format to JPG medium-size paying attention to the file extensions. So it would be easy to replicate to other formats.

**Comment by ildyria** [comment]
@jahurtado I am not really a fan of the exec method. But if imagick is used to generate big, medium, thumb image. then I am totally up for it. However I am not sure if the server should keep the raw or not (place taken...) but it could be an option.

If someone makes a pull request with those (using imagick and optionally saving raw files in an `upload/raw` folder) then I will merge it.

Quick example:

```php
$im = new Imagick( 'source.CR2' );
$im->setImageFormat( 'jpg' );
$im->writeImage( 'result.jpg' );
$im->clear();
$im->destroy();
```

**Comment by Shrinks99** [comment]
I would personally prefer it keep the RAW file and let users download that one while just displaying the JPEG (or give users the option to delete it).  I'm planning to use Lychee in the future for my family's photo collection and would definitely like to save Camera RAW / TIFF files!

**Comment by expiredemulsion** [comment]
Would it be possible to let exiftool extract the embedded jpegs from the raw and use them for previews. 

That way we would be the proper white balance, colour profiles, lens corrections and other adjustments included in the jpeg. 

Or if imagick have that possibility.

**Comment by ildyria** [comment]
Duplicate with https://github.com/LycheeOrg/Lychee-Laravel/issues/284
