### ISSUE TITLE
[Feature] Remove Metadata

### ISSUE THREAD

**Issue by lanaschuhmacher** [LycheeOrg/Lychee-v3#7]
Is it possible to remove the metadata from specific images and/or from all images within a folder?

**Comment by fly-man-** [comment]
What would be the added value to removing the metadata from an image ?

If an image has metadata, we only display it. When you want to remove it we'd have to rewrite the file which can be done but would need additional checks

**Comment by lanaschuhmacher** [comment]
I do not want the location on pictures in a shared album for example.

**Comment by LudovicRousseau** [comment]
I think that what @fly-man- wrote is that you can use another tool to remove any metadata you don't want to show.

You can use any EXIF management tool for that. For example the exif command line tool https://libexif.github.io/

**Comment by lanaschuhmacher** [comment]
Thanks for the clarification, @LudovicRousseau 😅

**Comment by LudovicRousseau** [comment]
Lychee is not the correct tool for what you propose.
