### ISSUE TITLE
Can I use existing files without Lychee restructuring them

### ISSUE THREAD

**Issue by jbreitbart** [LycheeOrg/Lychee-v3#72]
Can I use Lychee to present photos that I have already sorted in path like `../album_name/xxx.jpg` or will Lychee have to restructure/rename all the files?

Background of the question is, that I have ~100GB of pictures that are available over samba and I can mount it on my webserver, but I don't want the photos to be copied to the server and have Lychee change the names as I also use it in other places.

**Comment by ildyria** [comment]
In its current state, no, you cannot do that with Lychee.

However it would be interesting to integrate such functionality in the future (low priority).

**Comment by ildyria** [comment]
In short term, another *simple* way to do it would be to create another version of Lychee (just the backend, the front-end would not need to be modified) that parse your folders and generate the appropriate SQL database.

**Comment by LudovicRousseau** [comment]
You can do that using PhotoShow

https://github.com/thibaud-rohmer/PhotoShow
