### ISSUE TITLE
Not able to get past database connection screen :(

### ISSUE THREAD

**Issue by widert** [LycheeOrg/Lychee-v3#73]
I am not able to get past the first database connection screen.

I have created a mysql user but not able to connect.

Server running Ubuntu Server 18.04

Trying from both Safari and Chrome.

**Comment by ildyria** [comment]
Can you please look at https://github.com/LycheeOrg/Lychee/issues/23 and check if this helps. :)

**Comment by widert** [comment]
Yes, that helped, brilliant, thank you!
