### ISSUE TITLE
"No public albums" shows when not logged in, despite photos being in the Public album

### ISSUE THREAD

**Issue by corrilan** [LycheeOrg/Lychee-v3#76]
### Detailed description of the problem
I would like to give the public access to images stored in the default Public album (Smart Album) which contains photos.  I can see the Public album when logged in but when not logged in the message "No public albums" shows instead of the actual Public album.  I have found no mention of any configuration change required to allow this.

### Steps to reproduce the issue
Go to Lychee home page, do not login, The eye icon and "No public albums" appears

### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
No critical problems found. Lychee should work without problems!
System Information
------------------
/var/www/www.mywebsite.com/Lychee/Lychee-front/package.json not found. Please do: git submodule init ; git submodule update
DB Version:             update_030109
System:                 Linux
PHP Version:            7.2
MySQL Version:          50724
Imagick:                -
Imagick Active:         1
Imagick Version:        -
GD Version:             2.2.5
Plugins:                
```

### Browser and system
Mozilla Firefox and Google Chome on Ubuntu Linux.

**Comment by ildyria** [comment]
Pictures in the `Public` folder are pictures marked as Public alone (but not the Album which contains them). In order to access them you need to give the direct link provided in the sharing menu.

I would suggest you to create a _public_ album and place those picture in it and then share that album. (You can duplicate those pictures and place them in this _public_ album).
