### ISSUE TITLE
Feature: Subalbums

### ISSUE THREAD

**Issue by haivala** [LycheeOrg/Lychee-v3#78]
There is a branch subalbums already.
Is anyone working on getting it merged?

**Comment by ildyria** [comment]
I am currently working on a new back end for Lychee with Laravel. The front end stays the same.

So far I just finished implementing the multi-users and the sub albums is my next target.
This will be added to the next big release (4.0).

**Comment by ildyria** [comment]
Mostly finished it on Lychee-Laravel. Still need some finalization. :)

**Comment by rnwgnr** [comment]
Can this Laravel-version of Lychee be found anywhere for testing?

**Comment by ildyria** [comment]
@guzzisti https://github.com/ildyria/Lychee-Laravel

It is still work in progress but currently proposes:
- better infrastructure (Model-View-Controller)
- sub-albums
- users (with or without upload access) and sharing between them (but the sharing interface could be improved...)
- justified layout (by default, will be an option soon).

**It lacks the search functionality** (for now).

I aim it to be Lychee.4.0.0, and the current implementation of Lychee will be transfered to Lychee-Legacy or Lychee-Classic.

**Comment by ildyria** [comment]
See https://github.com/LycheeOrg/Lychee-Laravel for alpha version.
