### ISSUE TITLE
Internal links need updating

### ISSUE THREAD

**Issue by humantex** [LycheeOrg/Lychee-v3#79]
I had an issue with a freshly installed site and used the built-in links to find answers. It turns out that both of them are still pointing to the old repository.

Namely, the links for "Hosted by Lychee" on the public front-end, and "About Lychee" on the Gear/Settings menu don't lead to the new LycheeOrg project pages.

**Comment by d7415** [comment]
In my fresh install those links are both correct. Did you install from master?

**Comment by humantex** [comment]
Yes... "Lychee-master.zip". The internal sub folders are all dated as: June 12 2018.

**Comment by humantex** [comment]
I just grabbed a new one, and the folders show: Nov 7 2018.

Something tells me I may have ended up with a previous release. If that's the case, then I can easily clear everything and reinstall.

**Comment by d7415** [comment]
Ah, ok. Yes, I think the updates were more recent than that, but they have been updated.

Where did you get that zip file? "Installing from master" usually means from git, or a zip of the git repository.

If you're not comfortable with git, click on "[Code](https://github.com/LycheeOrg/Lychee)" and you will find links to "Clone or download" which has an option for a zip of master, or you can click on "[Releases](https://github.com/LycheeOrg/Lychee/releases)" to get a [zip](https://github.com/LycheeOrg/Lychee/archive/master.zip) of the latest release (which might still not have this fix, but may be more up to date than what you have)

Edit: You beat me to it...

**Comment by humantex** [comment]
On where I got the file....? I can only assume I got it from Git's project page as a 'download zip' I don't usually make the assumption that there's anything newer on the 'releases' page, and I don't download "unofficial" files without a really good reason. Could I have gotten a pre-LycheeOrg version? I suppose that might be possible, but the version on the login says 3.1.6, and according to the release page, that's correct, yes?

Since I have one easily replaceable album created, I might as well just dump it all and start fresh. Once I do that, I will also look at the install and see if any of the recent updates have affected the other 2 'issues' I added today. It anything has changed, I'll come back and modify my comments for those too.

**Comment by d7415** [comment]
An electerious version sounds likely, as that repo shows "Latest commit 2a8b1f9 on Jun 13". "Download zip" from the main page should download whichever branch you're viewing (usually master). The latest "release" through that process is 3.1.6, but the latest in code is 3.1.9. I *think* (I'm new here) that minor versions are for each change of database structure.

I get the impression that Lychee is expected to be run from master (though I'm happy to be corrected if I'm wrong!)

**Comment by d7415** [comment]
Upgrading should be straightforward if you don't want to start from scratch.
[This](https://github.com/LycheeOrg/Lychee/wiki/How-do-I-migrate-from-electerious-to-LycheeOrg%3F) page is about migration. I think Lychee automatically detects changes needed to the database and handles them itself (again, I may be wrong here. I'm new).

That guide uses git (rather than zips), but the principle is the same.

**Comment by humantex** [comment]
Well... dumping the files and uploading fresh gives me an error when opening the site to do an install.

The error is about running composer to install dependencies. I don't have easy access to composer through my host. Suggestions?

**Comment by d7415** [comment]
You don't necessarily need composer, but you may well need the dependencies... I'd be a little surprised if anything vital has been added since the move to LycheeOrg, but I haven't looked.

Does it say which dependencies are missing?

**Comment by humantex** [comment]
No... it's a quickly appearing and disappearing error that only says:

`Error: please install dependencies with composer "composer update" `

**Comment by d7415** [comment]
Ah. php-ffmpeg has been added (today!). That's probably the one... If the website otherwise works then I'd ignore it. Otherwise the project may want to decide whether that should be optional.

**Comment by humantex** [comment]
Here's the exact error shown in FF's dev console...
```

Object { description: "please install dependencies with composer: `composer update`", params: {…}, response: "Error: please install dependencies with composer: `composer update`" }
main.js:2778:2
lychee.error
https://testbed.lumiworx.com/dist/main.js:2778:2
success
https://testbed.lumiworx.com/dist/main.js:912:4
u
https://testbed.lumiworx.com/dist/main.js:2:27452
fireWith
https://testbed.lumiworx.com/dist/main.js:2:28202
k
https://testbed.lumiworx.com/dist/main.js:2:77649
n/<
https://testbed.lumiworx.com/dist/main.js:2:79907
```

**Comment by humantex** [comment]
Ignoring the error doesn't let me complete the setup. Here's the site as-is, without even getting to the setup screens... https://testbed.lumiworx.com

**Comment by d7415** [comment]
The code does look like composer is a requirement... Which, while technically is covered by the system requirements, is more than a little annoying when the requirements should be attainable through other means.

Everyone needs 99 copies of every library... :disappointed: 

Edit to add: Imagemagick as optional, composer (and through it ffmpeg) as compulsory seems a **very** strange way to set up a photo gallery...

**Comment by d7415** [comment]
It's probably worth renaming or replacing this issue, as it's moved quite a lot from the original topic.

**Comment by humantex** [comment]
At this point it might be worthwhile to mention something after reading the 'migration' page you posted earlier. With my hosting setup - and presumably most other's who use shared hosting - there's no default access to either a Linux user command line or composer prompt, or any means to run 'internal' commands.

In my case, I can (at extra cost) set up SSH to run composer commands on my hosting account - but - it's not something I'm likely to do for a simpler script that won't be generally used by the public at large. There are other scripts to use if needed, and I don't like the idea of a potential security issue if someone manages to crack the newly-accessible SSH door that's now open..

If the new installation of the latest version has a requirement that I'd need to access anything other than a browser to install and manage it, then I'd probably go back to the earlier version and hack some code myself to do some minimal fixes - or - install something else.

For any new users who are starting fresh, it may be wise to alert them of the new requirements that would preclude them from using it in a regular shared hosting account setup.

**Comment by d7415** [comment]
Yes. I've added a comment to the commit (e5a2925b29cd5b520d47175453a437dc6984c8e9) (which didn't even mention composer...)

You should be able to use any version before today (the requirement was added about 8 hours ago) e.g. [here](https://github.com/LycheeOrg/Lychee/tree/912e2eb9fd7741ce23b2eec78840012187a5d2d6). Alternatively, I think [these](https://github.com/LycheeOrg/Lychee/blob/master/php/index.php#L21-L26) are the lines that need removing. Removing the checks may cause breakages on any new functionality (e.g. generating video thumbnails).

As for new users, composer is now mentioned on the [installation](https://github.com/LycheeOrg/Lychee/wiki/Installation) page, but again that was only added today...

**Comment by humantex** [comment]
Okay.... I commented out lines 21-26, and was able to complete the install - then add an album and 16 images into it. I'll leave it as-is and otherwise watch the project's progress.

You're absolutely correct about running far off topic, so I'll leave it up to you to modify, rename, delete the issue. Thanks for the quick help and responses to what's turned out to be a few twists and turns in direction. I appreciate the assistance.

**Comment by d7415** [comment]
> I'll leave it up to you to modify, rename, delete the issue.

I'm not a maintainer, so I'll leave it to them :smile:

**Comment by LudovicRousseau** [comment]
I started a new issue at https://github.com/LycheeOrg/Lychee/issues/85

Closing this one.
