### ISSUE TITLE
Unable to edit settings table in database

### ISSUE THREAD

**Issue by humantex** [LycheeOrg/Lychee-v3#80]
When using cPanel's currently supplied phpmyadmin, there's an error notice shown when attempting to browse, and then edit, the 'lychee_settings' table... 

`Current selection does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.`

If editing the DB is the only way to modify these settings, at least one unique PRIMARY index is required, or phpmyadmin will block all attempts to change any values. I doubt that most users would know how to either add a new index, or run SQL commands, so an update to the table structure in a future update would solve the issue.

**Comment by ildyria** [comment]
The thing is you don't need to change 99% of the other parameters than the one already supplied.
I'll make an advance edit panel, but I will deny any responsibility if you break your Lychee (a bit like the `about:config` of Firefox)

**Comment by humantex** [comment]
The 1 value that I wanted to try changing was the Imagick toggle. I have ImageMagick 6.7.2 loaded on my host, and the script doesn't see it as installed, even though the docs suggest that it can be used and substituted when it's available. Running diagnostics will show that it apparently wasn't detected.

There's no other option in changing that value according to Lychee's docs, and no setting toggle in the site's admin panel. The only way to modify a DB for anyone who's hosting account uses cPanel, is to use phpmyadmin, and it will not allow the edit. Having a new setting option for the admin will certainly offer a way to make that change without messing with any DB table values.

The reason I suggested that a proper index be added to the table was not only for the sake of editing it's values... Having an index on every table insures that there won't be any issues in running dumps on mysql data for backups, migrations, or maintenance, when the only tool available is phpmyadmin. In the 30+ years of doing web work, I've had multiple issues with missing data that's not retrievable if the original tables are deleted or corrupted beyond repair where the provider has to use a cli prompt to rescue original data because their only user-available tool isn't capable as it is

I'm only suggesting that you'd follow common practices and add an index with unique values - even if it only has one entry in the entire table.

**Comment by ildyria** [comment]
> the docs suggest that it can be used and substituted when it's available. Running diagnostics will show that it apparently wasn't detected.

have you installed `php-imagick` ?

> I'm only suggesting that you'd follow common practices and add an index with unique values - even if it only has one entry in the entire table.

This is already the case in Lychee-Laravel.

@humantex As it seems to only be a database issue (table configuration) and not the request for a panel would you mind if we close this issue and wait for the next big iteration?

**Comment by humantex** [comment]
I personally haven't installed any libraries or php extensions, but the standard ImageMagick library is available on my host to any/all php calls, as well as GraphicsMagick 1.3.25 and the bundled 2.1.0 version of GD. I also run a Koken site and it sees all 3 as selectable image processors.

If it helps any - The primary locations to run graphics commands to are: /usr/bin/convert and /usr/bin/identify for everything but GD I think. I may be able to dig through Koken's code and find out how it detects what's available. The one exception is that Koken doesn't see their ffmpeg install at all, but it has no trouble finding the others.

As for closing this until the next version... Sure. There's no reason to keep it open with plans to modify things in a future release.

**Comment by ildyria** [comment]
Actually solved with release 3.2.8
