### ISSUE TITLE
Request: Add a "version" file to web root

### ISSUE THREAD

**Issue by humantex** [LycheeOrg/Lychee-v3#81]
It would be really helpful to have at least one single text-readable file that has the currently installed Lychee version number information written in it. The core code files have nothing in them as a versioning header block to check for release numbers, so something placed in an obvious location would give a hint.

Obviously there's a version number shown on the login's pop-up, so there's something somewhere to be read, but it isn't apparent where that detail resides. A "version.md/version.txt" file in web root would be an obvious spot - right next to the readme and license files

**Comment by d7415** [comment]
fwiw, the version seems to be [here](https://github.com/LycheeOrg/Lychee/blob/master/dist/main.js#L2067) and in the database (`select value from lychee_settings where lychee_settings.key='version';`)

**Comment by ildyria** [comment]
done.
