### ISSUE TITLE
Wiki update: Installation

### ISSUE THREAD

**Issue by d7415** [LycheeOrg/Lychee-v3#82]
[Installation](https://github.com/LycheeOrg/Lychee/wiki/Installation#1-requirements) page still refers to an electerious issue in the requirements section. All these issues have now been deleted.

**Comment by LudovicRousseau** [comment]
How do you propose to solve the issue?
What was Issue #106 talking about?

**Comment by d7415** [comment]
I have no idea as it's not there. Unless someone can remember, I'd propose removing the reference.

**Comment by LudovicRousseau** [comment]
Fixed
