### ISSUE TITLE
About Photo panel show two `Format` attr

### ISSUE THREAD

**Issue by yuhr123** [LycheeOrg/Lychee-v3#88]
### Detailed description of the problem
Lychee 3.1.9

![shutter_10](https://user-images.githubusercontent.com/3388604/48248134-131d0700-e431-11e8-836b-925a53d85b77.png)

I think the second Format attr text should be `RESOLUTION`.

### Browser and system
Firefox 63

**Comment by LudovicRousseau** [comment]
Or maybe "Dimension"?

I found that "resolution" is often the total number of pixels (12 millions for your example) or the number of pixel by distance unit in PPI (pixel per inch)

**Comment by d7415** [comment]
I'd automatically go "resolution", but I'd understand "dimension". Resolution is already in the locales as `PHOTO_RESOLUTION`. I'd only expect PPI if discussing printed work/printing.

**Comment by yuhr123** [comment]
Yep, just don't let both are named `Format`.

**Comment by LudovicRousseau** [comment]
Fixed.
