### ISSUE TITLE
Archive the old repo and move some issues

### ISSUE THREAD

**Issue by muuvmuuv** [LycheeOrg/Lychee-v3#9]
Now there two repositories existing and I accidentally posted an issue on the wrong repo. Please archive the old one or delete all files with one referer to that one here and maybe move some issues that are only between two months old to this.

**Comment by LudovicRousseau** [comment]
Maybe a good idea.
I found this project to move github issues https://github.com/google/github-issue-mover

I see people are still creating issues in the old repository. The latest one was created 2 days ago.

**Comment by ildyria** [comment]
Well only @electerious  can do that.

**Comment by LudovicRousseau** [comment]
@electerious do not have write access to https://github.com/LycheeOrg/Lychee so he can't. But I can arrange that.

I do not have write access to https://github.com/electerious/Lychee so I can't either.

Our life would be much simpler if github issues were in a git repository. Just ``git clone`` and that's it.

**Comment by ildyria** [comment]
I meant only @electerious can archive his repository.

**Comment by electerious** [comment]
I would like to keep the old repo, close all existing issues with a link to this fork and disable the GitHub issues.  Let me know if there's anything you want to move/copy before the issues are gone.

**Comment by ildyria** [comment]
@electerious I think I moved the most important ones but I might have missed some. :smiley:

**Comment by muuvmuuv** [comment]
Just take the last year I think. All others are too old to take care of.

**Comment by ildyria** [comment]
@muuvmuuv Some of the issues are not applicable as some pull request have not been ported from electerious to here.

**Comment by muuvmuuv** [comment]
@ildyria okay than it is just fine to remove them all as you have moved the important ones

**Comment by electerious** [comment]
All issues and PRs have been closed with a link to this repository. Keep up the good work and thanks for pushing Lychee forward 🤟

**Comment by muuvmuuv** [comment]
So we can close this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ildyria** [comment]
I guess so.
