### ISSUE TITLE
Add Content Security Policy (CSP) for Security

### ISSUE THREAD

**Issue by PeterTheOne** [LycheeOrg/Lychee-v3#91]
Add a [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) for Security. It protects agains Cross Site Scripting (XSS) and data injection attacks. I'm using `default-src 'none'; style-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self'; prefetch-src 'self'; block-all-mixed-content; form-action 'none'; base-uri 'none'; frame-ancestors 'none';` (in my .htacces file) right now. `default-src 'none'` sets everything to none and the other policies open up what is needed (whitelisting).

A CSP can be added in the `.htaccess` file (Apache) or as a meta tag in the `index.html` file.

**Comment by ildyria** [comment]
Can you make a PR with it ? :)
