### ISSUE TITLE
masonry grid

### ISSUE THREAD

**Issue by fatherb** [LycheeOrg/Lychee-v3#95]
Hi. Any chance of adding a masonry grid in Lychee rather than the cropped images.

**Comment by ildyria** [comment]
@fatherb I plan to add https://github.com/flickr/justified-layout in a future release.

**Comment by ildyria** [comment]
Implemented in Lychee-Laravel (currently by default, will be an option soon to make it available to Lychee too).

**Comment by ildyria** [comment]
Added with https://github.com/LycheeOrg/Lychee/commit/1bb5acd2815852fb9808feedef7860cd10917909
