### ISSUE TITLE
allow mp3 and mp4/video error

### ISSUE THREAD

**Issue by Gaeta** [LycheeOrg/Lychee-v3#98]
### Detailed description of the problem
When upload a mp4 it finishes and it will not play because of this

https://files.gitter.im/LycheeOrg/Lobby/aIgr/image.png

### Steps to reproduce the issue

Upload mp4
try to play

### Output of the diagnostics (Settings => Diagnostics)

```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version (json):  3.2.0
DB Version:             update_030109
System:                 Linux
PHP Version:            7
MySQL Version:          50641
Imagick:                -
Imagick Active:         1
Imagick Version:        -
GD Version:             bundled (2.1.0 compatible)
Plugins:                
```

### Browser and system

Latest Chrome

And can you add mp3?

**Comment by d7415** [comment]
It looks like you have a custom Content-Security-Policy set. The bundled one in .htaccess has `prefetch-src 'self';` set explicitly.

**Comment by Gaeta** [comment]
ok then how do i allow mp3 to be uploaded?

**Comment by Gaeta** [comment]
that accully did not work i need to change
```
Header set Content-Security-Policy "default-src 'none'; style-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self'; prefetch-src 'self'; block-all-mixed-content; form-action 'none'; base-uri 'none'; frame-ancestors 'none';"
```

to

```
#Header set Content-Security-Policy "default-src 'none'; style-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self'; prefetch-src 'self'; block-all-mixed-content; form-action 'none'; base-uri 'none'; frame-ancestors 'none';"
``` (so disabled it)

**Comment by d7415** [comment]
> ok then how do i allow mp3 to be uploaded?

mp3 isn't currently supported

**Comment by d7415** [comment]
> that accully did not work i need to change
> 
> ```
> Header set Content-Security-Policy "default-src 'none'; style-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self'; prefetch-src 'self'; block-all-mixed-content; form-action 'none'; base-uri 'none'; frame-ancestors 'none';"
> ```
> to
> 
> ```
> #Header set Content-Security-Policy "default-src 'none'; style-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self'; prefetch-src 'self'; block-all-mixed-content; form-action 'none'; base-uri 'none'; frame-ancestors 'none';"
> ``` (so disabled it)
> ```

That's strange... I'm unable to test as I'm not using apache, but your error message says that `prefetch-src` is not set, and it is set in that list. I was about to suggest checking your server configuration, but if commenting out that line fixes the problem then it won't be that.

**Comment by Gaeta** [comment]
do you know when mp3 will be supported?

**Comment by d7415** [comment]
I'd suggest you add that feature request as a separate issue. It should be possible, but I don't think anyone's working on it at the moment.
